In [1]:
import pandas as pd
import numpy as np

print("DataTrust environment is working!")
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

DataTrust environment is working!
Pandas version: 3.0.6
NumPy version: 2.5.3

In [2]:
from pathlib import Path

# DataTrust project root
PROJECT_ROOT = Path.cwd().parent

# Data directories
DATA_DIR = PROJECT_ROOT / "data"
INCOMING_DIR = DATA_DIR / "incoming"

# Make sure the incoming directory exists
INCOMING_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Incoming data folder:", INCOMING_DIR)

Project root: /Users/aryayogirajingale/Documents/DataTrust
Incoming data folder: /Users/aryayogirajingale/Documents/DataTrust/data/incoming

In [3]:
import random

# Fixed seed for reproducible data generation
RANDOM_SEED = 42

np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)

print("Random seed set to:", RANDOM_SEED)

Random seed set to: 42

In [4]:
# Number of customers to generate
NUM_CUSTOMERS = 50_000

# Customer segments
CUSTOMER_SEGMENTS = [
    "Consumer",
    "Corporate",
    "Home Office"
]

# U.S. regions used by NovaRetail
REGIONS = [
    "Northeast",
    "Midwest",
    "South",
    "West"
]

print("Customer dataset configuration created.")
print("Customers to generate:", f"{NUM_CUSTOMERS:,}")
print("Segments:", CUSTOMER_SEGMENTS)
print("Regions:", REGIONS)

Customer dataset configuration created.
Customers to generate: 50,000
Segments: ['Consumer', 'Corporate', 'Home Office']
Regions: ['Northeast', 'Midwest', 'South', 'West']

In [5]:
# Geographic reference data for customer generation

LOCATION_DATA = [
    # South
    {"city": "Dallas", "state": "TX", "region": "South"},
    {"city": "Houston", "state": "TX", "region": "South"},
    {"city": "Austin", "state": "TX", "region": "South"},
    {"city": "Atlanta", "state": "GA", "region": "South"},
    {"city": "Miami", "state": "FL", "region": "South"},
    {"city": "Orlando", "state": "FL", "region": "South"},
    {"city": "Charlotte", "state": "NC", "region": "South"},

    # West
    {"city": "Los Angeles", "state": "CA", "region": "West"},
    {"city": "San Francisco", "state": "CA", "region": "West"},
    {"city": "San Diego", "state": "CA", "region": "West"},
    {"city": "Seattle", "state": "WA", "region": "West"},
    {"city": "Phoenix", "state": "AZ", "region": "West"},
    {"city": "Denver", "state": "CO", "region": "West"},

    # Midwest
    {"city": "Chicago", "state": "IL", "region": "Midwest"},
    {"city": "Columbus", "state": "OH", "region": "Midwest"},
    {"city": "Detroit", "state": "MI", "region": "Midwest"},
    {"city": "Indianapolis", "state": "IN", "region": "Midwest"},
    {"city": "Minneapolis", "state": "MN", "region": "Midwest"},
    {"city": "Kansas City", "state": "MO", "region": "Midwest"},

    # Northeast
    {"city": "New York", "state": "NY", "region": "Northeast"},
    {"city": "Boston", "state": "MA", "region": "Northeast"},
    {"city": "Philadelphia", "state": "PA", "region": "Northeast"},
    {"city": "Pittsburgh", "state": "PA", "region": "Northeast"},
    {"city": "Buffalo", "state": "NY", "region": "Northeast"},
    {"city": "Newark", "state": "NJ", "region": "Northeast"}
]

locations_df = pd.DataFrame(LOCATION_DATA)

print("Geographic reference data created.")
print("Number of locations:", len(locations_df))

locations_df.head(10)

Geographic reference data created.
Number of locations: 25

            city state region
0         Dallas    TX  South
1        Houston    TX  South
2         Austin    TX  South
3        Atlanta    GA  South
4          Miami    FL  South
5        Orlando    FL  South
6      Charlotte    NC  South
7    Los Angeles    CA   West
8  San Francisco    CA   West
9      San Diego    CA   West

In [6]:
# Sample first names
FIRST_NAMES = [
    "James", "Mary", "John", "Patricia", "Robert",
    "Jennifer", "Michael", "Linda", "William", "Elizabeth",
    "David", "Barbara", "Richard", "Susan", "Joseph",
    "Jessica", "Thomas", "Sarah", "Charles", "Karen",
    "Daniel", "Nancy", "Matthew", "Lisa", "Anthony",
    "Betty", "Mark", "Margaret", "Donald", "Sandra",
    "Steven", "Ashley", "Andrew", "Kimberly", "Joshua",
    "Emily", "Kevin", "Donna", "Brian", "Michelle",
    "Christopher", "Amanda", "Jason", "Melissa", "Ryan",
    "Stephanie", "Eric", "Rebecca", "Jonathan", "Laura"
]

# Sample last names
LAST_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones",
    "Garcia", "Miller", "Davis", "Rodriguez", "Martinez",
    "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson",
    "Thomas", "Taylor", "Moore", "Jackson", "Martin",
    "Lee", "Perez", "Thompson", "White", "Harris",
    "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson",
    "Walker", "Young", "Allen", "King", "Wright",
    "Scott", "Torres", "Nguyen", "Hill", "Flores",
    "Green", "Adams", "Nelson", "Baker", "Hall",
    "Rivera", "Campbell", "Mitchell", "Carter", "Roberts"
]

print("Customer name reference data created.")
print("First names:", len(FIRST_NAMES))
print("Last names:", len(LAST_NAMES))

Customer name reference data created.
First names: 50
Last names: 50

In [7]:
# Sample first and last names for customer generation

FIRST_NAMES = [
    "James", "Mary", "John", "Patricia", "Robert",
    "Jennifer", "Michael", "Linda", "William", "Elizabeth",
    "David", "Barbara", "Richard", "Susan", "Joseph",
    "Jessica", "Thomas", "Sarah", "Charles", "Karen",
    "Christopher", "Nancy", "Daniel", "Lisa", "Matthew",
    "Betty", "Anthony", "Margaret", "Mark", "Sandra",
    "Donald", "Ashley", "Steven", "Kimberly", "Paul",
    "Emily", "Andrew", "Donna", "Joshua", "Michelle",
    "Kenneth", "Carol", "Kevin", "Amanda", "Brian",
    "Melissa", "George", "Deborah", "Edward", "Stephanie"
]

LAST_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones",
    "Garcia", "Miller", "Davis", "Rodriguez", "Martinez",
    "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson",
    "Thomas", "Taylor", "Moore", "Jackson", "Martin",
    "Lee", "Perez", "Thompson", "White", "Harris",
    "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson",
    "Walker", "Young", "Allen", "King", "Wright",
    "Scott", "Torres", "Nguyen", "Hill", "Flores",
    "Green", "Adams", "Nelson", "Baker", "Hall",
    "Rivera", "Campbell", "Mitchell", "Carter", "Roberts"
]

print("Customer name reference data created.")
print("First names:", len(FIRST_NAMES))
print("Last names:", len(LAST_NAMES))

Customer name reference data created.
First names: 50
Last names: 50

In [8]:
# Email domains used in the synthetic customer dataset
EMAIL_DOMAINS = [
    "gmail.com",
    "yahoo.com",
    "outlook.com",
    "icloud.com"
]


def generate_email(first_name, last_name, customer_number):
    """
    Generate a unique email address for a customer.
    """
    domain = random.choice(EMAIL_DOMAINS)

    email = (
        f"{first_name.lower()}."
        f"{last_name.lower()}"
        f"{customer_number}@{domain}"
    )

    return email


def generate_phone():
    """
    Generate a synthetic 10-digit US-style phone number.
    """
    area_code = random.randint(200, 999)
    prefix = random.randint(200, 999)
    line_number = random.randint(1000, 9999)

    return f"{area_code}-{prefix}-{line_number}"

In [9]:
test_email = generate_email(
    "Emily",
    "Johnson",
    1001
)

test_phone = generate_phone()

print("Test email:", test_email)
print("Test phone:", test_phone)

Test email: emily.johnson1001@gmail.com
Test phone: 225-959-5506

In [10]:
# Generate clean customer records

customers = []

for i in range(1, NUM_CUSTOMERS + 1):

    # Unique customer ID
    customer_id = f"C{i:06d}"

    # Random customer name
    first_name = random.choice(FIRST_NAMES)
    last_name = random.choice(LAST_NAMES)

    # Select a valid city/state/region combination
    location = random.choice(LOCATION_DATA)

    city = location["city"]
    state = location["state"]
    region = location["region"]

    # Customer segment
    customer_segment = random.choices(
        CUSTOMER_SEGMENTS,
        weights=[0.70, 0.20, 0.10],
        k=1
    )[0]

    # Contact information
    email = generate_email(first_name, last_name, i)
    phone = generate_phone()

    # Random signup date between 2021 and 2025
    start_date = pd.Timestamp("2021-01-01")
    end_date = pd.Timestamp("2025-12-31")

    signup_date = start_date + pd.to_timedelta(
        random.randint(0, (end_date - start_date).days),
        unit="D"
    )

    customers.append({
        "customer_id": customer_id,
        "first_name": first_name,
        "last_name": last_name,
        "email": email,
        "phone": phone,
        "city": city,
        "state": state,
        "region": region,
        "customer_segment": customer_segment,
        "signup_date": signup_date
    })


# Convert records into a DataFrame
customers_clean_df = pd.DataFrame(customers)

print("Customer dataset generated successfully!")
print("Number of rows:", len(customers_clean_df))
print("Number of columns:", len(customers_clean_df.columns))

customers_clean_df.head()

Customer dataset generated successfully!
Number of rows: 50000
Number of columns: 10

,customer_id,first_name,last_name,email,phone,city,state,region,customer_segment,signup_date
0,C000001,Jessica,Anderson,jessica.anderson1@gmail.com,804-632-1520,Miami,FL,South,Corporate,2021-03-03
1,C000002,Jennifer,Wilson,jennifer.wilson2@gmail.com,774-403-9928,Los Angeles,CA,West,Consumer,2023-05-10
2,C000003,Joseph,Lewis,joseph.lewis3@gmail.com,977-363-7924,Kansas City,MO,Midwest,Consumer,2022-11-28
3,C000004,Sarah,Martinez,sarah.martinez4@outlook.com,304-294-7224,Charlotte,NC,South,Home Office,2021-07-18
4,C000005,Daniel,Thompson,daniel.thompson5@gmail.com,947-670-9785,New York,NY,Northeast,Consumer,2021-09-13

In [11]:
# Basic validation of the clean customer dataset

print("=== CUSTOMER DATA VALIDATION ===")

# 1. Dataset size
print("\nDataset shape:")
print(customers_clean_df.shape)

# 2. Missing values
print("\nMissing values:")
print(customers_clean_df.isnull().sum())

# 3. Duplicate customer IDs
duplicate_ids = customers_clean_df["customer_id"].duplicated().sum()

print("\nDuplicate customer IDs:")
print(duplicate_ids)

# 4. Unique customer IDs
print("\nUnique customer IDs:")
print(customers_clean_df["customer_id"].nunique())

# 5. Customer segment distribution
print("\nCustomer segment distribution:")
print(customers_clean_df["customer_segment"].value_counts())

# 6. Region distribution
print("\nRegion distribution:")
print(customers_clean_df["region"].value_counts())

# 7. Signup date range
print("\nSignup date range:")
print(
    customers_clean_df["signup_date"].min(),
    "to",
    customers_clean_df["signup_date"].max()
)

=== CUSTOMER DATA VALIDATION ===

Dataset shape:
(50000, 10)

Missing values:
customer_id         0
first_name          0
last_name           0
email               0
phone               0
city                0
state               0
region              0
customer_segment    0
signup_date         0
dtype: int64

Duplicate customer IDs:
0

Unique customer IDs:
50000

Customer segment distribution:
customer_segment
Consumer       35011
Corporate      10042
Home Office     4947
Name: count, dtype: int64

Region distribution:
region
South        14106
West         12148
Midwest      12018
Northeast    11728
Name: count, dtype: int64

Signup date range:
2021-01-01 00:00:00 to 2025-12-31 00:00:00

In [12]:
# Create a protected copy of the clean customer dataset

customers_ground_truth_df = customers_clean_df.copy(deep=True)

print("Clean customer baseline preserved.")
print("Rows:", len(customers_ground_truth_df))
print("Columns:", len(customers_ground_truth_df.columns))

Clean customer baseline preserved.
Rows: 50000
Columns: 10

In [13]:
# Create the working copy that will receive intentional data-quality issues
customers_dirty_df = customers_ground_truth_df.copy(deep=True)

# Store information about every intentionally injected issue
customer_issue_log = []

print("Dirty customer dataset initialized.")
print("Rows:", len(customers_dirty_df))
print("Issue log initialized:", len(customer_issue_log))

Dirty customer dataset initialized.
Rows: 50000
Issue log initialized: 0

In [14]:
# ---------------------------------------------------------
# Inject Issue 1: Missing Region Values
# ---------------------------------------------------------

missing_region_rate = 0.01

# Calculate number of rows to corrupt
num_missing_regions = int(
    len(customers_dirty_df) * missing_region_rate
)

# Randomly select rows
missing_region_indices = np.random.choice(
    customers_dirty_df.index,
    size=num_missing_regions,
    replace=False
)

# Log the issue BEFORE changing the data
for idx in missing_region_indices:

    customer_issue_log.append({
        "customer_id": customers_dirty_df.loc[idx, "customer_id"],
        "issue_type": "missing_value",
        "column": "region",
        "original_value": customers_dirty_df.loc[idx, "region"],
        "injected_value": None
    })

# Inject missing values
customers_dirty_df.loc[
    missing_region_indices,
    "region"
] = None

print("Missing region values injected:", num_missing_regions)
print(
    "Current missing regions:",
    customers_dirty_df["region"].isnull().sum()
)

print(
    "Total issues logged:",
    len(customer_issue_log)
)

Missing region values injected: 500
Current missing regions: 500
Total issues logged: 500

In [15]:
customers_dirty_df[
    customers_dirty_df["region"].isnull()
].head(10)

,customer_id,first_name,last_name,email,phone,city,state,region,customer_segment,signup_date
147,C000148,Anthony,Adams,anthony.adams148@icloud.com,486-233-7070,Atlanta,GA,NaN,Corporate,2022-03-21
199,C000200,Lisa,Baker,lisa.baker200@icloud.com,825-491-8355,Buffalo,NY,NaN,Consumer,2022-04-25
262,C000263,William,King,william.king263@icloud.com,738-585-6140,Charlotte,NC,NaN,Consumer,2021-12-21
292,C000293,Sandra,Baker,sandra.baker293@icloud.com,435-453-8546,Buffalo,NY,NaN,Consumer,2022-12-10
314,C000315,Susan,Allen,susan.allen315@icloud.com,875-699-1257,Columbus,OH,NaN,Consumer,2021-01-14
508,C000509,George,Campbell,george.campbell509@yahoo.com,667-503-5327,Atlanta,GA,NaN,Home Office,2023-08-09
659,C000660,Richard,Taylor,richard.taylor660@gmail.com,986-931-5078,Denver,CO,NaN,Corporate,2023-02-28
708,C000709,Matthew,Nelson,matthew.nelson709@outlook.com,310-219-5792,San Francisco,CA,NaN,Consumer,2025-11-12
725,C000726,Michelle,Young,michelle.young726@icloud.com,452-637-7633,Pittsburgh,PA,NaN,Consumer,2025-05-09
821,C000822,Paul,Roberts,paul.roberts822@gmail.com,652-932-5243,Chicago,IL,NaN,Consumer,2021-07-31

In [16]:
# ---------------------------------------------------------
# Inject Issue 2: Invalid Email Addresses
# ---------------------------------------------------------

invalid_email_rate = 0.008

num_invalid_emails = int(
    len(customers_dirty_df) * invalid_email_rate
)

# Avoid customers already used for missing-region injection
available_indices = customers_dirty_df.index.difference(
    missing_region_indices
)

# Randomly select rows
invalid_email_indices = np.random.choice(
    available_indices,
    size=num_invalid_emails,
    replace=False
)

# Log original values BEFORE modifying them
for idx in invalid_email_indices:

    original_email = customers_dirty_df.loc[idx, "email"]

    # Remove @ to deliberately create an invalid email
    invalid_email = original_email.replace("@", "")

    customer_issue_log.append({
        "customer_id": customers_dirty_df.loc[idx, "customer_id"],
        "issue_type": "invalid_format",
        "column": "email",
        "original_value": original_email,
        "injected_value": invalid_email
    })

    # Inject corrupted email
    customers_dirty_df.loc[idx, "email"] = invalid_email


print("Invalid emails injected:", num_invalid_emails)

print(
    "Total issues logged:",
    len(customer_issue_log)
)

Invalid emails injected: 400
Total issues logged: 900

In [17]:
customers_dirty_df.loc[
    invalid_email_indices,
    ["customer_id", "email"]
].head(10)

      customer_id                            email
31712     C031713       edward.scott31713yahoo.com
4372      C004373     sandra.williams4373yahoo.com
11105     C011106       john.flores11106icloud.com
32528     C032529  patricia.torres32529outlook.com
4121      C004122    barbara.campbell4122gmail.com
2510      C002511   patricia.rivera2511outlook.com
27715     C027716        james.young27716gmail.com
25259     C025260     betty.anderson25260gmail.com
43889     C043890     joseph.baker43890outlook.com
5685      C005686    robert.ramirez5686outlook.com

In [18]:
# ---------------------------------------------------------
# Inject Issue 3: Geographic Region Mismatch
# ---------------------------------------------------------

region_mismatch_rate = 0.006

num_region_mismatches = int(
    len(customers_dirty_df) * region_mismatch_rate
)

# Exclude rows already corrupted
used_indices = set(missing_region_indices) | set(invalid_email_indices)

available_indices = customers_dirty_df.index[
    ~customers_dirty_df.index.isin(used_indices)
]

# Randomly select rows
region_mismatch_indices = np.random.choice(
    available_indices,
    size=num_region_mismatches,
    replace=False
)

# Inject incorrect regions
for idx in region_mismatch_indices:

    original_region = customers_dirty_df.loc[idx, "region"]

    # Select a region different from the correct one
    incorrect_regions = [
        region for region in REGIONS
        if region != original_region
    ]

    incorrect_region = random.choice(incorrect_regions)

    # Log the issue
    customer_issue_log.append({
        "customer_id": customers_dirty_df.loc[idx, "customer_id"],
        "issue_type": "consistency_error",
        "column": "region",
        "original_value": original_region,
        "injected_value": incorrect_region
    })

    # Replace correct region with incorrect region
    customers_dirty_df.loc[idx, "region"] = incorrect_region


print("Region mismatches injected:", num_region_mismatches)

print(
    "Total issues logged:",
    len(customer_issue_log)
)

Region mismatches injected: 300
Total issues logged: 1200

In [19]:
customers_dirty_df.loc[
    region_mismatch_indices,
    ["customer_id", "city", "state", "region"]
].head(10)

      customer_id          city state   region
11836     C011837      New York    NY    South
34006     C034007  Indianapolis    IN    South
9696      C009697       Atlanta    GA     West
29772     C029773    Pittsburgh    PA     West
26418     C026419     San Diego    CA    South
26183     C026184    Pittsburgh    PA  Midwest
17440     C017441  Philadelphia    PA  Midwest
44742     C044743        Newark    NJ  Midwest
8284      C008285        Dallas    TX  Midwest
18161     C018162      New York    NY     West

In [20]:
# ---------------------------------------------------------
# Inject Issue 4: Duplicate Customer Records
# ---------------------------------------------------------

num_duplicate_customers = 200

# Select records that have not already been corrupted
used_indices = (
    set(missing_region_indices)
    | set(invalid_email_indices)
    | set(region_mismatch_indices)
)

available_indices = customers_dirty_df.index[
    ~customers_dirty_df.index.isin(used_indices)
]

# Randomly select customers to duplicate
duplicate_source_indices = np.random.choice(
    available_indices,
    size=num_duplicate_customers,
    replace=False
)

# Copy selected customer records
duplicate_records = customers_dirty_df.loc[
    duplicate_source_indices
].copy()

# Log each duplicate
for idx in duplicate_source_indices:

    customer_issue_log.append({
        "customer_id": customers_dirty_df.loc[idx, "customer_id"],
        "issue_type": "duplicate_record",
        "column": "customer_id",
        "original_value": customers_dirty_df.loc[idx, "customer_id"],
        "injected_value": customers_dirty_df.loc[idx, "customer_id"]
    })

# Append duplicates to the dirty dataset
customers_dirty_df = pd.concat(
    [customers_dirty_df, duplicate_records],
    ignore_index=True
)

print("Duplicate customer records injected:", num_duplicate_customers)
print("New customer dataset size:", len(customers_dirty_df))
print("Total issues logged:", len(customer_issue_log))

Duplicate customer records injected: 200
New customer dataset size: 50200
Total issues logged: 1400

In [21]:
duplicate_check = customers_dirty_df[
    customers_dirty_df.duplicated(
        subset=["customer_id"],
        keep=False
    )
].sort_values("customer_id")

print(
    "Rows involved in duplicate customer IDs:",
    len(duplicate_check)
)

print(
    "Customer IDs with duplicates:",
    duplicate_check["customer_id"].nunique()
)

duplicate_check.head(10)

Rows involved in duplicate customer IDs: 400
Customer IDs with duplicates: 200

,customer_id,first_name,last_name,email,phone,city,state,region,customer_segment,signup_date
70,C000071,Paul,Robinson,paul.robinson71@icloud.com,598-988-1320,Chicago,IL,Midwest,Consumer,2025-10-21
50132,C000071,Paul,Robinson,paul.robinson71@icloud.com,598-988-1320,Chicago,IL,Midwest,Consumer,2025-10-21
272,C000273,Jennifer,Adams,jennifer.adams273@gmail.com,379-627-3880,Kansas City,MO,Midwest,Consumer,2021-03-16
50085,C000273,Jennifer,Adams,jennifer.adams273@gmail.com,379-627-3880,Kansas City,MO,Midwest,Consumer,2021-03-16
563,C000564,Amanda,Campbell,amanda.campbell564@gmail.com,766-768-3316,Boston,MA,Northeast,Consumer,2021-09-10
50094,C000564,Amanda,Campbell,amanda.campbell564@gmail.com,766-768-3316,Boston,MA,Northeast,Consumer,2021-09-10
628,C000629,Barbara,Young,barbara.young629@outlook.com,573-610-5581,Chicago,IL,Midwest,Consumer,2023-07-13
50116,C000629,Barbara,Young,barbara.young629@outlook.com,573-610-5581,Chicago,IL,Midwest,Consumer,2023-07-13
655,C000656,Patricia,Wright,patricia.wright656@gmail.com,488-475-3048,Dallas,TX,South,Consumer,2025-01-04
50034,C000656,Patricia,Wright,patricia.wright656@gmail.com,488-475-3048,Dallas,TX,South,Consumer,2025-01-04

In [22]:
# ---------------------------------------------------------
# Convert Customer Issue Log to DataFrame
# ---------------------------------------------------------

customer_issue_log_df = pd.DataFrame(customer_issue_log)

print("Customer issue log created successfully!")

print(
    "Total logged issues:",
    len(customer_issue_log_df)
)

print("\nIssues by type:")
print(
    customer_issue_log_df["issue_type"].value_counts()
)

customer_issue_log_df.head(10)

Customer issue log created successfully!
Total logged issues: 1400

Issues by type:
issue_type
missing_value        500
invalid_format       400
consistency_error    300
duplicate_record     200
Name: count, dtype: int64

  customer_id     issue_type  column original_value injected_value
0     C033554  missing_value  region        Midwest            NaN
1     C009428  missing_value  region        Midwest            NaN
2     C000200  missing_value  region      Northeast            NaN
3     C012448  missing_value  region          South            NaN
4     C039490  missing_value  region           West            NaN
5     C042725  missing_value  region           West            NaN
6     C010823  missing_value  region           West            NaN
7     C049499  missing_value  region      Northeast            NaN
8     C004145  missing_value  region          South            NaN
9     C036959  missing_value  region      Northeast            NaN

In [23]:
# Verify expected issue counts

expected_issue_counts = {
    "missing_value": 500,
    "invalid_format": 400,
    "consistency_error": 300,
    "duplicate_record": 200
}

actual_issue_counts = (
    customer_issue_log_df["issue_type"]
    .value_counts()
    .to_dict()
)

for issue_type, expected_count in expected_issue_counts.items():

    actual_count = actual_issue_counts.get(issue_type, 0)

    status = "PASS" if actual_count == expected_count else "FAIL"

    print(
        f"{issue_type}: "
        f"Expected={expected_count}, "
        f"Actual={actual_count} "
        f"[{status}]"
    )

missing_value: Expected=500, Actual=500 [PASS]
invalid_format: Expected=400, Actual=400 [PASS]
consistency_error: Expected=300, Actual=300 [PASS]
duplicate_record: Expected=200, Actual=200 [PASS]

In [24]:
# ---------------------------------------------------------
# Save Customer Dataset and Ground-Truth Issue Log
# ---------------------------------------------------------

# File paths
customer_file = INCOMING_DIR / "customers.csv"

issue_log_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "customer_issue_ground_truth.csv"
)

# Save dirty customer data
customers_dirty_df.to_csv(
    customer_file,
    index=False
)

# Save issue ground-truth log
customer_issue_log_df.to_csv(
    issue_log_file,
    index=False
)

print("Files saved successfully!")

print("\nCustomer file:")
print(customer_file)

print("\nGround-truth issue log:")
print(issue_log_file)

Files saved successfully!

Customer file:
/Users/aryayogirajingale/Documents/DataTrust/data/incoming/customers.csv

Ground-truth issue log:
/Users/aryayogirajingale/Documents/DataTrust/data/raw/customer_issue_ground_truth.csv

In [25]:
# Verify saved files

print("customers.csv exists:", customer_file.exists())
print("issue log exists:", issue_log_file.exists())

print("\ncustomers.csv size:")
print(f"{customer_file.stat().st_size / 1024 / 1024:.2f} MB")

print("\nSaved customer rows:")
saved_customers = pd.read_csv(customer_file)
print(len(saved_customers))

customers.csv exists: True
issue log exists: True

customers.csv size:
5.02 MB

Saved customer rows:
50200

In [26]:
# ---------------------------------------------------------
# Product Dataset Configuration
# ---------------------------------------------------------

NUM_PRODUCTS = 2_000

PRODUCT_CATEGORIES = {
    "Electronics": [
        "Laptops",
        "Smartphones",
        "Tablets",
        "Headphones",
        "Monitors"
    ],

    "Home & Kitchen": [
        "Kitchen Appliances",
        "Cookware",
        "Furniture",
        "Home Decor",
        "Storage"
    ],

    "Office Supplies": [
        "Writing Supplies",
        "Paper",
        "Desk Accessories",
        "Printers",
        "Office Furniture"
    ],

    "Sports & Outdoors": [
        "Fitness Equipment",
        "Outdoor Gear",
        "Sports Accessories",
        "Cycling",
        "Camping"
    ],

    "Clothing": [
        "Men's Clothing",
        "Women's Clothing",
        "Footwear",
        "Accessories",
        "Activewear"
    ]
}

print("Product dataset configuration created.")
print("Products to generate:", f"{NUM_PRODUCTS:,}")
print("Number of categories:", len(PRODUCT_CATEGORIES))

print("\nProduct categories:")

for category, subcategories in PRODUCT_CATEGORIES.items():
    print(f"{category}: {len(subcategories)} subcategories")

Product dataset configuration created.
Products to generate: 2,000
Number of categories: 5

Product categories:
Electronics: 5 subcategories
Home & Kitchen: 5 subcategories
Office Supplies: 5 subcategories
Sports & Outdoors: 5 subcategories
Clothing: 5 subcategories

In [27]:
# ---------------------------------------------------------
# Fictional Product Brands
# ---------------------------------------------------------

BRANDS_BY_CATEGORY = {

    "Electronics": [
        "NovaTech",
        "Vertex Electronics",
        "Pulse Digital",
        "Apex Devices",
        "Orbit Technologies"
    ],

    "Home & Kitchen": [
        "HavenHome",
        "PureLiving",
        "UrbanNest",
        "Oak & Stone",
        "HomeCraft"
    ],

    "Office Supplies": [
        "WorkEdge",
        "DeskPro",
        "PaperPoint",
        "OfficeCore",
        "PrimeDesk"
    ],

    "Sports & Outdoors": [
        "PeakMotion",
        "TrailForge",
        "ActiveCore",
        "SummitGear",
        "Velocity Sports"
    ],

    "Clothing": [
        "UrbanThread",
        "NorthLane",
        "ModeCraft",
        "EverWear",
        "Stride"
    ]
}

print("Product brands created.")

for category, brands in BRANDS_BY_CATEGORY.items():
    print(f"{category}: {len(brands)} brands")

Product brands created.
Electronics: 5 brands
Home & Kitchen: 5 brands
Office Supplies: 5 brands
Sports & Outdoors: 5 brands
Clothing: 5 brands

In [28]:
# ---------------------------------------------------------
# Product Cost and Price Configuration
# ---------------------------------------------------------

PRODUCT_PRICE_RANGES = {

    "Electronics": {
        "cost_min": 40,
        "cost_max": 1200,
        "markup_min": 1.15,
        "markup_max": 1.60
    },

    "Home & Kitchen": {
        "cost_min": 10,
        "cost_max": 600,
        "markup_min": 1.20,
        "markup_max": 1.70
    },

    "Office Supplies": {
        "cost_min": 2,
        "cost_max": 350,
        "markup_min": 1.20,
        "markup_max": 1.80
    },

    "Sports & Outdoors": {
        "cost_min": 8,
        "cost_max": 700,
        "markup_min": 1.20,
        "markup_max": 1.70
    },

    "Clothing": {
        "cost_min": 5,
        "cost_max": 180,
        "markup_min": 1.30,
        "markup_max": 2.20
    }
}

print("Product pricing configuration created.")

for category, values in PRODUCT_PRICE_RANGES.items():

    print(
        f"{category}: "
        f"Cost ${values['cost_min']} - ${values['cost_max']} | "
        f"Markup {values['markup_min']}x - {values['markup_max']}x"
    )

Product pricing configuration created.
Electronics: Cost $40 - $1200 | Markup 1.15x - 1.6x
Home & Kitchen: Cost $10 - $600 | Markup 1.2x - 1.7x
Office Supplies: Cost $2 - $350 | Markup 1.2x - 1.8x
Sports & Outdoors: Cost $8 - $700 | Markup 1.2x - 1.7x
Clothing: Cost $5 - $180 | Markup 1.3x - 2.2x

In [29]:
# ---------------------------------------------------------
# Generate Clean Product Dataset
# ---------------------------------------------------------

products = []

for i in range(1, NUM_PRODUCTS + 1):

    # Unique product ID
    product_id = f"P{i:05d}"

    # Select category
    category = random.choice(list(PRODUCT_CATEGORIES.keys()))

    # Select valid subcategory belonging to that category
    subcategory = random.choice(
        PRODUCT_CATEGORIES[category]
    )

    # Select brand belonging to that category
    brand = random.choice(
        BRANDS_BY_CATEGORY[category]
    )

    # Generate product name
    product_name = f"{brand} {subcategory} {i:04d}"

    # Get pricing configuration
    pricing = PRODUCT_PRICE_RANGES[category]

    # Generate product cost
    unit_cost = round(
        random.uniform(
            pricing["cost_min"],
            pricing["cost_max"]
        ),
        2
    )

    # Generate markup
    markup = random.uniform(
        pricing["markup_min"],
        pricing["markup_max"]
    )

    # Selling price
    unit_price = round(
        unit_cost * markup,
        2
    )

    # Supplier
    supplier_id = f"S{random.randint(1, 50):03d}"

    # Product launch date
    start_date = pd.Timestamp("2019-01-01")
    end_date = pd.Timestamp("2025-12-31")

    launch_date = start_date + pd.to_timedelta(
        random.randint(
            0,
            (end_date - start_date).days
        ),
        unit="D"
    )

    # Product status
    product_status = random.choices(
        ["Active", "Discontinued"],
        weights=[0.90, 0.10],
        k=1
    )[0]

    products.append({
        "product_id": product_id,
        "product_name": product_name,
        "category": category,
        "subcategory": subcategory,
        "brand": brand,
        "unit_cost": unit_cost,
        "unit_price": unit_price,
        "supplier_id": supplier_id,
        "launch_date": launch_date,
        "product_status": product_status
    })


# Convert to DataFrame
products_clean_df = pd.DataFrame(products)

print("Product dataset generated successfully!")
print("Number of rows:", len(products_clean_df))
print("Number of columns:", len(products_clean_df.columns))

products_clean_df.head()

Product dataset generated successfully!
Number of rows: 2000
Number of columns: 10

,product_id,product_name,category,subcategory,brand,unit_cost,unit_price,supplier_id,launch_date,product_status
0,P00001,UrbanThread Men's Clothing 0001,Clothing,Men's Clothing,UrbanThread,31.42,66.25,S017,2023-09-21,Active
1,P00002,PaperPoint Printers 0002,Office Supplies,Printers,PaperPoint,250.85,341.75,S041,2021-03-03,Active
2,P00003,TrailForge Sports Accessories 0003,Sports & Outdoors,Sports Accessories,TrailForge,67.06,102.04,S013,2025-09-11,Active
3,P00004,Oak & Stone Cookware 0004,Home & Kitchen,Cookware,Oak & Stone,484.75,613.72,S027,2023-09-13,Active
4,P00005,NovaTech Laptops 0005,Electronics,Laptops,NovaTech,680.72,787.71,S049,2019-02-06,Discontinued

In [30]:
# ---------------------------------------------------------
# Validate Clean Product Dataset
# ---------------------------------------------------------

print("=== PRODUCT DATA VALIDATION ===")

# 1. Dataset size
print("\nDataset shape:")
print(products_clean_df.shape)

# 2. Missing values
print("\nMissing values:")
print(products_clean_df.isnull().sum())

# 3. Duplicate product IDs
duplicate_product_ids = (
    products_clean_df["product_id"]
    .duplicated()
    .sum()
)

print("\nDuplicate product IDs:")
print(duplicate_product_ids)

# 4. Unique product IDs
print("\nUnique product IDs:")
print(products_clean_df["product_id"].nunique())

# 5. Invalid costs
invalid_costs = (
    products_clean_df["unit_cost"] <= 0
).sum()

print("\nInvalid unit costs:")
print(invalid_costs)

# 6. Invalid prices
invalid_prices = (
    products_clean_df["unit_price"] <= 0
).sum()

print("\nInvalid unit prices:")
print(invalid_prices)

# 7. Products where selling price is below cost
price_below_cost = (
    products_clean_df["unit_price"]
    < products_clean_df["unit_cost"]
).sum()

print("\nProducts with price below cost:")
print(price_below_cost)

# 8. Product status distribution
print("\nProduct status distribution:")
print(
    products_clean_df["product_status"]
    .value_counts()
)

# 9. Category distribution
print("\nCategory distribution:")
print(
    products_clean_df["category"]
    .value_counts()
)

# 10. Launch date range
print("\nLaunch date range:")
print(
    products_clean_df["launch_date"].min(),
    "to",
    products_clean_df["launch_date"].max()
)

=== PRODUCT DATA VALIDATION ===

Dataset shape:
(2000, 10)

Missing values:
product_id        0
product_name      0
category          0
subcategory       0
brand             0
unit_cost         0
unit_price        0
supplier_id       0
launch_date       0
product_status    0
dtype: int64

Duplicate product IDs:
0

Unique product IDs:
2000

Invalid unit costs:
0

Invalid unit prices:
0

Products with price below cost:
0

Product status distribution:
product_status
Active          1806
Discontinued     194
Name: count, dtype: int64

Category distribution:
category
Office Supplies      424
Clothing             406
Home & Kitchen       394
Electronics          389
Sports & Outdoors    387
Name: count, dtype: int64

Launch date range:
2019-01-02 00:00:00 to 2025-12-31 00:00:00

In [31]:
# ---------------------------------------------------------
# Preserve Clean Product Ground Truth
# ---------------------------------------------------------

products_ground_truth_df = products_clean_df.copy(deep=True)

print("Clean product baseline preserved.")
print("Rows:", len(products_ground_truth_df))
print("Columns:", len(products_ground_truth_df.columns))

Clean product baseline preserved.
Rows: 2000
Columns: 10

In [32]:
# ---------------------------------------------------------
# Initialize Dirty Product Dataset and Issue Log
# ---------------------------------------------------------

# Create a copy that we are allowed to modify
products_dirty_df = products_ground_truth_df.copy(deep=True)

# Create an empty issue log
product_issue_log = []

print("Dirty product dataset initialized.")
print("Rows:", len(products_dirty_df))
print("Issue log initialized:", len(product_issue_log))

Dirty product dataset initialized.
Rows: 2000
Issue log initialized: 0

In [33]:
# ---------------------------------------------------------
# Inject Product Issue 1: Missing Subcategory
# ---------------------------------------------------------

missing_subcategory_rate = 0.01

# Calculate number of products to corrupt
num_missing_subcategories = int(
    len(products_dirty_df) * missing_subcategory_rate
)

# Randomly select product rows
missing_subcategory_indices = np.random.choice(
    products_dirty_df.index,
    size=num_missing_subcategories,
    replace=False
)

# Log each issue BEFORE changing the data
for idx in missing_subcategory_indices:

    product_issue_log.append({
        "product_id": products_dirty_df.loc[idx, "product_id"],
        "issue_type": "missing_value",
        "column": "subcategory",
        "original_value": products_dirty_df.loc[idx, "subcategory"],
        "injected_value": None
    })

# Inject missing values
products_dirty_df.loc[
    missing_subcategory_indices,
    "subcategory"
] = None


print("Missing subcategories injected:", num_missing_subcategories)

print(
    "Current missing subcategories:",
    products_dirty_df["subcategory"].isnull().sum()
)

print(
    "Total product issues logged:",
    len(product_issue_log)
)

Missing subcategories injected: 20
Current missing subcategories: 20
Total product issues logged: 20

In [34]:
products_dirty_df.loc[
    missing_subcategory_indices,
    ["product_id", "product_name", "category", "subcategory"]
].head(10)

,product_id,product_name,category,subcategory
1951,P01952,NovaTech Smartphones 1952,Electronics,NaN
1028,P01029,Orbit Technologies Smartphones 1029,Electronics,NaN
173,P00174,PrimeDesk Printers 0174,Office Supplies,NaN
461,P00462,Pulse Digital Smartphones 0462,Electronics,NaN
1771,P01772,PeakMotion Camping 1772,Sports & Outdoors,NaN
1108,P01109,WorkEdge Writing Supplies 1109,Office Supplies,NaN
779,P00780,PaperPoint Desk Accessories 0780,Office Supplies,NaN
366,P00367,DeskPro Paper 0367,Office Supplies,NaN
817,P00818,Stride Men's Clothing 0818,Clothing,NaN
1079,P01080,Oak & Stone Cookware 1080,Home & Kitchen,NaN

In [35]:
# ---------------------------------------------------------
# Inject Product Issue 2: Selling Price Below Unit Cost
# ---------------------------------------------------------

num_price_below_cost = 15

# Avoid products already corrupted
used_indices = set(missing_subcategory_indices)

available_indices = products_dirty_df.index[
    ~products_dirty_df.index.isin(used_indices)
]

# Randomly select products
price_below_cost_indices = np.random.choice(
    available_indices,
    size=num_price_below_cost,
    replace=False
)

# Inject incorrect prices
for idx in price_below_cost_indices:

    original_price = products_dirty_df.loc[idx, "unit_price"]
    unit_cost = products_dirty_df.loc[idx, "unit_cost"]

    # Generate selling price between 60% and 90% of cost
    invalid_price = round(
        unit_cost * random.uniform(0.60, 0.90),
        2
    )

    # Log issue before modifying data
    product_issue_log.append({
        "product_id": products_dirty_df.loc[idx, "product_id"],
        "issue_type": "business_rule_violation",
        "column": "unit_price",
        "original_value": original_price,
        "injected_value": invalid_price
    })

    # Inject incorrect price
    products_dirty_df.loc[idx, "unit_price"] = invalid_price


print("Price-below-cost issues injected:", num_price_below_cost)

print(
    "Products currently priced below cost:",
    (
        products_dirty_df["unit_price"]
        < products_dirty_df["unit_cost"]
    ).sum()
)

print(
    "Total product issues logged:",
    len(product_issue_log)
)

Price-below-cost issues injected: 15
Products currently priced below cost: 15
Total product issues logged: 35

In [36]:
products_dirty_df.loc[
    price_below_cost_indices,
    [
        "product_id",
        "product_name",
        "unit_cost",
        "unit_price"
    ]
].head(10)

     product_id                        product_name  unit_cost  unit_price
1064     P01065   HavenHome Kitchen Appliances 1065     425.84      374.13
804      P00805           Apex Devices Tablets 0805     777.38      477.69
164      P00165             PeakMotion Cycling 0165     353.62      212.51
1754     P01755             Stride Accessories 1755      34.40       30.81
1728     P01729             NorthLane Footwear 1729     122.76      103.59
1888     P01889          NorthLane Accessories 1889     110.11       71.13
1609     P01610            HomeCraft Furniture 1610     477.11      426.52
816      P00817  Orbit Technologies Headphones 0817     926.73      594.95
1162     P01163        Velocity Sports Camping 1163     506.94      359.74
335      P00336        Velocity Sports Cycling 0336      30.11       19.10

In [37]:
# ---------------------------------------------------------
# Inject Product Issue 3: Category/Subcategory Mismatch
# ---------------------------------------------------------

num_category_mismatches = 15

# Avoid products already corrupted
used_indices = (
    set(missing_subcategory_indices)
    | set(price_below_cost_indices)
)

available_indices = products_dirty_df.index[
    ~products_dirty_df.index.isin(used_indices)
]

# Randomly select products
category_mismatch_indices = np.random.choice(
    available_indices,
    size=num_category_mismatches,
    replace=False
)

for idx in category_mismatch_indices:

    original_category = products_dirty_df.loc[idx, "category"]
    original_subcategory = products_dirty_df.loc[idx, "subcategory"]

    # Select a different category
    other_categories = [
        category
        for category in PRODUCT_CATEGORIES.keys()
        if category != original_category
    ]

    wrong_category = random.choice(other_categories)

    # Select a subcategory belonging to that WRONG category
    invalid_subcategory = random.choice(
        PRODUCT_CATEGORIES[wrong_category]
    )

    # Log the issue
    product_issue_log.append({
        "product_id": products_dirty_df.loc[idx, "product_id"],
        "issue_type": "consistency_error",
        "column": "subcategory",
        "original_value": original_subcategory,
        "injected_value": invalid_subcategory
    })

    # Replace the correct subcategory
    products_dirty_df.loc[
        idx,
        "subcategory"
    ] = invalid_subcategory


print(
    "Category/subcategory mismatches injected:",
    num_category_mismatches
)

print(
    "Total product issues logged:",
    len(product_issue_log)
)

Category/subcategory mismatches injected: 15
Total product issues logged: 50

In [38]:
products_dirty_df.loc[
    category_mismatch_indices,
    [
        "product_id",
        "product_name",
        "category",
        "subcategory"
    ]
].head(15)

,product_id,product_name,category,subcategory
12,P00013,HavenHome Storage 0013,Home & Kitchen,Office Furniture
1860,P01861,Velocity Sports Camping 1861,Sports & Outdoors,Men's Clothing
1009,P01010,Apex Devices Tablets 1010,Electronics,Home Decor
1753,P01754,TrailForge Sports Accessories 1754,Sports & Outdoors,Footwear
1090,P01091,EverWear Activewear 1091,Clothing,Fitness Equipment
161,P00162,NorthLane Men's Clothing 0162,Clothing,Monitors
1638,P01639,ModeCraft Women's Clothing 1639,Clothing,Headphones
1810,P01811,DeskPro Desk Accessories 1811,Office Supplies,Tablets
482,P00483,Pulse Digital Monitors 0483,Electronics,Sports Accessories
933,P00934,Apex Devices Headphones 0934,Electronics,Footwear
1328,P01329,ActiveCore Cycling 1329,Sports & Outdoors,Furniture
1508,P01509,Vertex Electronics Monitors 1509,Electronics,Office Furniture
1314,P01315,Stride Activewear 1315,Clothing,Writing Supplies
1411,P01412,PeakMotion Camping 1412,Sports & Outdoors,Tablets
1384,P01385,ActiveCore Outdoor Gear 1385,Sports & Outdoors,Printers

In [39]:
# ---------------------------------------------------------
# Inject Product Issue 4: Negative Unit Cost
# ---------------------------------------------------------

num_negative_costs = 10

# Avoid products already corrupted
used_indices = (
    set(missing_subcategory_indices)
    | set(price_below_cost_indices)
    | set(category_mismatch_indices)
)

available_indices = products_dirty_df.index[
    ~products_dirty_df.index.isin(used_indices)
]

# Randomly select products
negative_cost_indices = np.random.choice(
    available_indices,
    size=num_negative_costs,
    replace=False
)

for idx in negative_cost_indices:

    original_cost = products_dirty_df.loc[idx, "unit_cost"]

    # Convert the existing positive cost to a negative value
    invalid_cost = -abs(original_cost)

    # Log the issue
    product_issue_log.append({
        "product_id": products_dirty_df.loc[idx, "product_id"],
        "issue_type": "invalid_value",
        "column": "unit_cost",
        "original_value": original_cost,
        "injected_value": invalid_cost
    })

    # Inject negative cost
    products_dirty_df.loc[
        idx,
        "unit_cost"
    ] = invalid_cost


print("Negative unit costs injected:", num_negative_costs)

print(
    "Products with unit_cost <= 0:",
    (products_dirty_df["unit_cost"] <= 0).sum()
)

print(
    "Total product issues logged:",
    len(product_issue_log)
)

Negative unit costs injected: 10
Products with unit_cost <= 0: 10
Total product issues logged: 60

In [40]:
products_dirty_df.loc[
    negative_cost_indices,
    [
        "product_id",
        "product_name",
        "unit_cost",
        "unit_price"
    ]
].head(10)

     product_id                     product_name  unit_cost  unit_price
1364     P01365  Vertex Electronics Tablets 1365    -349.26      469.75
1285     P01286  PrimeDesk Writing Supplies 1286    -336.78      605.91
1592     P01593     UrbanThread Accessories 1593     -21.51       43.86
581      P00582          UrbanNest Cookware 0582    -131.24      213.54
101      P00102   Pulse Digital Smartphones 0102   -1188.35     1468.18
1002     P01003         Oak & Stone Storage 1003    -185.15      305.53
1676     P01677         OfficeCore Printers 1677     -53.64       93.84
1839     P01840          TrailForge Camping 1840    -650.26      911.97
1647     P01648        HavenHome Home Decor 1648    -213.15      326.47
390      P00391      Pulse Digital Monitors 0391    -726.50      935.45

In [41]:
# ---------------------------------------------------------
# Inject Product Issue 5: Duplicate Product Records
# ---------------------------------------------------------

num_duplicate_products = 10

# Avoid products that already contain injected issues
used_indices = (
    set(missing_subcategory_indices)
    | set(price_below_cost_indices)
    | set(category_mismatch_indices)
    | set(negative_cost_indices)
)

available_indices = products_dirty_df.index[
    ~products_dirty_df.index.isin(used_indices)
]

# Randomly select products to duplicate
duplicate_product_source_indices = np.random.choice(
    available_indices,
    size=num_duplicate_products,
    replace=False
)

# Copy selected records
duplicate_product_records = products_dirty_df.loc[
    duplicate_product_source_indices
].copy()

# Log each duplicate
for idx in duplicate_product_source_indices:

    product_issue_log.append({
        "product_id": products_dirty_df.loc[idx, "product_id"],
        "issue_type": "duplicate_record",
        "column": "product_id",
        "original_value": products_dirty_df.loc[idx, "product_id"],
        "injected_value": products_dirty_df.loc[idx, "product_id"]
    })

# Append duplicate records
products_dirty_df = pd.concat(
    [products_dirty_df, duplicate_product_records],
    ignore_index=True
)

print("Duplicate products injected:", num_duplicate_products)
print("New product dataset size:", len(products_dirty_df))
print("Total product issues logged:", len(product_issue_log))

Duplicate products injected: 10
New product dataset size: 2010
Total product issues logged: 70

In [42]:
duplicate_product_check = products_dirty_df[
    products_dirty_df.duplicated(
        subset=["product_id"],
        keep=False
    )
].sort_values("product_id")

print(
    "Rows involved in duplicate product IDs:",
    len(duplicate_product_check)
)

print(
    "Product IDs with duplicates:",
    duplicate_product_check["product_id"].nunique()
)

duplicate_product_check.head(10)

Rows involved in duplicate product IDs: 20
Product IDs with duplicates: 10

,product_id,product_name,category,subcategory,brand,unit_cost,unit_price,supplier_id,launch_date,product_status
89,P00090,OfficeCore Printers 0090,Office Supplies,Printers,OfficeCore,313.84,443.86,S020,2025-01-21,Active
2009,P00090,OfficeCore Printers 0090,Office Supplies,Printers,OfficeCore,313.84,443.86,S020,2025-01-21,Active
2004,P00316,DeskPro Desk Accessories 0316,Office Supplies,Desk Accessories,DeskPro,13.36,22.57,S026,2020-12-29,Active
315,P00316,DeskPro Desk Accessories 0316,Office Supplies,Desk Accessories,DeskPro,13.36,22.57,S026,2020-12-29,Active
606,P00607,PureLiving Storage 0607,Home & Kitchen,Storage,PureLiving,142.70,226.55,S028,2021-04-29,Active
2005,P00607,PureLiving Storage 0607,Home & Kitchen,Storage,PureLiving,142.70,226.55,S028,2021-04-29,Active
639,P00640,ModeCraft Women's Clothing 0640,Clothing,Women's Clothing,ModeCraft,172.55,322.88,S043,2021-09-12,Active
2008,P00640,ModeCraft Women's Clothing 0640,Clothing,Women's Clothing,ModeCraft,172.55,322.88,S043,2021-09-12,Active
700,P00701,Pulse Digital Tablets 0701,Electronics,Tablets,Pulse Digital,141.36,194.92,S031,2025-12-29,Active
2002,P00701,Pulse Digital Tablets 0701,Electronics,Tablets,Pulse Digital,141.36,194.92,S031,2025-12-29,Active

In [43]:
# ---------------------------------------------------------
# Convert Product Issue Log to DataFrame
# ---------------------------------------------------------

product_issue_log_df = pd.DataFrame(product_issue_log)

print("Product issue log created successfully!")

print(
    "Total logged issues:",
    len(product_issue_log_df)
)

print("\nIssues by type:")
print(
    product_issue_log_df["issue_type"].value_counts()
)

product_issue_log_df.head(10)

Product issue log created successfully!
Total logged issues: 70

Issues by type:
issue_type
missing_value              20
business_rule_violation    15
consistency_error          15
invalid_value              10
duplicate_record           10
Name: count, dtype: int64

  product_id     issue_type       column    original_value injected_value
0     P01952  missing_value  subcategory       Smartphones           None
1     P01029  missing_value  subcategory       Smartphones           None
2     P00174  missing_value  subcategory          Printers           None
3     P00462  missing_value  subcategory       Smartphones           None
4     P01772  missing_value  subcategory           Camping           None
5     P01109  missing_value  subcategory  Writing Supplies           None
6     P00780  missing_value  subcategory  Desk Accessories           None
7     P00367  missing_value  subcategory             Paper           None
8     P00818  missing_value  subcategory    Men's Clothing           None
9     P01080  missing_value  subcategory          Cookware           None

In [44]:
# ---------------------------------------------------------
# Verify Product Issue Counts
# ---------------------------------------------------------

expected_product_issue_counts = {
    "missing_value": 20,
    "business_rule_violation": 15,
    "consistency_error": 15,
    "invalid_value": 10,
    "duplicate_record": 10
}

actual_product_issue_counts = (
    product_issue_log_df["issue_type"]
    .value_counts()
    .to_dict()
)

for issue_type, expected_count in expected_product_issue_counts.items():

    actual_count = actual_product_issue_counts.get(issue_type, 0)

    status = (
        "PASS"
        if actual_count == expected_count
        else "FAIL"
    )

    print(
        f"{issue_type}: "
        f"Expected={expected_count}, "
        f"Actual={actual_count} "
        f"[{status}]"
    )

missing_value: Expected=20, Actual=20 [PASS]
business_rule_violation: Expected=15, Actual=15 [PASS]
consistency_error: Expected=15, Actual=15 [PASS]
invalid_value: Expected=10, Actual=10 [PASS]
duplicate_record: Expected=10, Actual=10 [PASS]

In [45]:
# ---------------------------------------------------------
# Save Product Dataset and Ground-Truth Issue Log
# ---------------------------------------------------------

# File paths
product_file = INCOMING_DIR / "products.xlsx"

product_issue_log_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "product_issue_ground_truth.csv"
)

# Save dirty product data as Excel
products_dirty_df.to_excel(
    product_file,
    index=False,
    engine="openpyxl"
)

# Save product issue ground truth as CSV
product_issue_log_df.to_csv(
    product_issue_log_file,
    index=False
)

print("Product files saved successfully!")

print("\nProduct source file:")
print(product_file)

print("\nProduct issue ground-truth file:")
print(product_issue_log_file)

Product files saved successfully!

Product source file:
/Users/aryayogirajingale/Documents/DataTrust/data/incoming/products.xlsx

Product issue ground-truth file:
/Users/aryayogirajingale/Documents/DataTrust/data/raw/product_issue_ground_truth.csv

In [46]:
# ---------------------------------------------------------
# Verify Saved Product Files
# ---------------------------------------------------------

print("products.xlsx exists:", product_file.exists())
print("Product issue log exists:", product_issue_log_file.exists())

# Read the Excel file back
saved_products = pd.read_excel(
    product_file,
    engine="openpyxl"
)

print("\nSaved product rows:")
print(len(saved_products))

print("\nSaved product columns:")
print(len(saved_products.columns))

print("\nFile size:")
print(f"{product_file.stat().st_size / 1024:.2f} KB")

products.xlsx exists: True
Product issue log exists: True

Saved product rows:
2010

Saved product columns:
10

File size:
127.99 KB

In [47]:
# ---------------------------------------------------------
# Order Dataset Configuration
# ---------------------------------------------------------

NUM_ORDERS = 120_000

ORDER_CHANNELS = [
    "Website",
    "Mobile App",
    "Physical Store"
]

ORDER_STATUSES = [
    "Completed",
    "Cancelled",
    "Returned"
]

PAYMENT_METHODS = [
    "Credit Card",
    "Debit Card",
    "PayPal",
    "Digital Wallet"
]

print("Order dataset configuration created.")
print("Orders to generate:", f"{NUM_ORDERS:,}")

print("\nSales channels:")
for channel in ORDER_CHANNELS:
    print("-", channel)

print("\nOrder statuses:")
for status in ORDER_STATUSES:
    print("-", status)

print("\nPayment methods:")
for method in PAYMENT_METHODS:
    print("-", method)

Order dataset configuration created.
Orders to generate: 120,000

Sales channels:
- Website
- Mobile App
- Physical Store

Order statuses:
- Completed
- Cancelled
- Returned

Payment methods:
- Credit Card
- Debit Card
- PayPal
- Digital Wallet

In [48]:
# ---------------------------------------------------------
# Order Behavior Configuration
# ---------------------------------------------------------

# Transaction history period
ORDER_START_DATE = pd.Timestamp("2023-01-01")
ORDER_END_DATE = pd.Timestamp("2025-12-31")

# Sales channel probabilities
CHANNEL_WEIGHTS = [
    0.45,   # Website
    0.35,   # Mobile App
    0.20    # Physical Store
]

# Order status probabilities
STATUS_WEIGHTS = [
    0.92,   # Completed
    0.05,   # Cancelled
    0.03    # Returned
]

# Payment method probabilities
PAYMENT_WEIGHTS = [
    0.40,   # Credit Card
    0.25,   # Debit Card
    0.20,   # PayPal
    0.15    # Digital Wallet
]

print("Order behavior configuration created.")

print(
    "Order period:",
    ORDER_START_DATE.date(),
    "to",
    ORDER_END_DATE.date()
)

print("\nChannel weights:")
for channel, weight in zip(ORDER_CHANNELS, CHANNEL_WEIGHTS):
    print(f"{channel}: {weight:.0%}")

print("\nStatus weights:")
for status, weight in zip(ORDER_STATUSES, STATUS_WEIGHTS):
    print(f"{status}: {weight:.0%}")

print("\nPayment weights:")
for method, weight in zip(PAYMENT_METHODS, PAYMENT_WEIGHTS):
    print(f"{method}: {weight:.0%}")

Order behavior configuration created.
Order period: 2023-01-01 to 2025-12-31

Channel weights:
Website: 45%
Mobile App: 35%
Physical Store: 20%

Status weights:
Completed: 92%
Cancelled: 5%
Returned: 3%

Payment weights:
Credit Card: 40%
Debit Card: 25%
PayPal: 20%
Digital Wallet: 15%

In [49]:
# ---------------------------------------------------------
# Generate Clean Order Dataset
# ---------------------------------------------------------

orders = []

# Customer lookup for faster access
customer_lookup = (
    customers_ground_truth_df
    .set_index("customer_id")
)

customer_ids = customers_ground_truth_df["customer_id"].tolist()

for i in range(1, NUM_ORDERS + 1):

    # Unique order ID
    order_id = f"O{i:07d}"

    # Select customer
    customer_id = random.choice(customer_ids)

    customer = customer_lookup.loc[customer_id]

    # Customer signup date
    signup_date = pd.Timestamp(customer["signup_date"])

    # Order cannot occur before:
    # 1. NovaRetail transaction-history start date
    # 2. Customer signup date
    earliest_order_date = max(
        ORDER_START_DATE,
        signup_date
    )

    # Generate valid order date
    available_days = (
        ORDER_END_DATE - earliest_order_date
    ).days

    order_date = (
        earliest_order_date
        + pd.to_timedelta(
            random.randint(0, available_days),
            unit="D"
        )
    )

    # Sales channel
    sales_channel = random.choices(
        ORDER_CHANNELS,
        weights=CHANNEL_WEIGHTS,
        k=1
    )[0]

    # Order status
    order_status = random.choices(
        ORDER_STATUSES,
        weights=STATUS_WEIGHTS,
        k=1
    )[0]

    # Payment method
    payment_method = random.choices(
        PAYMENT_METHODS,
        weights=PAYMENT_WEIGHTS,
        k=1
    )[0]

    # Use customer's location as shipping location
    shipping_city = customer["city"]
    shipping_state = customer["state"]
    shipping_region = customer["region"]

    orders.append({
        "order_id": order_id,
        "customer_id": customer_id,
        "order_date": order_date,
        "sales_channel": sales_channel,
        "order_status": order_status,
        "payment_method": payment_method,
        "shipping_city": shipping_city,
        "shipping_state": shipping_state,
        "shipping_region": shipping_region
    })


# Convert to DataFrame
orders_clean_df = pd.DataFrame(orders)

print("Order dataset generated successfully!")
print("Number of rows:", len(orders_clean_df))
print("Number of columns:", len(orders_clean_df.columns))

orders_clean_df.head()

Order dataset generated successfully!
Number of rows: 120000
Number of columns: 9

,order_id,customer_id,order_date,sales_channel,order_status,payment_method,shipping_city,shipping_state,shipping_region
0,O0000001,C024260,2025-12-06,Mobile App,Completed,Credit Card,Austin,TX,South
1,O0000002,C016387,2024-06-16,Mobile App,Returned,PayPal,Detroit,MI,Midwest
2,O0000003,C034376,2025-08-20,Website,Completed,Credit Card,Newark,NJ,Northeast
3,O0000004,C035249,2025-03-10,Website,Completed,Credit Card,Los Angeles,CA,West
4,O0000005,C034541,2025-09-23,Website,Completed,Credit Card,New York,NY,Northeast

In [50]:
# ---------------------------------------------------------
# Validate Clean Order Dataset
# ---------------------------------------------------------

print("=== ORDER DATA VALIDATION ===")

# 1. Dataset size
print("\nDataset shape:")
print(orders_clean_df.shape)

# 2. Missing values
print("\nMissing values:")
print(orders_clean_df.isnull().sum())

# 3. Duplicate order IDs
duplicate_order_ids = (
    orders_clean_df["order_id"]
    .duplicated()
    .sum()
)

print("\nDuplicate order IDs:")
print(duplicate_order_ids)

# 4. Unique order IDs
print("\nUnique order IDs:")
print(orders_clean_df["order_id"].nunique())

# 5. Order date range
print("\nOrder date range:")
print(
    orders_clean_df["order_date"].min(),
    "to",
    orders_clean_df["order_date"].max()
)

# 6. Channel distribution
print("\nSales channel distribution:")
print(
    orders_clean_df["sales_channel"]
    .value_counts()
)

# 7. Order status distribution
print("\nOrder status distribution:")
print(
    orders_clean_df["order_status"]
    .value_counts()
)

# 8. Payment method distribution
print("\nPayment method distribution:")
print(
    orders_clean_df["payment_method"]
    .value_counts()
)

=== ORDER DATA VALIDATION ===

Dataset shape:
(120000, 9)

Missing values:
order_id           0
customer_id        0
order_date         0
sales_channel      0
order_status       0
payment_method     0
shipping_city      0
shipping_state     0
shipping_region    0
dtype: int64

Duplicate order IDs:
0

Unique order IDs:
120000

Order date range:
2023-01-01 00:00:00 to 2025-12-31 00:00:00

Sales channel distribution:
sales_channel
Website           54330
Mobile App        41883
Physical Store    23787
Name: count, dtype: int64

Order status distribution:
order_status
Completed    110201
Cancelled      6150
Returned       3649
Name: count, dtype: int64

Payment method distribution:
payment_method
Credit Card       47884
Debit Card        29996
PayPal            24126
Digital Wallet    17994
Name: count, dtype: int64

In [51]:
# ---------------------------------------------------------
# Validate Customer ↔ Order Relationships
# ---------------------------------------------------------

# Add customer signup date to orders temporarily for validation
order_customer_check = orders_clean_df.merge(
    customers_ground_truth_df[
        ["customer_id", "signup_date"]
    ],
    on="customer_id",
    how="left"
)

# 1. Orders referencing customers that do not exist
orphan_customer_orders = (
    order_customer_check["signup_date"]
    .isnull()
    .sum()
)

# 2. Orders occurring before customer signup
orders_before_signup = (
    order_customer_check["order_date"]
    < order_customer_check["signup_date"]
).sum()

print("=== CUSTOMER ↔ ORDER INTEGRITY CHECK ===")

print(
    "\nOrders with nonexistent customer IDs:",
    orphan_customer_orders
)

print(
    "Orders placed before customer signup:",
    orders_before_signup
)

print(
    "Orders checked:",
    len(order_customer_check)
)

=== CUSTOMER ↔ ORDER INTEGRITY CHECK ===

Orders with nonexistent customer IDs: 0
Orders placed before customer signup: 0
Orders checked: 120000

In [52]:
# ---------------------------------------------------------
# Preserve Clean Order Ground Truth
# ---------------------------------------------------------

orders_ground_truth_df = orders_clean_df.copy(deep=True)

print("Clean order baseline preserved.")
print("Rows:", len(orders_ground_truth_df))
print("Columns:", len(orders_ground_truth_df.columns))

Clean order baseline preserved.
Rows: 120000
Columns: 9

In [53]:
# ---------------------------------------------------------
# Initialize Dirty Order Dataset and Issue Log
# ---------------------------------------------------------

# Create a copy that we are allowed to modify
orders_dirty_df = orders_ground_truth_df.copy(deep=True)

# Empty list to track every intentionally injected issue
order_issue_log = []

print("Dirty order dataset initialized.")
print("Rows:", len(orders_dirty_df))
print("Columns:", len(orders_dirty_df.columns))
print("Issue log initialized:", len(order_issue_log))

Dirty order dataset initialized.
Rows: 120000
Columns: 9
Issue log initialized: 0

In [54]:
# ---------------------------------------------------------
# Inject Order Issue 1: Missing Customer ID
# ---------------------------------------------------------

missing_customer_rate = 0.0025

# Calculate number of orders to corrupt
num_missing_customers = int(
    len(orders_dirty_df) * missing_customer_rate
)

# Randomly select order rows
missing_customer_indices = np.random.choice(
    orders_dirty_df.index,
    size=num_missing_customers,
    replace=False
)

# Log each issue BEFORE modifying the data
for idx in missing_customer_indices:

    order_issue_log.append({
        "order_id": orders_dirty_df.loc[idx, "order_id"],
        "issue_type": "missing_value",
        "column": "customer_id",
        "original_value": orders_dirty_df.loc[idx, "customer_id"],
        "injected_value": None
    })

# Inject missing customer IDs
orders_dirty_df.loc[
    missing_customer_indices,
    "customer_id"
] = None


print(
    "Missing customer IDs injected:",
    num_missing_customers
)

print(
    "Current missing customer IDs:",
    orders_dirty_df["customer_id"].isnull().sum()
)

print(
    "Total order issues logged:",
    len(order_issue_log)
)

Missing customer IDs injected: 300
Current missing customer IDs: 300
Total order issues logged: 300

In [55]:
orders_dirty_df.loc[
    missing_customer_indices,
    [
        "order_id",
        "customer_id",
        "order_date",
        "sales_channel",
        "order_status"
    ]
].head(10)

        order_id customer_id order_date   sales_channel order_status
114036  O0114037         NaN 2024-04-17  Physical Store    Completed
73151   O0073152         NaN 2025-11-14         Website    Completed
17917   O0017918         NaN 2025-05-16      Mobile App    Completed
96624   O0096625         NaN 2025-08-24      Mobile App    Completed
3478    O0003479         NaN 2025-08-04         Website    Completed
94633   O0094634         NaN 2025-09-24      Mobile App    Cancelled
4080    O0004081         NaN 2024-01-19         Website    Completed
7385    O0007386         NaN 2025-02-28  Physical Store    Completed
61851   O0061852         NaN 2023-10-19      Mobile App    Completed
1350    O0001351         NaN 2024-01-30         Website    Completed

In [56]:
# ---------------------------------------------------------
# Inject Order Issue 2: Nonexistent Customer IDs
# ---------------------------------------------------------

num_orphan_customer_ids = 200

# Avoid rows already corrupted
used_indices = set(missing_customer_indices)

available_indices = orders_dirty_df.index[
    ~orders_dirty_df.index.isin(used_indices)
]

# Randomly select orders
orphan_customer_indices = np.random.choice(
    available_indices,
    size=num_orphan_customer_ids,
    replace=False
)

# Create customer IDs outside our valid C000001-C050000 range
for counter, idx in enumerate(orphan_customer_indices, start=1):

    original_customer_id = orders_dirty_df.loc[
        idx,
        "customer_id"
    ]

    invalid_customer_id = f"C{900000 + counter:06d}"

    # Log issue before modification
    order_issue_log.append({
        "order_id": orders_dirty_df.loc[idx, "order_id"],
        "issue_type": "referential_integrity_error",
        "column": "customer_id",
        "original_value": original_customer_id,
        "injected_value": invalid_customer_id
    })

    # Inject nonexistent customer ID
    orders_dirty_df.loc[
        idx,
        "customer_id"
    ] = invalid_customer_id


print(
    "Nonexistent customer IDs injected:",
    num_orphan_customer_ids
)

print(
    "Total order issues logged:",
    len(order_issue_log)
)

Nonexistent customer IDs injected: 200
Total order issues logged: 500

In [57]:
# Valid customer IDs from the clean customer master
valid_customer_ids = set(
    customers_ground_truth_df["customer_id"]
)

# Find non-null customer IDs in orders that don't exist in customers
orphan_mask = (
    orders_dirty_df["customer_id"].notna()
    &
    ~orders_dirty_df["customer_id"].isin(valid_customer_ids)
)

print(
    "Orders with nonexistent customer IDs:",
    orphan_mask.sum()
)

orders_dirty_df.loc[
    orphan_mask,
    [
        "order_id",
        "customer_id",
        "order_date",
        "sales_channel"
    ]
].head(10)

Orders with nonexistent customer IDs: 200

      order_id customer_id order_date   sales_channel
93    O0000094     C900187 2024-06-13      Mobile App
135   O0000136     C900077 2025-12-14         Website
217   O0000218     C900148 2024-12-27      Mobile App
348   O0000349     C900025 2025-04-10      Mobile App
584   O0000585     C900195 2025-09-05      Mobile App
1978  O0001979     C900041 2025-07-19      Mobile App
2437  O0002438     C900132 2024-07-11         Website
2828  O0002829     C900032 2025-04-08  Physical Store
2915  O0002916     C900182 2024-05-08  Physical Store
3181  O0003182     C900167 2024-08-29      Mobile App

In [58]:
# ---------------------------------------------------------
# Inject Order Issue 3: Order Before Customer Signup
# ---------------------------------------------------------

num_orders_before_signup = 150

# Avoid rows already corrupted
used_indices = (
    set(missing_customer_indices)
    | set(orphan_customer_indices)
)

# We specifically need customers whose signup date is
# after 2021-01-01 so that an earlier valid date can be created.
eligible_indices = []

for idx in orders_dirty_df.index:

    if idx in used_indices:
        continue

    customer_id = orders_dirty_df.loc[idx, "customer_id"]

    signup_date = pd.Timestamp(
        customer_lookup.loc[customer_id, "signup_date"]
    )

    if signup_date > pd.Timestamp("2021-01-01"):
        eligible_indices.append(idx)


# Randomly select eligible orders
order_before_signup_indices = np.random.choice(
    eligible_indices,
    size=num_orders_before_signup,
    replace=False
)


# Inject invalid order dates
for idx in order_before_signup_indices:

    customer_id = orders_dirty_df.loc[idx, "customer_id"]

    signup_date = pd.Timestamp(
        customer_lookup.loc[customer_id, "signup_date"]
    )

    original_order_date = orders_dirty_df.loc[
        idx,
        "order_date"
    ]

    # Place order 1-90 days BEFORE customer signup
    days_before = random.randint(1, 90)

    invalid_order_date = (
        signup_date
        - pd.to_timedelta(days_before, unit="D")
    )

    # Log issue
    order_issue_log.append({
        "order_id": orders_dirty_df.loc[idx, "order_id"],
        "issue_type": "temporal_consistency_error",
        "column": "order_date",
        "original_value": original_order_date,
        "injected_value": invalid_order_date
    })

    # Inject incorrect date
    orders_dirty_df.loc[
        idx,
        "order_date"
    ] = invalid_order_date


print(
    "Orders-before-signup issues injected:",
    num_orders_before_signup
)

print(
    "Total order issues logged:",
    len(order_issue_log)
)

Orders-before-signup issues injected: 150
Total order issues logged: 650

In [59]:
# Check the intentionally corrupted orders

temporal_check = (
    orders_dirty_df.loc[
        order_before_signup_indices,
        ["order_id", "customer_id", "order_date"]
    ]
    .merge(
        customers_ground_truth_df[
            ["customer_id", "signup_date"]
        ],
        on="customer_id",
        how="left"
    )
)

temporal_check["invalid_date"] = (
    temporal_check["order_date"]
    < temporal_check["signup_date"]
)

print(
    "Orders before customer signup:",
    temporal_check["invalid_date"].sum()
)

temporal_check.head(10)

Orders before customer signup: 150

   order_id customer_id order_date signup_date  invalid_date
0  O0104385     C024205 2020-12-23  2021-01-20          True
1  O0025697     C038223 2023-03-10  2023-04-06          True
2  O0119905     C046378 2022-05-31  2022-07-20          True
3  O0117808     C029419 2022-12-28  2023-03-20          True
4  O0093164     C041449 2024-12-13  2025-02-06          True
5  O0023360     C036206 2024-11-15  2024-12-14          True
6  O0005067     C007201 2021-02-22  2021-04-24          True
7  O0075173     C020856 2024-01-08  2024-02-10          True
8  O0118732     C036190 2022-03-22  2022-04-20          True
9  O0051516     C023421 2023-06-12  2023-07-03          True

In [60]:
# ---------------------------------------------------------
# Inject Order Issue 4: Shipping Region Mismatch
# ---------------------------------------------------------

num_shipping_region_mismatches = 150

# Avoid rows already corrupted
used_indices = (
    set(missing_customer_indices)
    | set(orphan_customer_indices)
    | set(order_before_signup_indices)
)

available_indices = orders_dirty_df.index[
    ~orders_dirty_df.index.isin(used_indices)
]

# Randomly select orders
shipping_region_mismatch_indices = np.random.choice(
    available_indices,
    size=num_shipping_region_mismatches,
    replace=False
)

# Inject incorrect shipping regions
for idx in shipping_region_mismatch_indices:

    original_region = orders_dirty_df.loc[
        idx,
        "shipping_region"
    ]

    # Select a valid region different from the correct one
    incorrect_regions = [
        region
        for region in REGIONS
        if region != original_region
    ]

    incorrect_region = random.choice(
        incorrect_regions
    )

    # Log issue before changing data
    order_issue_log.append({
        "order_id": orders_dirty_df.loc[idx, "order_id"],
        "issue_type": "consistency_error",
        "column": "shipping_region",
        "original_value": original_region,
        "injected_value": incorrect_region
    })

    # Inject incorrect region
    orders_dirty_df.loc[
        idx,
        "shipping_region"
    ] = incorrect_region


print(
    "Shipping region mismatches injected:",
    num_shipping_region_mismatches
)

print(
    "Total order issues logged:",
    len(order_issue_log)
)

Shipping region mismatches injected: 150
Total order issues logged: 800

In [61]:
orders_dirty_df.loc[
    shipping_region_mismatch_indices,
    [
        "order_id",
        "shipping_city",
        "shipping_state",
        "shipping_region"
    ]
].head(10)

        order_id shipping_city shipping_state shipping_region
65082   O0065083   Minneapolis             MN           South
35010   O0035011  Indianapolis             IN           South
57646   O0057647        Boston             MA            West
89364   O0089365        Newark             NJ            West
88891   O0088892     Charlotte             NC       Northeast
101818  O0101819   Los Angeles             CA         Midwest
78545   O0078546   Los Angeles             CA           South
105763  O0105764  Philadelphia             PA           South
15917   O0015918       Chicago             IL           South
648     O0000649      Columbus             OH           South

In [62]:
# ---------------------------------------------------------
# Inject Order Issue 5: Invalid Sales Channel
# ---------------------------------------------------------

num_invalid_sales_channels = 100

INVALID_SALES_CHANNELS = [
    "Social Media",
    "Phone Order",
    "Marketplace",
    "Unknown"
]

# Avoid rows already corrupted
used_indices = (
    set(missing_customer_indices)
    | set(orphan_customer_indices)
    | set(order_before_signup_indices)
    | set(shipping_region_mismatch_indices)
)

available_indices = orders_dirty_df.index[
    ~orders_dirty_df.index.isin(used_indices)
]

# Randomly select orders
invalid_sales_channel_indices = np.random.choice(
    available_indices,
    size=num_invalid_sales_channels,
    replace=False
)

# Inject invalid channel values
for idx in invalid_sales_channel_indices:

    original_channel = orders_dirty_df.loc[
        idx,
        "sales_channel"
    ]

    invalid_channel = random.choice(
        INVALID_SALES_CHANNELS
    )

    # Log issue before modification
    order_issue_log.append({
        "order_id": orders_dirty_df.loc[idx, "order_id"],
        "issue_type": "invalid_category",
        "column": "sales_channel",
        "original_value": original_channel,
        "injected_value": invalid_channel
    })

    # Inject invalid value
    orders_dirty_df.loc[
        idx,
        "sales_channel"
    ] = invalid_channel


print(
    "Invalid sales channels injected:",
    num_invalid_sales_channels
)

print(
    "Total order issues logged:",
    len(order_issue_log)
)

Invalid sales channels injected: 100
Total order issues logged: 900

In [63]:
orders_dirty_df.loc[
    invalid_sales_channel_indices,
    [
        "order_id",
        "sales_channel",
        "order_date"
    ]
].head(10)

        order_id sales_channel order_date
94827   O0094828   Marketplace 2025-08-09
72215   O0072216   Phone Order 2025-07-24
95927   O0095928  Social Media 2024-02-06
31860   O0031861   Phone Order 2024-07-28
18306   O0018307       Unknown 2025-08-31
83084   O0083085   Phone Order 2025-03-21
735     O0000736   Marketplace 2025-11-04
61419   O0061420  Social Media 2025-10-17
107199  O0107200       Unknown 2025-09-14
112824  O0112825   Phone Order 2025-10-17

In [64]:
# ---------------------------------------------------------
# Inject Order Issue 6: Duplicate Order Records
# ---------------------------------------------------------

num_duplicate_orders = 100

# Avoid orders already corrupted
used_indices = (
    set(missing_customer_indices)
    | set(orphan_customer_indices)
    | set(order_before_signup_indices)
    | set(shipping_region_mismatch_indices)
    | set(invalid_sales_channel_indices)
)

available_indices = orders_dirty_df.index[
    ~orders_dirty_df.index.isin(used_indices)
]

# Randomly select orders to duplicate
duplicate_order_source_indices = np.random.choice(
    available_indices,
    size=num_duplicate_orders,
    replace=False
)

# Copy the selected records
duplicate_order_records = orders_dirty_df.loc[
    duplicate_order_source_indices
].copy()

# Log each duplicate
for idx in duplicate_order_source_indices:

    order_issue_log.append({
        "order_id": orders_dirty_df.loc[idx, "order_id"],
        "issue_type": "duplicate_record",
        "column": "order_id",
        "original_value": orders_dirty_df.loc[idx, "order_id"],
        "injected_value": orders_dirty_df.loc[idx, "order_id"]
    })

# Append duplicate rows
orders_dirty_df = pd.concat(
    [orders_dirty_df, duplicate_order_records],
    ignore_index=True
)

print(
    "Duplicate orders injected:",
    num_duplicate_orders
)

print(
    "New order dataset size:",
    len(orders_dirty_df)
)

print(
    "Total order issues logged:",
    len(order_issue_log)
)

Duplicate orders injected: 100
New order dataset size: 120100
Total order issues logged: 1000

In [65]:
duplicate_order_check = orders_dirty_df[
    orders_dirty_df.duplicated(
        subset=["order_id"],
        keep=False
    )
].sort_values("order_id")

print(
    "Rows involved in duplicate order IDs:",
    len(duplicate_order_check)
)

print(
    "Order IDs with duplicates:",
    duplicate_order_check["order_id"].nunique()
)

duplicate_order_check.head(10)

Rows involved in duplicate order IDs: 200
Order IDs with duplicates: 100

,order_id,customer_id,order_date,sales_channel,order_status,payment_method,shipping_city,shipping_state,shipping_region
201,O0000202,C006433,2025-04-23,Mobile App,Completed,Credit Card,Houston,TX,South
120061,O0000202,C006433,2025-04-23,Mobile App,Completed,Credit Card,Houston,TX,South
2506,O0002507,C014359,2024-01-09,Website,Completed,Debit Card,Dallas,TX,South
120037,O0002507,C014359,2024-01-09,Website,Completed,Debit Card,Dallas,TX,South
120015,O0002580,C049927,2025-12-19,Website,Completed,Digital Wallet,Philadelphia,PA,Northeast
2579,O0002580,C049927,2025-12-19,Website,Completed,Digital Wallet,Philadelphia,PA,Northeast
2653,O0002654,C023614,2024-12-17,Mobile App,Completed,Debit Card,Charlotte,NC,South
120017,O0002654,C023614,2024-12-17,Mobile App,Completed,Debit Card,Charlotte,NC,South
120067,O0003610,C004708,2025-09-05,Physical Store,Completed,PayPal,San Francisco,CA,West
3609,O0003610,C004708,2025-09-05,Physical Store,Completed,PayPal,San Francisco,CA,West

In [66]:
# ---------------------------------------------------------
# Convert Order Issue Log to DataFrame
# ---------------------------------------------------------

order_issue_log_df = pd.DataFrame(order_issue_log)

print("Order issue log created successfully!")

print(
    "Total logged issues:",
    len(order_issue_log_df)
)

print("\nIssues by type:")

print(
    order_issue_log_df["issue_type"]
    .value_counts()
)

order_issue_log_df.head(10)

Order issue log created successfully!
Total logged issues: 1000

Issues by type:
issue_type
missing_value                  300
referential_integrity_error    200
temporal_consistency_error     150
consistency_error              150
invalid_category               100
duplicate_record               100
Name: count, dtype: int64

   order_id     issue_type       column original_value injected_value
0  O0114037  missing_value  customer_id        C003950           None
1  O0073152  missing_value  customer_id        C027854           None
2  O0017918  missing_value  customer_id        C033244           None
3  O0096625  missing_value  customer_id        C008145           None
4  O0003479  missing_value  customer_id        C048721           None
5  O0094634  missing_value  customer_id        C016917           None
6  O0004081  missing_value  customer_id        C027827           None
7  O0007386  missing_value  customer_id        C028866           None
8  O0061852  missing_value  customer_id        C029069           None
9  O0001351  missing_value  customer_id        C015438           None

In [67]:
# ---------------------------------------------------------
# Verify Order Issue Counts
# ---------------------------------------------------------

expected_order_issue_counts = {
    "missing_value": 300,
    "referential_integrity_error": 200,
    "temporal_consistency_error": 150,
    "consistency_error": 150,
    "invalid_category": 100,
    "duplicate_record": 100
}

actual_order_issue_counts = (
    order_issue_log_df["issue_type"]
    .value_counts()
    .to_dict()
)

for issue_type, expected_count in expected_order_issue_counts.items():

    actual_count = actual_order_issue_counts.get(
        issue_type,
        0
    )

    status = (
        "PASS"
        if actual_count == expected_count
        else "FAIL"
    )

    print(
        f"{issue_type}: "
        f"Expected={expected_count}, "
        f"Actual={actual_count} "
        f"[{status}]"
    )

missing_value: Expected=300, Actual=300 [PASS]
referential_integrity_error: Expected=200, Actual=200 [PASS]
temporal_consistency_error: Expected=150, Actual=150 [PASS]
consistency_error: Expected=150, Actual=150 [PASS]
invalid_category: Expected=100, Actual=100 [PASS]
duplicate_record: Expected=100, Actual=100 [PASS]

In [68]:
# ---------------------------------------------------------
# Save Order Dataset and Ground-Truth Issue Log
# ---------------------------------------------------------

# File paths
order_file = INCOMING_DIR / "orders.csv"

order_issue_log_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "order_issue_ground_truth.csv"
)

# Save dirty order data
orders_dirty_df.to_csv(
    order_file,
    index=False
)

# Save order issue ground truth
order_issue_log_df.to_csv(
    order_issue_log_file,
    index=False
)

print("Order files saved successfully!")

print("\nOrder source file:")
print(order_file)

print("\nOrder issue ground-truth file:")
print(order_issue_log_file)

Order files saved successfully!

Order source file:
/Users/aryayogirajingale/Documents/DataTrust/data/incoming/orders.csv

Order issue ground-truth file:
/Users/aryayogirajingale/Documents/DataTrust/data/raw/order_issue_ground_truth.csv

In [69]:
# ---------------------------------------------------------
# Verify Saved Order Files
# ---------------------------------------------------------

print("orders.csv exists:", order_file.exists())
print("Order issue log exists:", order_issue_log_file.exists())

# Read orders.csv back from disk
saved_orders = pd.read_csv(order_file)

print("\nSaved order rows:")
print(len(saved_orders))

print("\nSaved order columns:")
print(len(saved_orders.columns))

print("\nFile size:")
print(f"{order_file.stat().st_size / 1024 / 1024:.2f} MB")

orders.csv exists: True
Order issue log exists: True

Saved order rows:
120100

Saved order columns:
9

File size:
9.04 MB

In [70]:
# ---------------------------------------------------------
# Order Item Configuration
# ---------------------------------------------------------

MIN_ITEMS_PER_ORDER = 1
MAX_ITEMS_PER_ORDER = 6

ITEM_COUNT_OPTIONS = [1, 2, 3, 4, 5, 6]

ITEM_COUNT_WEIGHTS = [
    0.25,   # 1 item
    0.30,   # 2 items
    0.22,   # 3 items
    0.13,   # 4 items
    0.07,   # 5 items
    0.03    # 6 items
]

QUANTITY_OPTIONS = [1, 2, 3, 4, 5]

QUANTITY_WEIGHTS = [
    0.68,   # quantity 1
    0.20,   # quantity 2
    0.07,   # quantity 3
    0.03,   # quantity 4
    0.02    # quantity 5
]

DISCOUNT_OPTIONS = [
    0.00,
    0.05,
    0.10,
    0.15,
    0.20,
    0.25,
    0.30
]

DISCOUNT_WEIGHTS = [
    0.40,
    0.15,
    0.15,
    0.10,
    0.10,
    0.06,
    0.04
]

print("Order-item configuration created!")

Order-item configuration created!

In [71]:
# ---------------------------------------------------------
# Create Product Lookup for Order-Item Generation
# ---------------------------------------------------------

product_lookup = (
    products_ground_truth_df
    .set_index("product_id")
)

product_ids = (
    products_ground_truth_df["product_id"]
    .tolist()
)

print("Product lookup created!")

print(
    "Products available:",
    len(product_ids)
)

print(
    "Unique product IDs:",
    len(set(product_ids))
)

Product lookup created!
Products available: 2000
Unique product IDs: 2000

In [72]:
# ---------------------------------------------------------
# Test Product Lookup
# ---------------------------------------------------------

test_product_id = product_ids[0]

print("Product ID:", test_product_id)

print(
    "Product Name:",
    product_lookup.loc[
        test_product_id,
        "product_name"
    ]
)

print(
    "Unit Price:",
    product_lookup.loc[
        test_product_id,
        "unit_price"
    ]
)

print(
    "Unit Cost:",
    product_lookup.loc[
        test_product_id,
        "unit_cost"
    ]
)

Product ID: P00001
Product Name: UrbanThread Men's Clothing 0001
Unit Price: 66.25
Unit Cost: 31.42

In [73]:
# ---------------------------------------------------------
# Generate Clean Order-Item Dataset
# ---------------------------------------------------------

order_items = []

order_item_counter = 1

# Generate line items for every clean order
for order_id in orders_ground_truth_df["order_id"]:

    # Decide how many different products are in this order
    num_items = random.choices(
        ITEM_COUNT_OPTIONS,
        weights=ITEM_COUNT_WEIGHTS,
        k=1
    )[0]

    # Select different products for this order
    selected_products = random.sample(
        product_ids,
        k=num_items
    )

    for product_id in selected_products:

        product = product_lookup.loc[product_id]

        # Quantity purchased
        quantity = random.choices(
            QUANTITY_OPTIONS,
            weights=QUANTITY_WEIGHTS,
            k=1
        )[0]

        # Discount applied
        discount_pct = random.choices(
            DISCOUNT_OPTIONS,
            weights=DISCOUNT_WEIGHTS,
            k=1
        )[0]

        # Product price and cost
        unit_price = float(product["unit_price"])
        unit_cost = float(product["unit_cost"])

        order_items.append({
            "order_item_id": f"OI{order_item_counter:08d}",
            "order_id": order_id,
            "product_id": product_id,
            "quantity": quantity,
            "unit_price": unit_price,
            "discount_pct": discount_pct,
            "unit_cost": unit_cost
        })

        order_item_counter += 1


order_items_clean_df = pd.DataFrame(order_items)

print("Clean order-items dataset created!")

print(
    "Total order-item rows:",
    len(order_items_clean_df)
)

print(
    "Total columns:",
    len(order_items_clean_df.columns)
)

Clean order-items dataset created!
Total order-item rows: 307159
Total columns: 7

In [74]:
order_items_clean_df.head(10)

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,unit_cost
0,OI00000001,O0000001,P00290,1,193.41,0.00,110.96
1,OI00000002,O0000001,P00300,1,459.79,0.10,308.94
2,OI00000003,O0000001,P01080,1,182.53,0.15,140.69
3,OI00000004,O0000001,P01421,1,333.26,0.00,267.14
4,OI00000005,O0000001,P00683,1,135.92,0.00,89.48
5,OI00000006,O0000002,P01888,1,1020.14,0.20,699.68
6,OI00000007,O0000002,P00776,1,1094.89,0.00,695.61
7,OI00000008,O0000002,P01373,2,35.08,0.00,24.06
8,OI00000009,O0000003,P01171,1,85.76,0.00,58.19
9,OI00000010,O0000003,P00241,2,791.08,0.30,526.99

In [75]:
# ---------------------------------------------------------
# Validate Clean Order-Item Dataset
# ---------------------------------------------------------

print("Dataset shape:")
print(order_items_clean_df.shape)

print("\nMissing values:")
print(order_items_clean_df.isnull().sum())

print("\nDuplicate order_item_id:")
print(
    order_items_clean_df["order_item_id"]
    .duplicated()
    .sum()
)

print("\nUnique order_item IDs:")
print(
    order_items_clean_df["order_item_id"]
    .nunique()
)

print("\nInvalid quantities:")
print(
    (order_items_clean_df["quantity"] <= 0).sum()
)

print("\nInvalid unit prices:")
print(
    (order_items_clean_df["unit_price"] <= 0).sum()
)

print("\nInvalid unit costs:")
print(
    (order_items_clean_df["unit_cost"] <= 0).sum()
)

print("\nInvalid discounts:")
print(
    (
        (order_items_clean_df["discount_pct"] < 0)
        |
        (order_items_clean_df["discount_pct"] > 0.30)
    ).sum()
)

print("\nPrice below cost:")
print(
    (
        order_items_clean_df["unit_price"]
        <
        order_items_clean_df["unit_cost"]
    ).sum()
)

Dataset shape:
(307159, 7)

Missing values:
order_item_id    0
order_id         0
product_id       0
quantity         0
unit_price       0
discount_pct     0
unit_cost        0
dtype: int64

Duplicate order_item_id:
0

Unique order_item IDs:
307159

Invalid quantities:
0

Invalid unit prices:
0

Invalid unit costs:
0

Invalid discounts:
0

Price below cost:
0

In [76]:
# ---------------------------------------------------------
# Validate Foreign-Key Relationships
# ---------------------------------------------------------

valid_order_ids = set(
    orders_ground_truth_df["order_id"]
)

valid_product_ids = set(
    products_ground_truth_df["product_id"]
)

invalid_order_references = (
    ~order_items_clean_df["order_id"]
    .isin(valid_order_ids)
).sum()

invalid_product_references = (
    ~order_items_clean_df["product_id"]
    .isin(valid_product_ids)
).sum()

print(
    "Invalid order references:",
    invalid_order_references
)

print(
    "Invalid product references:",
    invalid_product_references
)

Invalid order references: 0
Invalid product references: 0

In [77]:
# ---------------------------------------------------------
# Preserve Clean Order-Item Ground Truth
# ---------------------------------------------------------

order_items_ground_truth_df = (
    order_items_clean_df.copy(deep=True)
)

print("Order-item ground truth preserved!")

print(
    "Ground-truth rows:",
    len(order_items_ground_truth_df)
)

print(
    "Ground-truth columns:",
    len(order_items_ground_truth_df.columns)
)

Order-item ground truth preserved!
Ground-truth rows: 307159
Ground-truth columns: 7

In [78]:
# ---------------------------------------------------------
# Initialize Dirty Order-Item Dataset
# ---------------------------------------------------------

order_items_dirty_df = (
    order_items_ground_truth_df.copy(deep=True)
)

order_item_issue_log = []

print("Dirty order-item dataset initialized!")

print(
    "Current rows:",
    len(order_items_dirty_df)
)

print(
    "Current columns:",
    len(order_items_dirty_df.columns)
)

print(
    "Current injected issues:",
    len(order_item_issue_log)
)

Dirty order-item dataset initialized!
Current rows: 307159
Current columns: 7
Current injected issues: 0

In [79]:
# ---------------------------------------------------------
# Inject Order-Item Issue 1: Invalid Quantity
# ---------------------------------------------------------

num_invalid_quantities = 300

# Randomly select rows
invalid_quantity_indices = np.random.choice(
    order_items_dirty_df.index,
    size=num_invalid_quantities,
    replace=False
)

INVALID_QUANTITIES = [0, -1, -2]

# Inject invalid quantities
for idx in invalid_quantity_indices:

    original_quantity = order_items_dirty_df.loc[
        idx,
        "quantity"
    ]

    invalid_quantity = random.choice(
        INVALID_QUANTITIES
    )

    # Log issue before modification
    order_item_issue_log.append({
        "order_item_id": order_items_dirty_df.loc[
            idx,
            "order_item_id"
        ],
        "issue_type": "business_rule_violation",
        "column": "quantity",
        "original_value": original_quantity,
        "injected_value": invalid_quantity
    })

    # Inject invalid value
    order_items_dirty_df.loc[
        idx,
        "quantity"
    ] = invalid_quantity


print(
    "Invalid quantities injected:",
    num_invalid_quantities
)

print(
    "Current invalid quantities:",
    (
        order_items_dirty_df["quantity"] <= 0
    ).sum()
)

print(
    "Total order-item issues logged:",
    len(order_item_issue_log)
)

Invalid quantities injected: 300
Current invalid quantities: 300
Total order-item issues logged: 300

In [80]:
order_items_dirty_df.loc[
    invalid_quantity_indices,
    [
        "order_item_id",
        "order_id",
        "product_id",
        "quantity",
        "unit_price"
    ]
].head(10)

       order_item_id  order_id product_id  quantity  unit_price
102019    OI00102020  O0039843     P00986        -2      407.68
235188    OI00235189  O0091836     P00758        -1      295.55
275052    OI00275053  O0107434     P00961         0      186.92
34046     OI00034047  O0013238     P01272        -2       65.77
2613      OI00002614  O0001024     P00655        -1      293.21
186530    OI00186531  O0072854     P00846         0      254.57
170680    OI00170681  O0066653     P00309        -1      703.02
46624     OI00046625  O0018113     P00835        -2      309.52
183601    OI00183602  O0071706     P01633        -2      730.48
283107    OI00283108  O0110565     P01000        -1       45.19

In [81]:
# ---------------------------------------------------------
# Inject Order-Item Issue 2: Nonexistent Product IDs
# ---------------------------------------------------------

num_orphan_product_ids = 200

# Avoid rows already corrupted
used_indices = set(invalid_quantity_indices)

available_indices = order_items_dirty_df.index[
    ~order_items_dirty_df.index.isin(used_indices)
]

# Randomly select rows
orphan_product_indices = np.random.choice(
    available_indices,
    size=num_orphan_product_ids,
    replace=False
)

# Inject nonexistent product IDs
for counter, idx in enumerate(
    orphan_product_indices,
    start=1
):

    original_product_id = order_items_dirty_df.loc[
        idx,
        "product_id"
    ]

    # Valid products only go from P00001 to P02000
    invalid_product_id = f"P{90000 + counter:05d}"

    # Log issue before modification
    order_item_issue_log.append({
        "order_item_id": order_items_dirty_df.loc[
            idx,
            "order_item_id"
        ],
        "issue_type": "referential_integrity_error",
        "column": "product_id",
        "original_value": original_product_id,
        "injected_value": invalid_product_id
    })

    # Inject invalid product ID
    order_items_dirty_df.loc[
        idx,
        "product_id"
    ] = invalid_product_id


print(
    "Nonexistent product IDs injected:",
    num_orphan_product_ids
)

print(
    "Total order-item issues logged:",
    len(order_item_issue_log)
)

Nonexistent product IDs injected: 200
Total order-item issues logged: 500

In [82]:
# ---------------------------------------------------------
# Verify Nonexistent Product IDs
# ---------------------------------------------------------

valid_product_ids = set(
    products_ground_truth_df["product_id"]
)

orphan_product_mask = (
    order_items_dirty_df["product_id"].notna()
    &
    ~order_items_dirty_df["product_id"].isin(
        valid_product_ids
    )
)

print(
    "Order items with nonexistent product IDs:",
    orphan_product_mask.sum()
)

order_items_dirty_df.loc[
    orphan_product_mask,
    [
        "order_item_id",
        "order_id",
        "product_id",
        "quantity",
        "unit_price"
    ]
].head(10)

Order items with nonexistent product IDs: 200

      order_item_id  order_id product_id  quantity  unit_price
1555     OI00001556  O0000597     P90074         4      213.54
3925     OI00003926  O0001538     P90036         2      163.69
6274     OI00006275  O0002429     P90115         1      789.71
8139     OI00008140  O0003178     P90192         1      230.23
9260     OI00009261  O0003615     P90130         1      289.69
12686    OI00012687  O0004935     P90145         1      866.31
14277    OI00014278  O0005546     P90165         1      847.07
15537    OI00015538  O0006066     P90179         1      290.73
24833    OI00024834  O0009661     P90100         1      254.92
29464    OI00029465  O0011459     P90032         1       90.96

In [83]:
# ---------------------------------------------------------
# Inject Order-Item Issue 3: Invalid Discount
# ---------------------------------------------------------

num_invalid_discounts = 150

INVALID_DISCOUNTS = [
    0.50,
    0.75,
    1.10
]

# Avoid rows already corrupted
used_indices = (
    set(invalid_quantity_indices)
    | set(orphan_product_indices)
)

available_indices = order_items_dirty_df.index[
    ~order_items_dirty_df.index.isin(used_indices)
]

# Randomly select rows
invalid_discount_indices = np.random.choice(
    available_indices,
    size=num_invalid_discounts,
    replace=False
)

# Inject invalid discounts
for idx in invalid_discount_indices:

    original_discount = order_items_dirty_df.loc[
        idx,
        "discount_pct"
    ]

    invalid_discount = random.choice(
        INVALID_DISCOUNTS
    )

    # Log issue before modification
    order_item_issue_log.append({
        "order_item_id": order_items_dirty_df.loc[
            idx,
            "order_item_id"
        ],
        "issue_type": "business_rule_violation",
        "column": "discount_pct",
        "original_value": original_discount,
        "injected_value": invalid_discount
    })

    # Inject invalid discount
    order_items_dirty_df.loc[
        idx,
        "discount_pct"
    ] = invalid_discount


print(
    "Invalid discounts injected:",
    num_invalid_discounts
)

print(
    "Total order-item issues logged:",
    len(order_item_issue_log)
)

Invalid discounts injected: 150
Total order-item issues logged: 650

In [84]:
# ---------------------------------------------------------
# Verify Invalid Discounts
# ---------------------------------------------------------

invalid_discount_mask = (
    (order_items_dirty_df["discount_pct"] < 0)
    |
    (order_items_dirty_df["discount_pct"] > 0.30)
)

print(
    "Order items with invalid discounts:",
    invalid_discount_mask.sum()
)

order_items_dirty_df.loc[
    invalid_discount_mask,
    [
        "order_item_id",
        "order_id",
        "product_id",
        "quantity",
        "unit_price",
        "discount_pct"
    ]
].head(10)

Order items with invalid discounts: 150

      order_item_id  order_id product_id  quantity  unit_price  discount_pct
1475     OI00001476  O0000567     P00408         1       18.30          0.75
5887     OI00005888  O0002280     P01192         4      901.16          1.10
14491    OI00014492  O0005636     P01207         3      475.05          0.50
17579    OI00017580  O0006842     P00065         1      419.01          0.50
21001    OI00021002  O0008141     P00486         1      460.99          0.75
22424    OI00022425  O0008716     P01335         1      297.46          0.50
23642    OI00023643  O0009186     P00054         1      302.69          1.10
24205    OI00024206  O0009415     P01297         1      258.85          0.50
24415    OI00024416  O0009502     P01965         3      365.16          0.50
26494    OI00026495  O0010298     P00529         2      148.95          0.50

In [85]:
# ---------------------------------------------------------
# Inject Order-Item Issue 4: Unit Price Inconsistency
# ---------------------------------------------------------

num_price_inconsistencies = 150

# Avoid rows already corrupted
used_indices = (
    set(invalid_quantity_indices)
    | set(orphan_product_indices)
    | set(invalid_discount_indices)
)

available_indices = order_items_dirty_df.index[
    ~order_items_dirty_df.index.isin(used_indices)
]

# Randomly select rows
price_inconsistency_indices = np.random.choice(
    available_indices,
    size=num_price_inconsistencies,
    replace=False
)

for idx in price_inconsistency_indices:

    original_price = float(
        order_items_dirty_df.loc[idx, "unit_price"]
    )

    # Artificially increase/decrease price by 20%-60%
    price_multiplier = random.choice([
        0.40,
        0.60,
        1.30,
        1.50,
        1.60
    ])

    invalid_price = round(
        original_price * price_multiplier,
        2
    )

    # Log issue before modification
    order_item_issue_log.append({
        "order_item_id": order_items_dirty_df.loc[
            idx,
            "order_item_id"
        ],
        "issue_type": "price_inconsistency",
        "column": "unit_price",
        "original_value": original_price,
        "injected_value": invalid_price
    })

    # Inject incorrect transaction price
    order_items_dirty_df.loc[
        idx,
        "unit_price"
    ] = invalid_price


print(
    "Price inconsistencies injected:",
    num_price_inconsistencies
)

print(
    "Total order-item issues logged:",
    len(order_item_issue_log)
)

Price inconsistencies injected: 150
Total order-item issues logged: 800

In [86]:
# ---------------------------------------------------------
# Verify Price Inconsistencies
# ---------------------------------------------------------

price_check = (
    order_items_dirty_df.loc[
        price_inconsistency_indices,
        [
            "order_item_id",
            "order_id",
            "product_id",
            "unit_price"
        ]
    ]
    .merge(
        products_ground_truth_df[
            ["product_id", "unit_price"]
        ],
        on="product_id",
        how="left",
        suffixes=(
            "_transaction",
            "_product_master"
        )
    )
)

price_check["price_difference"] = (
    price_check["unit_price_transaction"]
    - price_check["unit_price_product_master"]
).round(2)

price_check["price_mismatch"] = (
    price_check["unit_price_transaction"]
    != price_check["unit_price_product_master"]
)

print(
    "Confirmed price inconsistencies:",
    price_check["price_mismatch"].sum()
)

price_check.head(10)

Confirmed price inconsistencies: 150

,order_item_id,order_id,product_id,unit_price_transaction,unit_price_product_master,price_difference,price_mismatch
0,OI00148439,O0057936,P00965,673.56,518.12,155.44,True
1,OI00168198,O0065677,P01358,441.12,339.32,101.80,True
2,OI00219778,O0085838,P01250,138.13,230.22,-92.09,True
3,OI00211982,O0082785,P00759,1824.91,1403.78,421.13,True
4,OI00165443,O0064610,P01549,570.96,356.85,214.11,True
5,OI00273362,O0106764,P00206,125.44,78.40,47.04,True
6,OI00258583,O0100970,P01229,114.79,286.97,-172.18,True
7,OI00040633,O0015794,P01096,12.83,8.02,4.81,True
8,OI00196307,O0076688,P01223,323.35,248.73,74.62,True
9,OI00033923,O0013187,P00116,307.24,768.10,-460.86,True

In [87]:
# ---------------------------------------------------------
# Inject Order-Item Issue 5: Duplicate Records
# ---------------------------------------------------------

num_duplicate_order_items = 150

# Avoid rows already corrupted
used_indices = (
    set(invalid_quantity_indices)
    | set(orphan_product_indices)
    | set(invalid_discount_indices)
    | set(price_inconsistency_indices)
)

available_indices = order_items_dirty_df.index[
    ~order_items_dirty_df.index.isin(used_indices)
]

# Randomly select clean records to duplicate
duplicate_order_item_source_indices = np.random.choice(
    available_indices,
    size=num_duplicate_order_items,
    replace=False
)

# Copy the selected rows
duplicate_order_item_records = order_items_dirty_df.loc[
    duplicate_order_item_source_indices
].copy()

# Log the duplicate issues
for idx in duplicate_order_item_source_indices:

    order_item_id = order_items_dirty_df.loc[
        idx,
        "order_item_id"
    ]

    order_item_issue_log.append({
        "order_item_id": order_item_id,
        "issue_type": "duplicate_record",
        "column": "order_item_id",
        "original_value": order_item_id,
        "injected_value": order_item_id
    })

# Append duplicates to the dirty dataset
order_items_dirty_df = pd.concat(
    [
        order_items_dirty_df,
        duplicate_order_item_records
    ],
    ignore_index=True
)

print(
    "Duplicate order items injected:",
    num_duplicate_order_items
)

print(
    "New order-item dataset size:",
    len(order_items_dirty_df)
)

print(
    "Total order-item issues logged:",
    len(order_item_issue_log)
)

Duplicate order items injected: 150
New order-item dataset size: 307309
Total order-item issues logged: 950

In [88]:
# ---------------------------------------------------------
# Verify Duplicate Order Items
# ---------------------------------------------------------

duplicate_order_item_check = order_items_dirty_df[
    order_items_dirty_df.duplicated(
        subset=["order_item_id"],
        keep=False
    )
].sort_values("order_item_id")

print(
    "Rows involved in duplicate order-item IDs:",
    len(duplicate_order_item_check)
)

print(
    "Order-item IDs with duplicates:",
    duplicate_order_item_check[
        "order_item_id"
    ].nunique()
)

duplicate_order_item_check.head(10)

Rows involved in duplicate order-item IDs: 300
Order-item IDs with duplicates: 150

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,unit_cost
1860,OI00001861,O0000710,P01749,1,1188.32,0.30,782.81
307233,OI00001861,O0000710,P01749,1,1188.32,0.30,782.81
307209,OI00002689,O0001058,P01458,2,650.96,0.00,401.68
2688,OI00002689,O0001058,P01458,2,650.96,0.00,401.68
4970,OI00004971,O0001944,P00122,2,383.34,0.25,274.59
307299,OI00004971,O0001944,P00122,2,383.34,0.25,274.59
307173,OI00005379,O0002093,P00459,1,521.60,0.00,356.07
5378,OI00005379,O0002093,P00459,1,521.60,0.00,356.07
6246,OI00006247,O0002418,P00580,3,151.02,0.15,102.06
307256,OI00006247,O0002418,P00580,3,151.02,0.15,102.06

In [89]:
# ---------------------------------------------------------
# Convert Order-Item Issue Log to DataFrame
# ---------------------------------------------------------

order_item_issue_log_df = pd.DataFrame(
    order_item_issue_log
)

print("Order-item issue log created successfully!")

print(
    "Total logged issues:",
    len(order_item_issue_log_df)
)

print("\nIssues by type:")

print(
    order_item_issue_log_df["issue_type"]
    .value_counts()
)

order_item_issue_log_df.head(10)

Order-item issue log created successfully!
Total logged issues: 950

Issues by type:
issue_type
business_rule_violation        450
referential_integrity_error    200
price_inconsistency            150
duplicate_record               150
Name: count, dtype: int64

,order_item_id,issue_type,column,original_value,injected_value
0,OI00102020,business_rule_violation,quantity,1,-2
1,OI00235189,business_rule_violation,quantity,1,-1
2,OI00275053,business_rule_violation,quantity,1,0
3,OI00034047,business_rule_violation,quantity,1,-2
4,OI00002614,business_rule_violation,quantity,1,-1
5,OI00186531,business_rule_violation,quantity,3,0
6,OI00170681,business_rule_violation,quantity,1,-1
7,OI00046625,business_rule_violation,quantity,1,-2
8,OI00183602,business_rule_violation,quantity,1,-2
9,OI00283108,business_rule_violation,quantity,1,-1

In [90]:
# ---------------------------------------------------------
# Detailed Order-Item Issue Verification
# ---------------------------------------------------------

issue_summary = (
    order_item_issue_log_df
    .groupby(
        ["issue_type", "column"]
    )
    .size()
    .reset_index(name="count")
)

print(issue_summary)

                    issue_type         column  count
0      business_rule_violation   discount_pct    150
1      business_rule_violation       quantity    300
2             duplicate_record  order_item_id    150
3          price_inconsistency     unit_price    150
4  referential_integrity_error     product_id    200

In [91]:
# ---------------------------------------------------------
# Automatically Verify Order-Item Issue Counts
# ---------------------------------------------------------

expected_order_item_issues = {
    ("business_rule_violation", "quantity"): 300,
    ("referential_integrity_error", "product_id"): 200,
    ("business_rule_violation", "discount_pct"): 150,
    ("price_inconsistency", "unit_price"): 150,
    ("duplicate_record", "order_item_id"): 150
}

actual_order_item_issues = (
    order_item_issue_log_df
    .groupby(["issue_type", "column"])
    .size()
    .to_dict()
)

for issue, expected_count in expected_order_item_issues.items():

    actual_count = actual_order_item_issues.get(
        issue,
        0
    )

    status = (
        "PASS"
        if actual_count == expected_count
        else "FAIL"
    )

    print(
        f"{issue}: "
        f"Expected={expected_count}, "
        f"Actual={actual_count} "
        f"[{status}]"
    )

('business_rule_violation', 'quantity'): Expected=300, Actual=300 [PASS]
('referential_integrity_error', 'product_id'): Expected=200, Actual=200 [PASS]
('business_rule_violation', 'discount_pct'): Expected=150, Actual=150 [PASS]
('price_inconsistency', 'unit_price'): Expected=150, Actual=150 [PASS]
('duplicate_record', 'order_item_id'): Expected=150, Actual=150 [PASS]

In [92]:
# ---------------------------------------------------------
# Save Order-Item Dataset and Ground-Truth Issue Log
# ---------------------------------------------------------

# File paths
order_items_file = (
    INCOMING_DIR / "order_items.csv"
)

order_item_issue_log_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "order_item_issue_ground_truth.csv"
)

# Save dirty order-item data
order_items_dirty_df.to_csv(
    order_items_file,
    index=False
)

# Save issue ground truth
order_item_issue_log_df.to_csv(
    order_item_issue_log_file,
    index=False
)

print("Order-item files saved successfully!")

print("\nOrder-item source file:")
print(order_items_file)

print("\nOrder-item issue ground-truth file:")
print(order_item_issue_log_file)

Order-item files saved successfully!

Order-item source file:
/Users/aryayogirajingale/Documents/DataTrust/data/incoming/order_items.csv

Order-item issue ground-truth file:
/Users/aryayogirajingale/Documents/DataTrust/data/raw/order_item_issue_ground_truth.csv

In [93]:
# ---------------------------------------------------------
# Verify Saved Order-Item Files
# ---------------------------------------------------------

print(
    "order_items.csv exists:",
    order_items_file.exists()
)

print(
    "Order-item issue log exists:",
    order_item_issue_log_file.exists()
)

# Read the file back from disk
saved_order_items = pd.read_csv(
    order_items_file
)

print(
    "\nSaved order-item rows:",
    len(saved_order_items)
)

print(
    "\nSaved order-item columns:",
    len(saved_order_items.columns)
)

print(
    "\nGround-truth issues:",
    len(order_item_issue_log_df)
)

print(
    "\nFile size:",
    f"{order_items_file.stat().st_size / 1024 / 1024:.2f} MB"
)

order_items.csv exists: True
Order-item issue log exists: True

Saved order-item rows: 307309

Saved order-item columns: 7

Ground-truth issues: 950

File size: 13.72 MB

In [94]:
# ---------------------------------------------------------
# Payment Dataset Configuration
# ---------------------------------------------------------

PAYMENT_STATUSES = [
    "Successful",
    "Failed",
    "Refunded"
]

print("Payment configuration created!")

print(
    "Payment statuses:",
    PAYMENT_STATUSES
)

print(
    "Clean orders available:",
    len(orders_ground_truth_df)
)

Payment configuration created!
Payment statuses: ['Successful', 'Failed', 'Refunded']
Clean orders available: 120000

In [95]:
# ---------------------------------------------------------
# Calculate Clean Order Financial Totals
# ---------------------------------------------------------

# Work from the CLEAN ground-truth order items
order_financials = order_items_ground_truth_df.copy()

# Gross sales before discount
order_financials["gross_sales"] = (
    order_financials["quantity"]
    * order_financials["unit_price"]
)

# Discount amount
order_financials["discount_amount"] = (
    order_financials["gross_sales"]
    * order_financials["discount_pct"]
)

# Net sales after discount
order_financials["net_sales"] = (
    order_financials["gross_sales"]
    - order_financials["discount_amount"]
)

# Total product cost
order_financials["total_cost"] = (
    order_financials["quantity"]
    * order_financials["unit_cost"]
)

# Gross profit
order_financials["gross_profit"] = (
    order_financials["net_sales"]
    - order_financials["total_cost"]
)

print("Line-item financial metrics calculated!")

order_financials.head(10)

Line-item financial metrics calculated!

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,unit_cost,gross_sales,discount_amount,net_sales,total_cost,gross_profit
0,OI00000001,O0000001,P00290,1,193.41,0.00,110.96,193.41,0.0000,193.4100,110.96,82.4500
1,OI00000002,O0000001,P00300,1,459.79,0.10,308.94,459.79,45.9790,413.8110,308.94,104.8710
2,OI00000003,O0000001,P01080,1,182.53,0.15,140.69,182.53,27.3795,155.1505,140.69,14.4605
3,OI00000004,O0000001,P01421,1,333.26,0.00,267.14,333.26,0.0000,333.2600,267.14,66.1200
4,OI00000005,O0000001,P00683,1,135.92,0.00,89.48,135.92,0.0000,135.9200,89.48,46.4400
5,OI00000006,O0000002,P01888,1,1020.14,0.20,699.68,1020.14,204.0280,816.1120,699.68,116.4320
6,OI00000007,O0000002,P00776,1,1094.89,0.00,695.61,1094.89,0.0000,1094.8900,695.61,399.2800
7,OI00000008,O0000002,P01373,2,35.08,0.00,24.06,70.16,0.0000,70.1600,48.12,22.0400
8,OI00000009,O0000003,P01171,1,85.76,0.00,58.19,85.76,0.0000,85.7600,58.19,27.5700
9,OI00000010,O0000003,P00241,2,791.08,0.30,526.99,1582.16,474.6480,1107.5120,1053.98,53.5320

In [96]:
# ---------------------------------------------------------
# Aggregate Financial Metrics by Order
# ---------------------------------------------------------

order_totals_df = (
    order_financials
    .groupby("order_id", as_index=False)
    .agg({
        "gross_sales": "sum",
        "discount_amount": "sum",
        "net_sales": "sum",
        "total_cost": "sum",
        "gross_profit": "sum"
    })
)

# Round financial values to cents
financial_columns = [
    "gross_sales",
    "discount_amount",
    "net_sales",
    "total_cost",
    "gross_profit"
]

order_totals_df[financial_columns] = (
    order_totals_df[financial_columns]
    .round(2)
)

print("Order-level financial totals created!")

print(
    "Orders with financial totals:",
    len(order_totals_df)
)

print(
    "Unique order IDs:",
    order_totals_df["order_id"].nunique()
)

order_totals_df.head(10)

Order-level financial totals created!
Orders with financial totals: 120000
Unique order IDs: 120000

   order_id  gross_sales  discount_amount  net_sales  total_cost  gross_profit
0  O0000001      1304.91            73.36    1231.55      917.21        314.34
1  O0000002      2185.19           204.03    1981.16     1443.41        537.75
2  O0000003      1667.92           474.65    1193.27     1112.17         81.10
3  O0000004      2142.83           260.38    1882.45     1417.83        464.62
4  O0000005      3444.33           344.43    3099.90     2511.21        588.69
5  O0000006       175.33             0.00     175.33      131.56         43.77
6  O0000007      3596.07            70.14    3525.93     2716.47        809.46
7  O0000008      3510.88           108.18    3402.70     2303.56       1099.14
8  O0000009      2251.31           145.22    2106.09     1617.98        488.11
9  O0000010       812.26             0.45     811.81      564.87        246.94

In [97]:
# ---------------------------------------------------------
# Prepare Clean Payment Source Data
# ---------------------------------------------------------

payment_source_df = (
    orders_ground_truth_df[
        [
            "order_id",
            "order_date",
            "order_status",
            "payment_method"
        ]
    ]
    .merge(
        order_totals_df[
            [
                "order_id",
                "net_sales"
            ]
        ],
        on="order_id",
        how="left"
    )
)

print("Payment source data prepared!")

print(
    "Rows:",
    len(payment_source_df)
)

print(
    "Missing order totals:",
    payment_source_df["net_sales"]
    .isnull()
    .sum()
)

payment_source_df.head()

Payment source data prepared!
Rows: 120000
Missing order totals: 0

   order_id order_date order_status payment_method  net_sales
0  O0000001 2025-12-06    Completed    Credit Card    1231.55
1  O0000002 2024-06-16     Returned         PayPal    1981.16
2  O0000003 2025-08-20    Completed    Credit Card    1193.27
3  O0000004 2025-03-10    Completed    Credit Card    1882.45
4  O0000005 2025-09-23    Completed    Credit Card    3099.90

In [98]:
# ---------------------------------------------------------
# Generate Clean Payments Dataset
# ---------------------------------------------------------

payments = []

for i, row in payment_source_df.iterrows():

    payment_id = f"PAY{i + 1:07d}"

    # Map order status to payment status
    if row["order_status"] == "Completed":
        payment_status = "Successful"

    elif row["order_status"] == "Cancelled":
        payment_status = "Failed"

    else:
        payment_status = "Refunded"

    # Keep payment date aligned with the order date
    payment_date = row["order_date"]

    # Expected transaction amount
    payment_amount = round(
        float(row["net_sales"]),
        2
    )

    payments.append({
        "payment_id": payment_id,
        "order_id": row["order_id"],
        "payment_date": payment_date,
        "payment_method": row["payment_method"],
        "payment_status": payment_status,
        "payment_amount": payment_amount
    })


payments_clean_df = pd.DataFrame(payments)

print("Clean payments dataset created!")

print(
    "Total payment rows:",
    len(payments_clean_df)
)

print(
    "Total columns:",
    len(payments_clean_df.columns)
)

payments_clean_df.head(10)

Clean payments dataset created!
Total payment rows: 120000
Total columns: 6

,payment_id,order_id,payment_date,payment_method,payment_status,payment_amount
0,PAY0000001,O0000001,2025-12-06,Credit Card,Successful,1231.55
1,PAY0000002,O0000002,2024-06-16,PayPal,Refunded,1981.16
2,PAY0000003,O0000003,2025-08-20,Credit Card,Successful,1193.27
3,PAY0000004,O0000004,2025-03-10,Credit Card,Successful,1882.45
4,PAY0000005,O0000005,2025-09-23,Credit Card,Successful,3099.90
5,PAY0000006,O0000006,2024-10-31,Debit Card,Failed,175.33
6,PAY0000007,O0000007,2025-07-25,Debit Card,Successful,3525.93
7,PAY0000008,O0000008,2025-10-19,PayPal,Successful,3402.70
8,PAY0000009,O0000009,2025-12-31,Credit Card,Successful,2106.09
9,PAY0000010,O0000010,2025-09-15,PayPal,Successful,811.81

In [99]:
# ---------------------------------------------------------
# Validate Clean Payments Dataset
# ---------------------------------------------------------

print("Dataset shape:")
print(payments_clean_df.shape)

print("\nMissing values:")
print(
    payments_clean_df.isnull().sum()
)

print("\nDuplicate payment IDs:")
print(
    payments_clean_df["payment_id"]
    .duplicated()
    .sum()
)

print("\nUnique payment IDs:")
print(
    payments_clean_df["payment_id"]
    .nunique()
)

print("\nDuplicate order IDs in payments:")
print(
    payments_clean_df["order_id"]
    .duplicated()
    .sum()
)

print("\nInvalid payment methods:")
print(
    (
        ~payments_clean_df["payment_method"]
        .isin(PAYMENT_METHODS)
    ).sum()
)

print("\nInvalid payment statuses:")
print(
    (
        ~payments_clean_df["payment_status"]
        .isin(PAYMENT_STATUSES)
    ).sum()
)

print("\nNon-positive payment amounts:")
print(
    (
        payments_clean_df["payment_amount"] <= 0
    ).sum()
)

Dataset shape:
(120000, 6)

Missing values:
payment_id        0
order_id          0
payment_date      0
payment_method    0
payment_status    0
payment_amount    0
dtype: int64

Duplicate payment IDs:
0

Unique payment IDs:
120000

Duplicate order IDs in payments:
0

Invalid payment methods:
0

Invalid payment statuses:
0

Non-positive payment amounts:
0

In [100]:
# ---------------------------------------------------------
# Validate Payment → Order Relationship
# ---------------------------------------------------------

valid_order_ids = set(
    orders_ground_truth_df["order_id"]
)

invalid_payment_order_refs = (
    ~payments_clean_df["order_id"]
    .isin(valid_order_ids)
).sum()

print(
    "Payments referencing nonexistent orders:",
    invalid_payment_order_refs
)

Payments referencing nonexistent orders: 0

In [101]:
# ---------------------------------------------------------
# Validate Payment Amount Reconciliation
# ---------------------------------------------------------

payment_reconciliation = (
    payments_clean_df[
        [
            "payment_id",
            "order_id",
            "payment_amount"
        ]
    ]
    .merge(
        order_totals_df[
            [
                "order_id",
                "net_sales"
            ]
        ],
        on="order_id",
        how="left"
    )
)

payment_reconciliation["difference"] = (
    payment_reconciliation["payment_amount"]
    - payment_reconciliation["net_sales"]
).round(2)

payment_reconciliation["is_mismatch"] = (
    payment_reconciliation["difference"].abs() > 0.01
)

print(
    "Payment amount mismatches:",
    payment_reconciliation["is_mismatch"].sum()
)

print(
    "Maximum reconciliation difference:",
    payment_reconciliation["difference"].abs().max()
)

payment_reconciliation.head(10)

Payment amount mismatches: 0
Maximum reconciliation difference: 0.0

   payment_id  order_id  payment_amount  net_sales  difference  is_mismatch
0  PAY0000001  O0000001         1231.55    1231.55         0.0        False
1  PAY0000002  O0000002         1981.16    1981.16         0.0        False
2  PAY0000003  O0000003         1193.27    1193.27         0.0        False
3  PAY0000004  O0000004         1882.45    1882.45         0.0        False
4  PAY0000005  O0000005         3099.90    3099.90         0.0        False
5  PAY0000006  O0000006          175.33     175.33         0.0        False
6  PAY0000007  O0000007         3525.93    3525.93         0.0        False
7  PAY0000008  O0000008         3402.70    3402.70         0.0        False
8  PAY0000009  O0000009         2106.09    2106.09         0.0        False
9  PAY0000010  O0000010          811.81     811.81         0.0        False

In [102]:
# ---------------------------------------------------------
# Preserve Clean Payments Ground Truth
# ---------------------------------------------------------

payments_ground_truth_df = (
    payments_clean_df.copy(deep=True)
)

print("Payment ground truth preserved!")

print(
    "Ground-truth rows:",
    len(payments_ground_truth_df)
)

print(
    "Ground-truth columns:",
    len(payments_ground_truth_df.columns)
)

Payment ground truth preserved!
Ground-truth rows: 120000
Ground-truth columns: 6

In [103]:
# ---------------------------------------------------------
# Initialize Dirty Payments Dataset
# ---------------------------------------------------------

payments_dirty_df = (
    payments_ground_truth_df.copy(deep=True)
)

payment_issue_log = []

print("Dirty payments dataset initialized!")

print(
    "Current rows:",
    len(payments_dirty_df)
)

print(
    "Current columns:",
    len(payments_dirty_df.columns)
)

print(
    "Current injected issues:",
    len(payment_issue_log)
)

Dirty payments dataset initialized!
Current rows: 120000
Current columns: 6
Current injected issues: 0

In [104]:
# ---------------------------------------------------------
# Inject Payment Issue 1: Payment Amount Mismatch
# ---------------------------------------------------------

num_payment_amount_mismatches = 200

# Randomly select payment rows
payment_amount_mismatch_indices = np.random.choice(
    payments_dirty_df.index,
    size=num_payment_amount_mismatches,
    replace=False
)

for idx in payment_amount_mismatch_indices:

    original_amount = float(
        payments_dirty_df.loc[idx, "payment_amount"]
    )

    # Change the payment by 10%-30%
    multiplier = random.choice([
        0.70,
        0.80,
        0.90,
        1.10,
        1.20,
        1.30
    ])

    incorrect_amount = round(
        original_amount * multiplier,
        2
    )

    # Log issue before modification
    payment_issue_log.append({
        "payment_id": payments_dirty_df.loc[
            idx,
            "payment_id"
        ],
        "issue_type": "reconciliation_error",
        "column": "payment_amount",
        "original_value": original_amount,
        "injected_value": incorrect_amount
    })

    # Inject incorrect payment amount
    payments_dirty_df.loc[
        idx,
        "payment_amount"
    ] = incorrect_amount


print(
    "Payment amount mismatches injected:",
    num_payment_amount_mismatches
)

print(
    "Total payment issues logged:",
    len(payment_issue_log)
)

Payment amount mismatches injected: 200
Total payment issues logged: 200

In [105]:
# ---------------------------------------------------------
# Verify Payment Amount Mismatches
# ---------------------------------------------------------

payment_amount_check = (
    payments_dirty_df.loc[
        payment_amount_mismatch_indices,
        [
            "payment_id",
            "order_id",
            "payment_amount"
        ]
    ]
    .merge(
        order_totals_df[
            [
                "order_id",
                "net_sales"
            ]
        ],
        on="order_id",
        how="left"
    )
)

payment_amount_check["difference"] = (
    payment_amount_check["payment_amount"]
    - payment_amount_check["net_sales"]
).round(2)

payment_amount_check["is_mismatch"] = (
    payment_amount_check["difference"].abs() > 0.01
)

print(
    "Confirmed payment amount mismatches:",
    payment_amount_check["is_mismatch"].sum()
)

payment_amount_check.head(10)

Confirmed payment amount mismatches: 200

   payment_id  order_id  payment_amount  net_sales  difference  is_mismatch
0  PAY0020520  O0020520         2263.47    3233.53     -970.06         True
1  PAY0071732  O0071732         2976.69    2706.08      270.61         True
2  PAY0063657  O0063657          363.58     519.40     -155.82         True
3  PAY0030722  O0030722         2134.10    1940.09      194.01         True
4  PAY0027089  O0027089         1107.96    1582.80     -474.84         True
5  PAY0011913  O0011913         3735.97    2873.82      862.15         True
6  PAY0047462  O0047462         3200.41    2909.46      290.95         True
7  PAY0118536  O0118536          926.37    1157.96     -231.59         True
8  PAY0115314  O0115314          690.70     986.71     -296.01         True
9  PAY0062202  O0062202         1239.01    1032.51      206.50         True

In [106]:
# ---------------------------------------------------------
# Inject Payment Issue 2: Nonexistent Order IDs
# ---------------------------------------------------------

num_orphan_payment_orders = 150

# Avoid rows already corrupted
used_indices = set(
    payment_amount_mismatch_indices
)

available_indices = payments_dirty_df.index[
    ~payments_dirty_df.index.isin(used_indices)
]

# Randomly select rows
orphan_payment_order_indices = np.random.choice(
    available_indices,
    size=num_orphan_payment_orders,
    replace=False
)

# Inject nonexistent order IDs
for counter, idx in enumerate(
    orphan_payment_order_indices,
    start=1
):

    original_order_id = payments_dirty_df.loc[
        idx,
        "order_id"
    ]

    # Real order IDs only run through O0120000
    invalid_order_id = f"O{9000000 + counter:07d}"

    # Log issue before modification
    payment_issue_log.append({
        "payment_id": payments_dirty_df.loc[
            idx,
            "payment_id"
        ],
        "issue_type": "referential_integrity_error",
        "column": "order_id",
        "original_value": original_order_id,
        "injected_value": invalid_order_id
    })

    # Inject nonexistent order ID
    payments_dirty_df.loc[
        idx,
        "order_id"
    ] = invalid_order_id


print(
    "Nonexistent order IDs injected:",
    num_orphan_payment_orders
)

print(
    "Total payment issues logged:",
    len(payment_issue_log)
)

Nonexistent order IDs injected: 150
Total payment issues logged: 350

In [107]:
# ---------------------------------------------------------
# Verify Nonexistent Order References
# ---------------------------------------------------------

valid_order_ids = set(
    orders_ground_truth_df["order_id"]
)

orphan_payment_mask = (
    payments_dirty_df["order_id"].notna()
    &
    ~payments_dirty_df["order_id"].isin(
        valid_order_ids
    )
)

print(
    "Payments referencing nonexistent orders:",
    orphan_payment_mask.sum()
)

payments_dirty_df.loc[
    orphan_payment_mask,
    [
        "payment_id",
        "order_id",
        "payment_date",
        "payment_method",
        "payment_amount"
    ]
].head(10)

Payments referencing nonexistent orders: 150

      payment_id  order_id payment_date  payment_method  payment_amount
214   PAY0000215  O9000056   2025-12-20  Digital Wallet         2066.69
410   PAY0000411  O9000073   2025-05-21     Credit Card          572.57
537   PAY0000538  O9000053   2025-11-23      Debit Card         1204.44
662   PAY0000663  O9000013   2024-10-21     Credit Card         2915.00
2088  PAY0002089  O9000054   2025-12-15     Credit Card          678.00
2422  PAY0002423  O9000029   2024-11-12     Credit Card          302.32
2614  PAY0002615  O9000085   2025-10-18      Debit Card          931.66
3885  PAY0003886  O9000039   2025-06-16     Credit Card           87.92
4262  PAY0004263  O9000090   2023-04-13  Digital Wallet         4033.94
6025  PAY0006026  O9000078   2024-06-01      Debit Card          433.07

In [108]:
# ---------------------------------------------------------
# Inject Payment Issue 3: Payment Before Order Date
# ---------------------------------------------------------

num_payment_date_errors = 100

# Avoid rows already corrupted
used_indices = (
    set(payment_amount_mismatch_indices)
    | set(orphan_payment_order_indices)
)

available_indices = payments_dirty_df.index[
    ~payments_dirty_df.index.isin(used_indices)
]

# Randomly select payment rows
payment_date_error_indices = np.random.choice(
    available_indices,
    size=num_payment_date_errors,
    replace=False
)

for idx in payment_date_error_indices:

    original_payment_date = pd.Timestamp(
        payments_dirty_df.loc[idx, "payment_date"]
    )

    # Move payment 1-7 days before the order date
    days_before = random.randint(1, 7)

    invalid_payment_date = (
        original_payment_date
        - pd.to_timedelta(days_before, unit="D")
    )

    # Log issue before modification
    payment_issue_log.append({
        "payment_id": payments_dirty_df.loc[
            idx,
            "payment_id"
        ],
        "issue_type": "temporal_consistency_error",
        "column": "payment_date",
        "original_value": original_payment_date,
        "injected_value": invalid_payment_date
    })

    # Inject incorrect payment date
    payments_dirty_df.loc[
        idx,
        "payment_date"
    ] = invalid_payment_date


print(
    "Payment-date errors injected:",
    num_payment_date_errors
)

print(
    "Total payment issues logged:",
    len(payment_issue_log)
)

Payment-date errors injected: 100
Total payment issues logged: 450

In [109]:
# ---------------------------------------------------------
# Verify Payment-Date Inconsistencies
# ---------------------------------------------------------

payment_date_check = (
    payments_dirty_df.loc[
        payment_date_error_indices,
        [
            "payment_id",
            "order_id",
            "payment_date"
        ]
    ]
    .merge(
        orders_ground_truth_df[
            [
                "order_id",
                "order_date"
            ]
        ],
        on="order_id",
        how="left"
    )
)

payment_date_check["payment_before_order"] = (
    pd.to_datetime(payment_date_check["payment_date"])
    <
    pd.to_datetime(payment_date_check["order_date"])
)

print(
    "Confirmed payments before order date:",
    payment_date_check[
        "payment_before_order"
    ].sum()
)

payment_date_check.head(10)

Confirmed payments before order date: 100

   payment_id  order_id payment_date order_date  payment_before_order
0  PAY0045825  O0045825   2025-07-14 2025-07-21                  True
1  PAY0034691  O0034691   2025-01-19 2025-01-21                  True
2  PAY0070271  O0070271   2023-11-29 2023-11-30                  True
3  PAY0030363  O0030363   2025-08-16 2025-08-21                  True
4  PAY0114979  O0114979   2024-09-09 2024-09-12                  True
5  PAY0103506  O0103506   2025-11-06 2025-11-11                  True
6  PAY0050007  O0050007   2024-03-17 2024-03-21                  True
7  PAY0058830  O0058830   2023-07-31 2023-08-04                  True
8  PAY0075391  O0075391   2025-04-16 2025-04-17                  True
9  PAY0090822  O0090822   2023-03-10 2023-03-17                  True

In [110]:
# ---------------------------------------------------------
# Inject Payment Issue 4: Payment Status Inconsistency
# ---------------------------------------------------------

num_payment_status_errors = 100

# Avoid rows already corrupted
used_indices = (
    set(payment_amount_mismatch_indices)
    | set(orphan_payment_order_indices)
    | set(payment_date_error_indices)
)

available_indices = payments_dirty_df.index[
    ~payments_dirty_df.index.isin(used_indices)
]

# Randomly select payment rows
payment_status_error_indices = np.random.choice(
    available_indices,
    size=num_payment_status_errors,
    replace=False
)

# Correct mapping used by our NovaRetail business rules
EXPECTED_PAYMENT_STATUS = {
    "Completed": "Successful",
    "Cancelled": "Failed",
    "Returned": "Refunded"
}

for idx in payment_status_error_indices:

    order_id = payments_dirty_df.loc[
        idx,
        "order_id"
    ]

    # Find corresponding order status
    order_status = orders_ground_truth_df.loc[
        orders_ground_truth_df["order_id"] == order_id,
        "order_status"
    ].iloc[0]

    correct_status = EXPECTED_PAYMENT_STATUS[
        order_status
    ]

    # Choose a status different from the correct one
    incorrect_statuses = [
        status
        for status in PAYMENT_STATUSES
        if status != correct_status
    ]

    incorrect_status = random.choice(
        incorrect_statuses
    )

    original_status = payments_dirty_df.loc[
        idx,
        "payment_status"
    ]

    # Log issue before modification
    payment_issue_log.append({
        "payment_id": payments_dirty_df.loc[
            idx,
            "payment_id"
        ],
        "issue_type": "consistency_error",
        "column": "payment_status",
        "original_value": original_status,
        "injected_value": incorrect_status
    })

    # Inject incorrect payment status
    payments_dirty_df.loc[
        idx,
        "payment_status"
    ] = incorrect_status


print(
    "Payment-status inconsistencies injected:",
    num_payment_status_errors
)

print(
    "Total payment issues logged:",
    len(payment_issue_log)
)

Payment-status inconsistencies injected: 100
Total payment issues logged: 550

In [111]:
# ---------------------------------------------------------
# Verify Payment-Status Inconsistencies
# ---------------------------------------------------------

payment_status_check = (
    payments_dirty_df.loc[
        payment_status_error_indices,
        [
            "payment_id",
            "order_id",
            "payment_status"
        ]
    ]
    .merge(
        orders_ground_truth_df[
            [
                "order_id",
                "order_status"
            ]
        ],
        on="order_id",
        how="left"
    )
)

payment_status_check["expected_payment_status"] = (
    payment_status_check["order_status"]
    .map(EXPECTED_PAYMENT_STATUS)
)

payment_status_check["status_mismatch"] = (
    payment_status_check["payment_status"]
    !=
    payment_status_check["expected_payment_status"]
)

print(
    "Confirmed payment-status inconsistencies:",
    payment_status_check["status_mismatch"].sum()
)

payment_status_check.head(10)

Confirmed payment-status inconsistencies: 100

,payment_id,order_id,payment_status,order_status,expected_payment_status,status_mismatch
0,PAY0011474,O0011474,Refunded,Completed,Successful,True
1,PAY0070650,O0070650,Refunded,Completed,Successful,True
2,PAY0084745,O0084745,Refunded,Completed,Successful,True
3,PAY0031649,O0031649,Failed,Completed,Successful,True
4,PAY0115335,O0115335,Failed,Returned,Refunded,True
5,PAY0090336,O0090336,Successful,Returned,Refunded,True
6,PAY0013391,O0013391,Failed,Completed,Successful,True
7,PAY0074837,O0074837,Failed,Completed,Successful,True
8,PAY0053107,O0053107,Failed,Completed,Successful,True
9,PAY0025781,O0025781,Failed,Completed,Successful,True

In [112]:
# ---------------------------------------------------------
# Inject Payment Issue 5: Duplicate Payment Records
# ---------------------------------------------------------

num_duplicate_payments = 100

# Avoid rows already corrupted
used_indices = (
    set(payment_amount_mismatch_indices)
    | set(orphan_payment_order_indices)
    | set(payment_date_error_indices)
    | set(payment_status_error_indices)
)

available_indices = payments_dirty_df.index[
    ~payments_dirty_df.index.isin(used_indices)
]

# Randomly select clean payment records
duplicate_payment_source_indices = np.random.choice(
    available_indices,
    size=num_duplicate_payments,
    replace=False
)

# Copy selected payment records
duplicate_payment_records = payments_dirty_df.loc[
    duplicate_payment_source_indices
].copy()

# Log each duplicate issue
for idx in duplicate_payment_source_indices:

    payment_id = payments_dirty_df.loc[
        idx,
        "payment_id"
    ]

    payment_issue_log.append({
        "payment_id": payment_id,
        "issue_type": "duplicate_record",
        "column": "payment_id",
        "original_value": payment_id,
        "injected_value": payment_id
    })

# Append duplicate rows
payments_dirty_df = pd.concat(
    [
        payments_dirty_df,
        duplicate_payment_records
    ],
    ignore_index=True
)

print(
    "Duplicate payments injected:",
    num_duplicate_payments
)

print(
    "New payments dataset size:",
    len(payments_dirty_df)
)

print(
    "Total payment issues logged:",
    len(payment_issue_log)
)

Duplicate payments injected: 100
New payments dataset size: 120100
Total payment issues logged: 650

In [113]:
# ---------------------------------------------------------
# Verify Duplicate Payments
# ---------------------------------------------------------

duplicate_payment_check = payments_dirty_df[
    payments_dirty_df.duplicated(
        subset=["payment_id"],
        keep=False
    )
].sort_values("payment_id")

print(
    "Rows involved in duplicate payment IDs:",
    len(duplicate_payment_check)
)

print(
    "Payment IDs with duplicates:",
    duplicate_payment_check[
        "payment_id"
    ].nunique()
)

duplicate_payment_check.head(10)

Rows involved in duplicate payment IDs: 200
Payment IDs with duplicates: 100

,payment_id,order_id,payment_date,payment_method,payment_status,payment_amount
2875,PAY0002876,O0002876,2025-07-18,Digital Wallet,Refunded,3092.47
120006,PAY0002876,O0002876,2025-07-18,Digital Wallet,Refunded,3092.47
3497,PAY0003498,O0003498,2024-11-30,Credit Card,Successful,901.26
120076,PAY0003498,O0003498,2024-11-30,Credit Card,Successful,901.26
3977,PAY0003978,O0003978,2025-05-10,PayPal,Successful,185.65
120018,PAY0003978,O0003978,2025-05-10,PayPal,Successful,185.65
4683,PAY0004684,O0004684,2025-08-18,PayPal,Successful,1654.90
120096,PAY0004684,O0004684,2025-08-18,PayPal,Successful,1654.90
4941,PAY0004942,O0004942,2025-04-17,Debit Card,Successful,130.53
120031,PAY0004942,O0004942,2025-04-17,Debit Card,Successful,130.53

In [114]:
# ---------------------------------------------------------
# Convert Payment Issue Log to DataFrame
# ---------------------------------------------------------

payment_issue_log_df = pd.DataFrame(
    payment_issue_log
)

print("Payment issue log created successfully!")

print(
    "Total logged issues:",
    len(payment_issue_log_df)
)

print("\nIssues by type:")

print(
    payment_issue_log_df["issue_type"]
    .value_counts()
)

payment_issue_log_df.head(10)

Payment issue log created successfully!
Total logged issues: 650

Issues by type:
issue_type
reconciliation_error           200
referential_integrity_error    150
temporal_consistency_error     100
consistency_error              100
duplicate_record               100
Name: count, dtype: int64

,payment_id,issue_type,column,original_value,injected_value
0,PAY0020520,reconciliation_error,payment_amount,3233.53,2263.47
1,PAY0071732,reconciliation_error,payment_amount,2706.08,2976.69
2,PAY0063657,reconciliation_error,payment_amount,519.4,363.58
3,PAY0030722,reconciliation_error,payment_amount,1940.09,2134.1
4,PAY0027089,reconciliation_error,payment_amount,1582.8,1107.96
5,PAY0011913,reconciliation_error,payment_amount,2873.82,3735.97
6,PAY0047462,reconciliation_error,payment_amount,2909.46,3200.41
7,PAY0118536,reconciliation_error,payment_amount,1157.96,926.37
8,PAY0115314,reconciliation_error,payment_amount,986.71,690.7
9,PAY0062202,reconciliation_error,payment_amount,1032.51,1239.01

In [115]:
# ---------------------------------------------------------
# Verify Payment Issue Counts
# ---------------------------------------------------------

expected_payment_issue_counts = {
    "reconciliation_error": 200,
    "referential_integrity_error": 150,
    "temporal_consistency_error": 100,
    "consistency_error": 100,
    "duplicate_record": 100
}

actual_payment_issue_counts = (
    payment_issue_log_df["issue_type"]
    .value_counts()
    .to_dict()
)

for issue_type, expected_count in expected_payment_issue_counts.items():

    actual_count = actual_payment_issue_counts.get(
        issue_type,
        0
    )

    status = (
        "PASS"
        if actual_count == expected_count
        else "FAIL"
    )

    print(
        f"{issue_type}: "
        f"Expected={expected_count}, "
        f"Actual={actual_count} "
        f"[{status}]"
    )

reconciliation_error: Expected=200, Actual=200 [PASS]
referential_integrity_error: Expected=150, Actual=150 [PASS]
temporal_consistency_error: Expected=100, Actual=100 [PASS]
consistency_error: Expected=100, Actual=100 [PASS]
duplicate_record: Expected=100, Actual=100 [PASS]

In [116]:
# ---------------------------------------------------------
# Save Payments Dataset and Ground-Truth Issue Log
# ---------------------------------------------------------

# File paths
payments_file = (
    INCOMING_DIR / "payments.csv"
)

payment_issue_log_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "payment_issue_ground_truth.csv"
)

# Save dirty payment data
payments_dirty_df.to_csv(
    payments_file,
    index=False
)

# Save payment issue ground truth
payment_issue_log_df.to_csv(
    payment_issue_log_file,
    index=False
)

print("Payment files saved successfully!")

print("\nPayment source file:")
print(payments_file)

print("\nPayment issue ground-truth file:")
print(payment_issue_log_file)

Payment files saved successfully!

Payment source file:
/Users/aryayogirajingale/Documents/DataTrust/data/incoming/payments.csv

Payment issue ground-truth file:
/Users/aryayogirajingale/Documents/DataTrust/data/raw/payment_issue_ground_truth.csv

In [117]:
# ---------------------------------------------------------
# Verify Saved Payment Files
# ---------------------------------------------------------

print(
    "payments.csv exists:",
    payments_file.exists()
)

print(
    "Payment issue log exists:",
    payment_issue_log_file.exists()
)

# Read payments.csv back from disk
saved_payments = pd.read_csv(
    payments_file
)

print(
    "\nSaved payment rows:",
    len(saved_payments)
)

print(
    "\nSaved payment columns:",
    len(saved_payments.columns)
)

print(
    "\nGround-truth issues:",
    len(payment_issue_log_df)
)

print(
    "\nFile size:",
    f"{payments_file.stat().st_size / 1024 / 1024:.2f} MB"
)

payments.csv exists: True
Payment issue log exists: True

Saved payment rows: 120100

Saved payment columns: 6

Ground-truth issues: 650

File size: 6.91 MB

In [118]:
# ---------------------------------------------------------
# Returns Dataset Configuration
# ---------------------------------------------------------

RETURN_REASONS = [
    "Damaged",
    "Defective",
    "Wrong Item",
    "Not as Described",
    "Changed Mind",
    "Size/Fit Issue",
    "Arrived Late"
]

MIN_RETURN_DAYS = 1
MAX_RETURN_DAYS = 30

print("Returns configuration created!")

print(
    "Return reasons:",
    RETURN_REASONS
)

print(
    "Return window:",
    f"{MIN_RETURN_DAYS}-{MAX_RETURN_DAYS} days"
)

Returns configuration created!
Return reasons: ['Damaged', 'Defective', 'Wrong Item', 'Not as Described', 'Changed Mind', 'Size/Fit Issue', 'Arrived Late']
Return window: 1-30 days

In [119]:
# ---------------------------------------------------------
# Identify Orders Marked as Returned
# ---------------------------------------------------------

returned_orders_df = (
    orders_ground_truth_df[
        orders_ground_truth_df["order_status"] == "Returned"
    ]
    .copy()
)

print("Returned orders identified!")

print(
    "Total returned orders:",
    len(returned_orders_df)
)

print(
    "Unique returned order IDs:",
    returned_orders_df["order_id"].nunique()
)

returned_orders_df.head(10)

Returned orders identified!
Total returned orders: 3649
Unique returned order IDs: 3649

,order_id,customer_id,order_date,sales_channel,order_status,payment_method,shipping_city,shipping_state,shipping_region
1,O0000002,C016387,2024-06-16,Mobile App,Returned,PayPal,Detroit,MI,Midwest
43,O0000044,C011415,2023-04-27,Website,Returned,Debit Card,Atlanta,GA,South
98,O0000099,C016685,2025-05-26,Mobile App,Returned,Debit Card,Phoenix,AZ,West
105,O0000106,C022808,2025-12-24,Website,Returned,Debit Card,New York,NY,Northeast
185,O0000186,C034683,2025-11-07,Website,Returned,Digital Wallet,Kansas City,MO,Midwest
246,O0000247,C037531,2024-08-02,Physical Store,Returned,Debit Card,Houston,TX,South
261,O0000262,C043041,2024-12-22,Physical Store,Returned,Credit Card,Buffalo,NY,Northeast
334,O0000335,C023518,2025-06-27,Website,Returned,PayPal,Philadelphia,PA,Northeast
342,O0000343,C031083,2025-02-13,Website,Returned,Debit Card,Kansas City,MO,Midwest
401,O0000402,C041888,2025-12-09,Physical Store,Returned,Debit Card,Kansas City,MO,Midwest

In [120]:
# ---------------------------------------------------------
# Find Line Items Belonging to Returned Orders
# ---------------------------------------------------------

returned_order_ids = set(
    returned_orders_df["order_id"]
)

eligible_return_items_df = (
    order_items_ground_truth_df[
        order_items_ground_truth_df["order_id"].isin(
            returned_order_ids
        )
    ]
    .copy()
)

print("Eligible return items identified!")

print(
    "Returned orders:",
    len(returned_orders_df)
)

print(
    "Eligible line items:",
    len(eligible_return_items_df)
)

print(
    "Returned orders represented in line items:",
    eligible_return_items_df["order_id"].nunique()
)

eligible_return_items_df.head(10)

Eligible return items identified!
Returned orders: 3649
Eligible line items: 9417
Returned orders represented in line items: 3649

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,unit_cost
5,OI00000006,O0000002,P01888,1,1020.14,0.20,699.68
6,OI00000007,O0000002,P00776,1,1094.89,0.00,695.61
7,OI00000008,O0000002,P01373,2,35.08,0.00,24.06
110,OI00000111,O0000044,P00160,1,660.04,0.00,484.36
111,OI00000112,O0000044,P01361,2,46.90,0.00,33.17
112,OI00000113,O0000044,P00338,1,297.22,0.05,192.63
241,OI00000242,O0000099,P01164,1,136.82,0.00,95.62
242,OI00000243,O0000099,P01122,2,208.00,0.30,145.46
261,OI00000262,O0000106,P01085,5,87.25,0.25,55.03
262,OI00000263,O0000106,P01313,1,187.44,0.25,137.89

In [121]:
# ---------------------------------------------------------
# Select Line Items to Return
# ---------------------------------------------------------

selected_return_indices = []

# Process each returned order separately
for order_id, group in eligible_return_items_df.groupby("order_id"):

    num_items_in_order = len(group)

    # Every returned order must have at least one returned item
    if num_items_in_order == 1:
        num_items_to_return = 1

    else:
        # Randomly return between 1 and all items in the order
        num_items_to_return = random.randint(
            1,
            num_items_in_order
        )

    # Randomly select the line items
    selected_indices = random.sample(
        list(group.index),
        k=num_items_to_return
    )

    selected_return_indices.extend(
        selected_indices
    )


selected_return_items_df = (
    eligible_return_items_df.loc[
        selected_return_indices
    ]
    .copy()
)

print("Return line items selected!")

print(
    "Selected return line items:",
    len(selected_return_items_df)
)

print(
    "Returned orders represented:",
    selected_return_items_df["order_id"].nunique()
)

print(
    "Expected returned orders:",
    len(returned_orders_df)
)

Return line items selected!
Selected return line items: 6510
Returned orders represented: 3649
Expected returned orders: 3649

In [122]:
# ---------------------------------------------------------
# Verify Every Returned Order Has a Return Item
# ---------------------------------------------------------

orders_with_return_items = set(
    selected_return_items_df["order_id"]
)

expected_returned_orders = set(
    returned_orders_df["order_id"]
)

missing_return_orders = (
    expected_returned_orders
    - orders_with_return_items
)

print(
    "Returned orders missing a return item:",
    len(missing_return_orders)
)

if len(missing_return_orders) == 0:
    print("PASS - Every returned order has at least one return item.")
else:
    print("FAIL - Some returned orders have no return item.")

Returned orders missing a return item: 0
PASS - Every returned order has at least one return item.

In [123]:
# ---------------------------------------------------------
# Generate Clean Returns Dataset
# ---------------------------------------------------------

# Get order dates for returned items
returns_source_df = selected_return_items_df.merge(
    orders_ground_truth_df[
        ["order_id", "order_date"]
    ],
    on="order_id",
    how="left"
)

return_records = []

for counter, (_, row) in enumerate(
    returns_source_df.iterrows(),
    start=1
):

    # Return quantity cannot exceed purchased quantity
    return_quantity = np.random.randint(
        1,
        int(row["quantity"]) + 1
    )

    # Return occurs 1-30 days after purchase
    days_after_order = np.random.randint(
        MIN_RETURN_DAYS,
        MAX_RETURN_DAYS + 1
    )

    return_date = (
        pd.Timestamp(row["order_date"])
        + pd.Timedelta(days=days_after_order)
    )

    # Select a return reason
    return_reason = np.random.choice(
        RETURN_REASONS
    )

    # Calculate refund using original transaction price
    refund_amount = (
        return_quantity
        * float(row["unit_price"])
        * (1 - float(row["discount_pct"]))
    )

    return_records.append({
        "return_id": f"R{counter:07d}",
        "order_item_id": row["order_item_id"],
        "order_id": row["order_id"],
        "product_id": row["product_id"],
        "return_date": return_date,
        "return_quantity": return_quantity,
        "return_reason": return_reason,
        "refund_amount": round(refund_amount, 2)
    })


returns_clean_df = pd.DataFrame(
    return_records
)

print("Clean returns dataset generated!")

print(
    "Total return records:",
    len(returns_clean_df)
)

print(
    "Unique returned orders:",
    returns_clean_df["order_id"].nunique()
)

print(
    "Unique returned products:",
    returns_clean_df["product_id"].nunique()
)

print(
    "Total refund amount:",
    round(
        returns_clean_df["refund_amount"].sum(),
        2
    )
)

returns_clean_df.head(10)

Clean returns dataset generated!
Total return records: 6510
Unique returned orders: 3649
Unique returned products: 1916
Total refund amount: 3216607.05

,return_id,order_item_id,order_id,product_id,return_date,return_quantity,return_reason,refund_amount
0,R0000001,OI00000008,O0000002,P01373,2024-07-03,2,Wrong Item,70.16
1,R0000002,OI00000007,O0000002,P00776,2024-07-11,1,Not as Described,1094.89
2,R0000003,OI00000006,O0000002,P01888,2024-07-16,1,Arrived Late,816.11
3,R0000004,OI00000112,O0000044,P01361,2023-05-09,2,Defective,93.80
4,R0000005,OI00000113,O0000044,P00338,2023-05-21,1,Damaged,282.36
5,R0000006,OI00000242,O0000099,P01164,2025-06-19,1,Not as Described,136.82
6,R0000007,OI00000243,O0000099,P01122,2025-06-01,1,Size/Fit Issue,145.60
7,R0000008,OI00000264,O0000106,P01946,2026-01-23,1,Size/Fit Issue,452.77
8,R0000009,OI00000262,O0000106,P01085,2026-01-11,4,Not as Described,261.75
9,R0000010,OI00000462,O0000186,P00754,2025-11-18,2,Changed Mind,638.91

In [124]:
# ---------------------------------------------------------
# Validate Clean Returns Dataset
# ---------------------------------------------------------

print("Returns dataset shape:", returns_clean_df.shape)

print(
    "Missing values:",
    returns_clean_df.isnull().sum().sum()
)

print(
    "Duplicate return IDs:",
    returns_clean_df["return_id"].duplicated().sum()
)

print(
    "Invalid return quantities:",
    (returns_clean_df["return_quantity"] <= 0).sum()
)

print(
    "Invalid refund amounts:",
    (returns_clean_df["refund_amount"] <= 0).sum()
)

print(
    "Invalid return reasons:",
    (~returns_clean_df["return_reason"].isin(
        RETURN_REASONS
    )).sum()
)

Returns dataset shape: (6510, 8)
Missing values: 0
Duplicate return IDs: 0
Invalid return quantities: 0
Invalid refund amounts: 0
Invalid return reasons: 0

In [125]:
# ---------------------------------------------------------
# Validate Return References
# ---------------------------------------------------------

valid_order_ids = set(
    orders_ground_truth_df["order_id"]
)

valid_order_item_ids = set(
    order_items_ground_truth_df["order_item_id"]
)

valid_product_ids = set(
    products_ground_truth_df["product_id"]
)

invalid_return_orders = (
    ~returns_clean_df["order_id"].isin(
        valid_order_ids
    )
).sum()

invalid_return_items = (
    ~returns_clean_df["order_item_id"].isin(
        valid_order_item_ids
    )
).sum()

invalid_return_products = (
    ~returns_clean_df["product_id"].isin(
        valid_product_ids
    )
).sum()

print(
    "Invalid order references:",
    invalid_return_orders
)

print(
    "Invalid order-item references:",
    invalid_return_items
)

print(
    "Invalid product references:",
    invalid_return_products
)

Invalid order references: 0
Invalid order-item references: 0
Invalid product references: 0

In [126]:
# ---------------------------------------------------------
# Validate Return Dates
# ---------------------------------------------------------

return_date_check = returns_clean_df.merge(
    orders_ground_truth_df[
        ["order_id", "order_date"]
    ],
    on="order_id",
    how="left"
)

return_date_check["days_to_return"] = (
    pd.to_datetime(
        return_date_check["return_date"]
    )
    - pd.to_datetime(
        return_date_check["order_date"]
    )
).dt.days

invalid_return_dates = (
    (
        return_date_check["days_to_return"]
        < MIN_RETURN_DAYS
    )
    |
    (
        return_date_check["days_to_return"]
        > MAX_RETURN_DAYS
    )
).sum()

print(
    "Invalid return dates:",
    invalid_return_dates
)

print(
    "Minimum days to return:",
    return_date_check["days_to_return"].min()
)

print(
    "Maximum days to return:",
    return_date_check["days_to_return"].max()
)

Invalid return dates: 0
Minimum days to return: 1
Maximum days to return: 30

In [127]:
# ---------------------------------------------------------
# Preserve Clean Returns Ground Truth
# ---------------------------------------------------------

returns_ground_truth_df = returns_clean_df.copy(
    deep=True
)

# Create the working copy where we will inject problems
returns_dirty_df = returns_ground_truth_df.copy(
    deep=True
)

# Empty list for tracking every injected issue
return_issue_log = []

print("Returns ground truth preserved!")

print(
    "Ground-truth rows:",
    len(returns_ground_truth_df)
)

print(
    "Working dirty rows:",
    len(returns_dirty_df)
)

print(
    "Issues currently logged:",
    len(return_issue_log)
)

Returns ground truth preserved!
Ground-truth rows: 6510
Working dirty rows: 6510
Issues currently logged: 0

In [128]:
# ---------------------------------------------------------
# Verify Returns Ground Truth
# ---------------------------------------------------------

print(
    "Same number of rows:",
    len(returns_ground_truth_df)
    == len(returns_dirty_df)
)

print(
    "Datasets currently identical:",
    returns_ground_truth_df.equals(
        returns_dirty_df
    )
)

print(
    "Ground-truth return IDs unique:",
    returns_ground_truth_df[
        "return_id"
    ].is_unique
)

Same number of rows: True
Datasets currently identical: True
Ground-truth return IDs unique: True

In [129]:
# ---------------------------------------------------------
# Inject Return Issue 1: Invalid Return Quantity
# ---------------------------------------------------------

num_invalid_return_quantities = 100

# Randomly select return records
invalid_return_quantity_indices = np.random.choice(
    returns_dirty_df.index,
    size=num_invalid_return_quantities,
    replace=False
)

# Lookup purchased quantities by order_item_id
purchased_quantity_lookup = (
    order_items_ground_truth_df
    .set_index("order_item_id")["quantity"]
)

for idx in invalid_return_quantity_indices:

    order_item_id = returns_dirty_df.loc[
        idx,
        "order_item_id"
    ]

    original_return_quantity = returns_dirty_df.loc[
        idx,
        "return_quantity"
    ]

    purchased_quantity = int(
        purchased_quantity_lookup.loc[
            order_item_id
        ]
    )

    # Force returned quantity to exceed purchased quantity
    invalid_quantity = purchased_quantity + np.random.randint(
        1,
        4
    )

    returns_dirty_df.loc[
        idx,
        "return_quantity"
    ] = invalid_quantity

    # Record the intentionally injected issue
    return_issue_log.append({
        "return_id": returns_dirty_df.loc[idx, "return_id"],
        "issue_type": "business_rule_violation",
        "column": "return_quantity",
        "original_value": original_return_quantity,
        "injected_value": invalid_quantity
    })


print(
    "Invalid return quantities injected:",
    num_invalid_return_quantities
)

print(
    "Total return issues logged:",
    len(return_issue_log)
)

Invalid return quantities injected: 100
Total return issues logged: 100

In [130]:
# ---------------------------------------------------------
# Verify Invalid Return Quantities
# ---------------------------------------------------------

return_quantity_check = returns_dirty_df.merge(
    order_items_ground_truth_df[
        ["order_item_id", "quantity"]
    ],
    on="order_item_id",
    how="left"
)

invalid_quantity_count = (
    return_quantity_check["return_quantity"]
    > return_quantity_check["quantity"]
).sum()

print(
    "Returns exceeding purchased quantity:",
    invalid_quantity_count
)

return_quantity_check[
    return_quantity_check["return_quantity"]
    > return_quantity_check["quantity"]
][
    [
        "return_id",
        "order_item_id",
        "quantity",
        "return_quantity"
    ]
].head(10)

Returns exceeding purchased quantity: 100

    return_id order_item_id  quantity  return_quantity
76   R0000077    OI00003117         1                2
159  R0000160    OI00006825         1                2
208  R0000209    OI00009608         3                5
321  R0000322    OI00014791         1                3
359  R0000360    OI00016347         4                5
415  R0000416    OI00019150         1                2
435  R0000436    OI00019823         2                5
678  R0000679    OI00033566         1                3
696  R0000697    OI00033928         1                4
739  R0000740    OI00035639         1                4

In [131]:
# ---------------------------------------------------------
# Inject Return Issue 2: Invalid Refund Amount
# ---------------------------------------------------------

num_invalid_refund_amounts = 100

# Avoid rows already corrupted in Step 79
available_indices = returns_dirty_df.index[
    ~returns_dirty_df.index.isin(
        invalid_return_quantity_indices
    )
]

invalid_refund_amount_indices = np.random.choice(
    available_indices,
    size=num_invalid_refund_amounts,
    replace=False
)

for idx in invalid_refund_amount_indices:

    original_refund = returns_dirty_df.loc[
        idx,
        "refund_amount"
    ]

    # Change refund by a noticeable amount
    multiplier = np.random.choice(
        [0.50, 0.70, 0.80, 1.20, 1.30, 1.50]
    )

    invalid_refund = round(
        float(original_refund) * multiplier,
        2
    )

    returns_dirty_df.loc[
        idx,
        "refund_amount"
    ] = invalid_refund

    return_issue_log.append({
        "return_id": returns_dirty_df.loc[idx, "return_id"],
        "issue_type": "reconciliation_error",
        "column": "refund_amount",
        "original_value": original_refund,
        "injected_value": invalid_refund
    })


print(
    "Invalid refund amounts injected:",
    num_invalid_refund_amounts
)

print(
    "Total return issues logged:",
    len(return_issue_log)
)

Invalid refund amounts injected: 100
Total return issues logged: 200

In [132]:
# ---------------------------------------------------------
# Verify Invalid Refund Amounts
# ---------------------------------------------------------

clean_refund_lookup = (
    returns_ground_truth_df
    .set_index("return_id")["refund_amount"]
)

refund_mismatch_count = 0

for idx in invalid_refund_amount_indices:

    return_id = returns_dirty_df.loc[
        idx,
        "return_id"
    ]

    dirty_refund = returns_dirty_df.loc[
        idx,
        "refund_amount"
    ]

    clean_refund = clean_refund_lookup.loc[
        return_id
    ]

    if dirty_refund != clean_refund:
        refund_mismatch_count += 1


print(
    "Refund amount mismatches:",
    refund_mismatch_count
)

Refund amount mismatches: 100

In [133]:
# ---------------------------------------------------------
# Inject Return Issue 3: Return Outside Allowed Window
# ---------------------------------------------------------

num_invalid_return_dates = 100

# Avoid rows already corrupted in previous steps
used_indices = (
    set(invalid_return_quantity_indices)
    | set(invalid_refund_amount_indices)
)

available_indices = returns_dirty_df.index[
    ~returns_dirty_df.index.isin(used_indices)
]

invalid_return_date_indices = np.random.choice(
    available_indices,
    size=num_invalid_return_dates,
    replace=False
)

# Lookup original order dates
order_date_lookup = (
    orders_ground_truth_df
    .set_index("order_id")["order_date"]
)

for idx in invalid_return_date_indices:

    order_id = returns_dirty_df.loc[
        idx,
        "order_id"
    ]

    original_return_date = returns_dirty_df.loc[
        idx,
        "return_date"
    ]

    order_date = pd.Timestamp(
        order_date_lookup.loc[order_id]
    )

    # Force return to occur 31-90 days after purchase
    invalid_days_after_order = np.random.randint(
        31,
        91
    )

    invalid_return_date = (
        order_date
        + pd.Timedelta(
            days=int(invalid_days_after_order)
        )
    )

    returns_dirty_df.loc[
        idx,
        "return_date"
    ] = invalid_return_date

    return_issue_log.append({
        "return_id": returns_dirty_df.loc[idx, "return_id"],
        "issue_type": "temporal_consistency_error",
        "column": "return_date",
        "original_value": original_return_date,
        "injected_value": invalid_return_date
    })


print(
    "Invalid return dates injected:",
    num_invalid_return_dates
)

print(
    "Total return issues logged:",
    len(return_issue_log)
)

Invalid return dates injected: 100
Total return issues logged: 300

In [134]:
# ---------------------------------------------------------
# Verify Invalid Return Dates
# ---------------------------------------------------------

return_date_validation = returns_dirty_df.merge(
    orders_ground_truth_df[
        ["order_id", "order_date"]
    ],
    on="order_id",
    how="left"
)

return_date_validation["days_to_return"] = (
    pd.to_datetime(
        return_date_validation["return_date"]
    )
    - pd.to_datetime(
        return_date_validation["order_date"]
    )
).dt.days

invalid_window_count = (
    return_date_validation["days_to_return"]
    > MAX_RETURN_DAYS
).sum()

print(
    "Returns outside 30-day window:",
    invalid_window_count
)

return_date_validation[
    return_date_validation["days_to_return"]
    > MAX_RETURN_DAYS
][
    [
        "return_id",
        "order_id",
        "order_date",
        "return_date",
        "days_to_return"
    ]
].head(10)

Returns outside 30-day window: 100

    return_id  order_id order_date return_date  days_to_return
60   R0000061  O0000940 2025-04-27  2025-07-03              67
288  R0000289  O0005075 2023-11-27  2024-02-02              67
349  R0000350  O0006212 2024-06-23  2024-09-03              72
400  R0000401  O0007068 2023-12-28  2024-03-05              68
448  R0000449  O0007987 2025-08-17  2025-10-12              56
562  R0000563  O0010279 2025-08-05  2025-09-16              42
618  R0000619  O0011636 2025-09-13  2025-10-16              33
647  R0000648  O0012439 2025-01-19  2025-04-01              72
701  R0000702  O0013279 2024-05-28  2024-07-19              52
821  R0000822  O0015151 2025-07-27  2025-10-24              89

In [135]:
# ---------------------------------------------------------
# Inject Return Issue 4: Invalid Return Reason
# ---------------------------------------------------------

num_invalid_return_reasons = 75

# Avoid rows already corrupted
used_indices = (
    set(invalid_return_quantity_indices)
    | set(invalid_refund_amount_indices)
    | set(invalid_return_date_indices)
)

available_indices = returns_dirty_df.index[
    ~returns_dirty_df.index.isin(used_indices)
]

invalid_return_reason_indices = np.random.choice(
    available_indices,
    size=num_invalid_return_reasons,
    replace=False
)

INVALID_RETURN_REASONS = [
    "Unknown",
    "Other123",
    "N/A",
    "Customer Complaint",
    "No Reason"
]

for idx in invalid_return_reason_indices:

    original_reason = returns_dirty_df.loc[
        idx,
        "return_reason"
    ]

    invalid_reason = np.random.choice(
        INVALID_RETURN_REASONS
    )

    returns_dirty_df.loc[
        idx,
        "return_reason"
    ] = invalid_reason

    return_issue_log.append({
        "return_id": returns_dirty_df.loc[idx, "return_id"],
        "issue_type": "invalid_category",
        "column": "return_reason",
        "original_value": original_reason,
        "injected_value": invalid_reason
    })


print(
    "Invalid return reasons injected:",
    num_invalid_return_reasons
)

print(
    "Total return issues logged:",
    len(return_issue_log)
)

Invalid return reasons injected: 75
Total return issues logged: 375

In [136]:
# ---------------------------------------------------------
# Verify Invalid Return Reasons
# ---------------------------------------------------------

invalid_reason_check = returns_dirty_df[
    ~returns_dirty_df["return_reason"].isin(
        RETURN_REASONS
    )
]

print(
    "Invalid return reasons found:",
    len(invalid_reason_check)
)

print("\nInvalid values:")

print(
    invalid_reason_check[
        "return_reason"
    ].value_counts()
)

invalid_reason_check[
    [
        "return_id",
        "order_id",
        "product_id",
        "return_reason"
    ]
].head(10)

Invalid return reasons found: 75

Invalid values:
return_reason
Unknown               23
N/A                   17
Customer Complaint    13
Other123              13
No Reason              9
Name: count, dtype: int64

    return_id  order_id product_id       return_reason
95   R0000096  O0001489     P01592  Customer Complaint
177  R0000178  O0003253     P01541           No Reason
257  R0000258  O0004647     P00089  Customer Complaint
470  R0000471  O0008358     P00562                 N/A
493  R0000494  O0008978     P00663                 N/A
559  R0000560  O0010233     P00455                 N/A
597  R0000598  O0010991     P01119            Other123
726  R0000727  O0013662     P00642                 N/A
876  R0000877  O0016036     P01177                 N/A
894  R0000895  O0016475     P00446             Unknown

In [137]:
# ---------------------------------------------------------
# Inject Return Issue 5: Nonexistent Order Item IDs
# ---------------------------------------------------------

num_orphan_return_items = 75

# Avoid rows already corrupted
used_indices = (
    set(invalid_return_quantity_indices)
    | set(invalid_refund_amount_indices)
    | set(invalid_return_date_indices)
    | set(invalid_return_reason_indices)
)

available_indices = returns_dirty_df.index[
    ~returns_dirty_df.index.isin(used_indices)
]

orphan_return_item_indices = np.random.choice(
    available_indices,
    size=num_orphan_return_items,
    replace=False
)

for counter, idx in enumerate(
    orphan_return_item_indices,
    start=1
):

    original_order_item_id = returns_dirty_df.loc[
        idx,
        "order_item_id"
    ]

    # Generate an ID that does not exist
    invalid_order_item_id = (
        f"OI9{counter:07d}"
    )

    returns_dirty_df.loc[
        idx,
        "order_item_id"
    ] = invalid_order_item_id

    return_issue_log.append({
        "return_id": returns_dirty_df.loc[idx, "return_id"],
        "issue_type": "referential_integrity_error",
        "column": "order_item_id",
        "original_value": original_order_item_id,
        "injected_value": invalid_order_item_id
    })


print(
    "Nonexistent order-item IDs injected:",
    num_orphan_return_items
)

print(
    "Total return issues logged:",
    len(return_issue_log)
)

Nonexistent order-item IDs injected: 75
Total return issues logged: 450

In [138]:
# ---------------------------------------------------------
# Verify Nonexistent Order Item References
# ---------------------------------------------------------

valid_order_item_ids = set(
    order_items_ground_truth_df[
        "order_item_id"
    ]
)

orphan_return_check = returns_dirty_df[
    ~returns_dirty_df[
        "order_item_id"
    ].isin(valid_order_item_ids)
]

print(
    "Returns with nonexistent order-item IDs:",
    len(orphan_return_check)
)

orphan_return_check[
    [
        "return_id",
        "order_item_id",
        "order_id",
        "product_id"
    ]
].head(10)

Returns with nonexistent order-item IDs: 75

    return_id order_item_id  order_id product_id
8    R0000009    OI90000040  O0000106     P01085
123  R0000124    OI90000023  O0001982     P01230
144  R0000145    OI90000008  O0002405     P01119
180  R0000181    OI90000046  O0003253     P01399
211  R0000212    OI90000016  O0003738     P00744
279  R0000280    OI90000048  O0005012     P01625
343  R0000344    OI90000013  O0006041     P01172
482  R0000483    OI90000021  O0008657     P00594
548  R0000549    OI90000059  O0009973     P00946
549  R0000550    OI90000066  O0009974     P01528

In [139]:
# ---------------------------------------------------------
# Inject Return Issue 6: Duplicate Return Records
# ---------------------------------------------------------

num_duplicate_returns = 50

# Avoid rows already corrupted
used_indices = (
    set(invalid_return_quantity_indices)
    | set(invalid_refund_amount_indices)
    | set(invalid_return_date_indices)
    | set(invalid_return_reason_indices)
    | set(orphan_return_item_indices)
)

available_indices = returns_dirty_df.index[
    ~returns_dirty_df.index.isin(used_indices)
]

# Select records to duplicate
duplicate_return_source_indices = np.random.choice(
    available_indices,
    size=num_duplicate_returns,
    replace=False
)

# Copy the selected records
duplicate_return_records = returns_dirty_df.loc[
    duplicate_return_source_indices
].copy()

# Log the duplicate issues
for idx in duplicate_return_source_indices:

    return_id = returns_dirty_df.loc[
        idx,
        "return_id"
    ]

    return_issue_log.append({
        "return_id": return_id,
        "issue_type": "duplicate_record",
        "column": "return_id",
        "original_value": return_id,
        "injected_value": return_id
    })

# Append duplicates to dirty dataset
returns_dirty_df = pd.concat(
    [
        returns_dirty_df,
        duplicate_return_records
    ],
    ignore_index=True
)

print(
    "Duplicate returns injected:",
    num_duplicate_returns
)

print(
    "New returns dataset size:",
    len(returns_dirty_df)
)

print(
    "Total return issues logged:",
    len(return_issue_log)
)

Duplicate returns injected: 50
New returns dataset size: 6560
Total return issues logged: 500

In [140]:
# ---------------------------------------------------------
# Verify Duplicate Return Records
# ---------------------------------------------------------

duplicate_return_check = returns_dirty_df[
    returns_dirty_df.duplicated(
        subset=["return_id"],
        keep=False
    )
].sort_values("return_id")

print(
    "Rows involved in duplicate return IDs:",
    len(duplicate_return_check)
)

print(
    "Return IDs with duplicates:",
    duplicate_return_check[
        "return_id"
    ].nunique()
)

duplicate_return_check[
    [
        "return_id",
        "order_item_id",
        "order_id",
        "product_id",
        "refund_amount"
    ]
].head(10)

Rows involved in duplicate return IDs: 100
Return IDs with duplicates: 50

     return_id order_item_id  order_id product_id  refund_amount
11    R0000012    OI00000636  O0000247     P00583         943.07
6533  R0000012    OI00000636  O0000247     P00583         943.07
199   R0000200    OI00008899  O0003476     P00599         752.21
6549  R0000200    OI00008899  O0003476     P00599         752.21
317   R0000318    OI00014650  O0005699     P00278         246.23
6550  R0000318    OI00014650  O0005699     P00278         246.23
447   R0000448    OI00020604  O0007987     P01667         111.06
6513  R0000448    OI00020604  O0007987     P01667         111.06
475   R0000476    OI00021694  O0008415     P01223         211.42
6536  R0000476    OI00021694  O0008415     P01223         211.42

In [141]:
# ---------------------------------------------------------
# Convert Return Issue Log to DataFrame
# ---------------------------------------------------------

return_issue_log_df = pd.DataFrame(
    return_issue_log
)

print("Return issue log created successfully!")

print(
    "Total logged issues:",
    len(return_issue_log_df)
)

print("\nIssues by type:")

print(
    return_issue_log_df["issue_type"]
    .value_counts()
)

return_issue_log_df.head(10)

Return issue log created successfully!
Total logged issues: 500

Issues by type:
issue_type
business_rule_violation        100
reconciliation_error           100
temporal_consistency_error     100
invalid_category                75
referential_integrity_error     75
duplicate_record                50
Name: count, dtype: int64

,return_id,issue_type,column,original_value,injected_value
0,R0000933,business_rule_violation,return_quantity,1,2
1,R0006172,business_rule_violation,return_quantity,1,4
2,R0002667,business_rule_violation,return_quantity,1,3
3,R0002009,business_rule_violation,return_quantity,1,4
4,R0003290,business_rule_violation,return_quantity,3,4
5,R0003781,business_rule_violation,return_quantity,1,3
6,R0002114,business_rule_violation,return_quantity,1,4
7,R0004537,business_rule_violation,return_quantity,1,2
8,R0002852,business_rule_violation,return_quantity,1,2
9,R0005518,business_rule_violation,return_quantity,1,2

In [142]:
# ---------------------------------------------------------
# Verify Return Issue Counts
# ---------------------------------------------------------

expected_return_issue_counts = {
    "business_rule_violation": 100,
    "reconciliation_error": 100,
    "temporal_consistency_error": 100,
    "invalid_category": 75,
    "referential_integrity_error": 75,
    "duplicate_record": 50
}

actual_return_issue_counts = (
    return_issue_log_df["issue_type"]
    .value_counts()
    .to_dict()
)

for issue_type, expected_count in expected_return_issue_counts.items():

    actual_count = actual_return_issue_counts.get(
        issue_type,
        0
    )

    status = (
        "PASS"
        if actual_count == expected_count
        else "FAIL"
    )

    print(
        f"{issue_type}: "
        f"Expected={expected_count}, "
        f"Actual={actual_count} "
        f"[{status}]"
    )

business_rule_violation: Expected=100, Actual=100 [PASS]
reconciliation_error: Expected=100, Actual=100 [PASS]
temporal_consistency_error: Expected=100, Actual=100 [PASS]
invalid_category: Expected=75, Actual=75 [PASS]
referential_integrity_error: Expected=75, Actual=75 [PASS]
duplicate_record: Expected=50, Actual=50 [PASS]

In [143]:
# ---------------------------------------------------------
# Verify Return Issues by Type and Column
# ---------------------------------------------------------

return_issue_summary = (
    return_issue_log_df
    .groupby(
        ["issue_type", "column"]
    )
    .size()
    .reset_index(name="issue_count")
)

return_issue_summary

                    issue_type           column  issue_count
0      business_rule_violation  return_quantity          100
1             duplicate_record        return_id           50
2             invalid_category    return_reason           75
3         reconciliation_error    refund_amount          100
4  referential_integrity_error    order_item_id           75
5   temporal_consistency_error      return_date          100

In [144]:
# ---------------------------------------------------------
# Save Returns Dataset and Ground-Truth Issue Log
# ---------------------------------------------------------

# File paths
returns_file = (
    INCOMING_DIR / "returns.csv"
)

return_issue_log_file = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "return_issue_ground_truth.csv"
)

# Save dirty returns data
returns_dirty_df.to_csv(
    returns_file,
    index=False
)

# Save return issue ground truth
return_issue_log_df.to_csv(
    return_issue_log_file,
    index=False
)

print("Return files saved successfully!")

print("\nReturn source file:")
print(returns_file)

print("\nReturn issue ground-truth file:")
print(return_issue_log_file)

Return files saved successfully!

Return source file:
/Users/aryayogirajingale/Documents/DataTrust/data/incoming/returns.csv

Return issue ground-truth file:
/Users/aryayogirajingale/Documents/DataTrust/data/raw/return_issue_ground_truth.csv

In [145]:
# ---------------------------------------------------------
# Verify Saved Return Files
# ---------------------------------------------------------

print(
    "returns.csv exists:",
    returns_file.exists()
)

print(
    "Return issue log exists:",
    return_issue_log_file.exists()
)

# Read the saved source file back from disk
saved_returns = pd.read_csv(
    returns_file
)

print(
    "\nSaved return rows:",
    len(saved_returns)
)

print(
    "Saved return columns:",
    len(saved_returns.columns)
)

print(
    "Ground-truth issues:",
    len(return_issue_log_df)
)

print(
    "Duplicate return IDs:",
    saved_returns["return_id"].duplicated().sum()
)

print(
    "\nFile size:",
    f"{returns_file.stat().st_size / 1024 / 1024:.2f} MB"
)

returns.csv exists: True
Return issue log exists: True

Saved return rows: 6560
Saved return columns: 8
Ground-truth issues: 500
Duplicate return IDs: 50

File size: 0.43 MB

In [146]:
# ---------------------------------------------------------
# Final Stage 2 Audit - Load All Source Datasets
# ---------------------------------------------------------

# Load all six source datasets from disk
audit_customers = pd.read_csv(
    INCOMING_DIR / "customers.csv"
)

audit_products = pd.read_excel(
    INCOMING_DIR / "products.xlsx"
)

audit_orders = pd.read_csv(
    INCOMING_DIR / "orders.csv"
)

audit_order_items = pd.read_csv(
    INCOMING_DIR / "order_items.csv"
)

audit_payments = pd.read_csv(
    INCOMING_DIR / "payments.csv"
)

audit_returns = pd.read_csv(
    INCOMING_DIR / "returns.csv"
)

print("All source datasets loaded successfully!")

All source datasets loaded successfully!

In [147]:
# ---------------------------------------------------------
# Display Dataset Row and Column Counts
# ---------------------------------------------------------

dataset_audit = pd.DataFrame({
    "dataset": [
        "customers",
        "products",
        "orders",
        "order_items",
        "payments",
        "returns"
    ],
    "rows": [
        len(audit_customers),
        len(audit_products),
        len(audit_orders),
        len(audit_order_items),
        len(audit_payments),
        len(audit_returns)
    ],
    "columns": [
        len(audit_customers.columns),
        len(audit_products.columns),
        len(audit_orders.columns),
        len(audit_order_items.columns),
        len(audit_payments.columns),
        len(audit_returns.columns)
    ]
})

dataset_audit

       dataset    rows  columns
0    customers   50200       10
1     products    2010       10
2       orders  120100        9
3  order_items  307309        7
4     payments  120100        6
5      returns    6560        8

In [148]:
# ---------------------------------------------------------
# Calculate Total Source Data Volume
# ---------------------------------------------------------

total_source_rows = dataset_audit["rows"].sum()

print(
    "Total rows across all source datasets:",
    f"{total_source_rows:,}"
)

print(
    "Number of source datasets:",
    len(dataset_audit)
)

Total rows across all source datasets: 606,279
Number of source datasets: 6

In [149]:
# ---------------------------------------------------------
# Final Stage 2 Audit - Ground-Truth Issue Counts
# ---------------------------------------------------------

issue_audit = pd.DataFrame({
    "dataset": [
        "customers",
        "products",
        "orders",
        "order_items",
        "payments",
        "returns"
    ],
    "injected_issues": [
        len(customer_issue_log_df),
        len(product_issue_log_df),
        len(order_issue_log_df),
        len(order_item_issue_log_df),
        len(payment_issue_log_df),
        len(return_issue_log_df)
    ]
})

print("Ground-truth issue audit:")
display(issue_audit)

total_injected_issues = issue_audit[
    "injected_issues"
].sum()

print(
    "\nTotal intentionally injected issues:",
    f"{total_injected_issues:,}"
)

Ground-truth issue audit:

       dataset  injected_issues
0    customers             1400
1     products               70
2       orders             1000
3  order_items              950
4     payments              650
5      returns              500

Total intentionally injected issues: 4,570

In [150]:
# ---------------------------------------------------------
# Calculate Overall Known Issue Rate
# ---------------------------------------------------------

total_source_rows = dataset_audit[
    "rows"
].sum()

overall_issue_rate = (
    total_injected_issues
    / total_source_rows
) * 100

print(
    "Total source rows:",
    f"{total_source_rows:,}"
)

print(
    "Known injected issues:",
    f"{total_injected_issues:,}"
)

print(
    "Known issue rate:",
    f"{overall_issue_rate:.3f}%"
)

Total source rows: 606,279
Known injected issues: 4,570
Known issue rate: 0.754%

In [151]:
# ---------------------------------------------------------
# Relationship Audit 1: Customers -> Orders
# ---------------------------------------------------------

valid_customer_ids = set(
    audit_customers["customer_id"]
    .dropna()
)

# Orders where customer_id is missing
orders_missing_customer = audit_orders[
    audit_orders["customer_id"].isna()
]

# Orders where customer_id exists but is not found
# in the customer table
orders_orphan_customer = audit_orders[
    audit_orders["customer_id"].notna()
    &
    ~audit_orders["customer_id"].isin(
        valid_customer_ids
    )
]

print("CUSTOMERS -> ORDERS RELATIONSHIP")
print("--------------------------------")

print(
    "Orders with missing customer_id:",
    len(orders_missing_customer)
)

print(
    "Orders with nonexistent customer_id:",
    len(orders_orphan_customer)
)

print(
    "Total customer-reference problems:",
    len(orders_missing_customer)
    + len(orders_orphan_customer)
)

CUSTOMERS -> ORDERS RELATIONSHIP
--------------------------------
Orders with missing customer_id: 300
Orders with nonexistent customer_id: 200
Total customer-reference problems: 500

In [152]:
# ---------------------------------------------------------
# Show Example Customer Reference Problems
# ---------------------------------------------------------

print("Example orders with missing customer IDs:")

display(
    orders_missing_customer[
        [
            "order_id",
            "customer_id",
            "order_date",
            "sales_channel"
        ]
    ].head()
)

print("Example orders with nonexistent customer IDs:")

display(
    orders_orphan_customer[
        [
            "order_id",
            "customer_id",
            "order_date",
            "sales_channel"
        ]
    ].head()
)

Example orders with missing customer IDs:

      order_id customer_id  order_date   sales_channel
404   O0000405         NaN  2025-03-10         Website
419   O0000420         NaN  2023-02-15  Physical Store
847   O0000848         NaN  2024-11-20         Website
1084  O0001085         NaN  2024-04-11         Website
1350  O0001351         NaN  2024-01-30         Website

Example orders with nonexistent customer IDs:

     order_id customer_id  order_date sales_channel
93   O0000094     C900187  2024-06-13    Mobile App
135  O0000136     C900077  2025-12-14       Website
217  O0000218     C900148  2024-12-27    Mobile App
348  O0000349     C900025  2025-04-10    Mobile App
584  O0000585     C900195  2025-09-05    Mobile App

In [153]:
# ---------------------------------------------------------
# Relationship Audit 2: Orders -> Order Items
# ---------------------------------------------------------

valid_order_ids = set(
    audit_orders["order_id"]
    .dropna()
)

# Order items with missing order_id
order_items_missing_order = audit_order_items[
    audit_order_items["order_id"].isna()
]

# Order items whose order_id does not exist in orders
order_items_orphan_order = audit_order_items[
    audit_order_items["order_id"].notna()
    &
    ~audit_order_items["order_id"].isin(
        valid_order_ids
    )
]

print("ORDERS -> ORDER ITEMS RELATIONSHIP")
print("----------------------------------")

print(
    "Order items with missing order_id:",
    len(order_items_missing_order)
)

print(
    "Order items with nonexistent order_id:",
    len(order_items_orphan_order)
)

print(
    "Total order-reference problems:",
    len(order_items_missing_order)
    + len(order_items_orphan_order)
)

ORDERS -> ORDER ITEMS RELATIONSHIP
----------------------------------
Order items with missing order_id: 0
Order items with nonexistent order_id: 0
Total order-reference problems: 0

In [154]:
# ---------------------------------------------------------
# Check Order Item Coverage
# ---------------------------------------------------------

print(
    "Unique orders in orders table:",
    audit_orders["order_id"].nunique()
)

print(
    "Unique orders represented in order_items:",
    audit_order_items["order_id"].nunique()
)

orders_without_items = (
    set(audit_orders["order_id"].dropna())
    -
    set(audit_order_items["order_id"].dropna())
)

print(
    "Orders without any order items:",
    len(orders_without_items)
)

Unique orders in orders table: 120000
Unique orders represented in order_items: 120000
Orders without any order items: 0

In [155]:
# ---------------------------------------------------------
# Relationship Audit 3: Products -> Order Items
# ---------------------------------------------------------

valid_product_ids = set(
    audit_products["product_id"]
    .dropna()
)

# Order items with missing product_id
order_items_missing_product = audit_order_items[
    audit_order_items["product_id"].isna()
]

# Order items whose product_id does not exist in products
order_items_orphan_product = audit_order_items[
    audit_order_items["product_id"].notna()
    &
    ~audit_order_items["product_id"].isin(
        valid_product_ids
    )
]

print("PRODUCTS -> ORDER ITEMS RELATIONSHIP")
print("------------------------------------")

print(
    "Order items with missing product_id:",
    len(order_items_missing_product)
)

print(
    "Order items with nonexistent product_id:",
    len(order_items_orphan_product)
)

print(
    "Total product-reference problems:",
    len(order_items_missing_product)
    + len(order_items_orphan_product)
)

PRODUCTS -> ORDER ITEMS RELATIONSHIP
------------------------------------
Order items with missing product_id: 0
Order items with nonexistent product_id: 200
Total product-reference problems: 200

In [156]:
# ---------------------------------------------------------
# Show Nonexistent Product References
# ---------------------------------------------------------

print(
    "Unique nonexistent product IDs:",
    order_items_orphan_product[
        "product_id"
    ].nunique()
)

display(
    order_items_orphan_product[
        [
            "order_item_id",
            "order_id",
            "product_id",
            "quantity",
            "unit_price"
        ]
    ].head(10)
)

Unique nonexistent product IDs: 200

      order_item_id  order_id product_id  quantity  unit_price
1555     OI00001556  O0000597     P90074         4      213.54
3925     OI00003926  O0001538     P90036         2      163.69
6274     OI00006275  O0002429     P90115         1      789.71
8139     OI00008140  O0003178     P90192         1      230.23
9260     OI00009261  O0003615     P90130         1      289.69
12686    OI00012687  O0004935     P90145         1      866.31
14277    OI00014278  O0005546     P90165         1      847.07
15537    OI00015538  O0006066     P90179         1      290.73
24833    OI00024834  O0009661     P90100         1      254.92
29464    OI00029465  O0011459     P90032         1       90.96

In [157]:
# ---------------------------------------------------------
# Relationship Audit 4: Orders -> Payments
# ---------------------------------------------------------

valid_order_ids = set(
    audit_orders["order_id"]
    .dropna()
)

# Payments with missing order_id
payments_missing_order = audit_payments[
    audit_payments["order_id"].isna()
]

# Payments whose order_id does not exist in orders
payments_orphan_order = audit_payments[
    audit_payments["order_id"].notna()
    &
    ~audit_payments["order_id"].isin(
        valid_order_ids
    )
]

print("ORDERS -> PAYMENTS RELATIONSHIP")
print("-------------------------------")

print(
    "Payments with missing order_id:",
    len(payments_missing_order)
)

print(
    "Payments with nonexistent order_id:",
    len(payments_orphan_order)
)

print(
    "Total order-reference problems:",
    len(payments_missing_order)
    + len(payments_orphan_order)
)

ORDERS -> PAYMENTS RELATIONSHIP
-------------------------------
Payments with missing order_id: 0
Payments with nonexistent order_id: 150
Total order-reference problems: 150

In [158]:
# ---------------------------------------------------------
# Show Nonexistent Payment Order References
# ---------------------------------------------------------

print(
    "Unique nonexistent order IDs:",
    payments_orphan_order[
        "order_id"
    ].nunique()
)

display(
    payments_orphan_order[
        [
            "payment_id",
            "order_id",
            "payment_date",
            "payment_method",
            "payment_status",
            "payment_amount"
        ]
    ].head(10)
)

Unique nonexistent order IDs: 150

,payment_id,order_id,payment_date,payment_method,payment_status,payment_amount
214,PAY0000215,O9000056,2025-12-20,Digital Wallet,Successful,2066.69
410,PAY0000411,O9000073,2025-05-21,Credit Card,Successful,572.57
537,PAY0000538,O9000053,2025-11-23,Debit Card,Successful,1204.44
662,PAY0000663,O9000013,2024-10-21,Credit Card,Successful,2915.00
2088,PAY0002089,O9000054,2025-12-15,Credit Card,Successful,678.00
2422,PAY0002423,O9000029,2024-11-12,Credit Card,Successful,302.32
2614,PAY0002615,O9000085,2025-10-18,Debit Card,Failed,931.66
3885,PAY0003886,O9000039,2025-06-16,Credit Card,Successful,87.92
4262,PAY0004263,O9000090,2023-04-13,Digital Wallet,Successful,4033.94
6025,PAY0006026,O9000078,2024-06-01,Debit Card,Failed,433.07

In [159]:
# ---------------------------------------------------------
# Relationship Audit 5: Order Items -> Returns
# ---------------------------------------------------------

valid_order_item_ids = set(
    audit_order_items["order_item_id"]
    .dropna()
)

# Returns with missing order_item_id
returns_missing_order_item = audit_returns[
    audit_returns["order_item_id"].isna()
]

# Returns whose order_item_id does not exist
returns_orphan_order_item = audit_returns[
    audit_returns["order_item_id"].notna()
    &
    ~audit_returns["order_item_id"].isin(
        valid_order_item_ids
    )
]

print("ORDER ITEMS -> RETURNS RELATIONSHIP")
print("-----------------------------------")

print(
    "Returns with missing order_item_id:",
    len(returns_missing_order_item)
)

print(
    "Returns with nonexistent order_item_id:",
    len(returns_orphan_order_item)
)

print(
    "Total order-item reference problems:",
    len(returns_missing_order_item)
    + len(returns_orphan_order_item)
)

ORDER ITEMS -> RETURNS RELATIONSHIP
-----------------------------------
Returns with missing order_item_id: 0
Returns with nonexistent order_item_id: 75
Total order-item reference problems: 75

In [160]:
# ---------------------------------------------------------
# Show Nonexistent Return Order-Item References
# ---------------------------------------------------------

print(
    "Unique nonexistent order-item IDs:",
    returns_orphan_order_item[
        "order_item_id"
    ].nunique()
)

display(
    returns_orphan_order_item[
        [
            "return_id",
            "order_item_id",
            "order_id",
            "product_id",
            "return_quantity",
            "refund_amount"
        ]
    ].head(10)
)

Unique nonexistent order-item IDs: 75

,return_id,order_item_id,order_id,product_id,return_quantity,refund_amount
8,R0000009,OI90000040,O0000106,P01085,4,261.75
123,R0000124,OI90000023,O0001982,P01230,2,822.66
144,R0000145,OI90000008,O0002405,P01119,1,99.58
180,R0000181,OI90000046,O0003253,P01399,1,800.51
211,R0000212,OI90000016,O0003738,P00744,1,87.65
279,R0000280,OI90000048,O0005012,P01625,1,224.04
343,R0000344,OI90000013,O0006041,P01172,1,233.81
482,R0000483,OI90000021,O0008657,P00594,1,584.34
548,R0000549,OI90000059,O0009973,P00946,2,663.82
549,R0000550,OI90000066,O0009974,P01528,3,198.03

In [161]:
# ---------------------------------------------------------
# Relationship Audit 6:
# Return Order/Product Consistency
# ---------------------------------------------------------

# Keep only returns whose order_item_id actually exists
valid_return_refs = audit_returns[
    audit_returns["order_item_id"].isin(
        valid_order_item_ids
    )
].copy()

# Bring in the expected order_id and product_id
return_consistency_check = valid_return_refs.merge(
    audit_order_items[
        [
            "order_item_id",
            "order_id",
            "product_id"
        ]
    ].drop_duplicates(
        subset=["order_item_id"]
    ),
    on="order_item_id",
    how="left",
    suffixes=("_return", "_expected")
)

# Check whether order_id matches
order_mismatches = return_consistency_check[
    return_consistency_check["order_id_return"]
    != return_consistency_check["order_id_expected"]
]

# Check whether product_id matches
product_mismatches = return_consistency_check[
    return_consistency_check["product_id_return"]
    != return_consistency_check["product_id_expected"]
]

print("RETURN INTERNAL RELATIONSHIP CONSISTENCY")
print("----------------------------------------")

print(
    "Return/order mismatches:",
    len(order_mismatches)
)

print(
    "Return/product mismatches:",
    len(product_mismatches)
)

RETURN INTERNAL RELATIONSHIP CONSISTENCY
----------------------------------------
Return/order mismatches: 0
Return/product mismatches: 4

In [162]:
# ---------------------------------------------------------
# Verify Return Consistency Audit Coverage
# ---------------------------------------------------------

print(
    "Total return rows:",
    len(audit_returns)
)

print(
    "Rows excluded due to invalid order_item_id:",
    len(returns_orphan_order_item)
)

print(
    "Rows checked for consistency:",
    len(return_consistency_check)
)

print(
    "Order mismatches:",
    len(order_mismatches)
)

print(
    "Product mismatches:",
    len(product_mismatches)
)

Total return rows: 6560
Rows excluded due to invalid order_item_id: 75
Rows checked for consistency: 6485
Order mismatches: 0
Product mismatches: 4

In [163]:
# ---------------------------------------------------------
# Financial Reconciliation Audit 1:
# Order Totals -> Payments
# ---------------------------------------------------------

# Recalculate expected order totals from CLEAN order-item ground truth
expected_order_totals = (
    order_items_ground_truth_df
    .assign(
        expected_net_sales=lambda df:
            df["quantity"]
            * df["unit_price"]
            * (1 - df["discount_pct"])
    )
    .groupby(
        "order_id",
        as_index=False
    )["expected_net_sales"]
    .sum()
)

expected_order_totals[
    "expected_net_sales"
] = expected_order_totals[
    "expected_net_sales"
].round(2)

print(
    "Expected order totals calculated:",
    len(expected_order_totals)
)

Expected order totals calculated: 120000

In [164]:
# ---------------------------------------------------------
# Prepare Payments for Reconciliation
# ---------------------------------------------------------

# Remove orphan payments
valid_payments_for_reconciliation = audit_payments[
    audit_payments["order_id"].isin(
        expected_order_totals["order_id"]
    )
].copy()

# Remove ALL occurrences of duplicated payment IDs
# so duplicate problems remain a separate quality test
duplicate_payment_ids = set(
    audit_payments.loc[
        audit_payments["payment_id"].duplicated(
            keep=False
        ),
        "payment_id"
    ]
)

valid_payments_for_reconciliation = (
    valid_payments_for_reconciliation[
        ~valid_payments_for_reconciliation[
            "payment_id"
        ].isin(duplicate_payment_ids)
    ]
    .copy()
)

print(
    "Payments eligible for amount reconciliation:",
    len(valid_payments_for_reconciliation)
)

print(
    "Duplicate payment IDs excluded:",
    len(duplicate_payment_ids)
)

print(
    "Orphan payments excluded:",
    len(payments_orphan_order)
)

Payments eligible for amount reconciliation: 119750
Duplicate payment IDs excluded: 100
Orphan payments excluded: 150

In [165]:
# ---------------------------------------------------------
# Detect Payment Amount Reconciliation Errors
# ---------------------------------------------------------

payment_reconciliation = (
    valid_payments_for_reconciliation.merge(
        expected_order_totals,
        on="order_id",
        how="inner"
    )
)

payment_reconciliation[
    "amount_difference"
] = (
    payment_reconciliation["payment_amount"]
    - payment_reconciliation["expected_net_sales"]
).round(2)

payment_amount_mismatches = payment_reconciliation[
    payment_reconciliation[
        "amount_difference"
    ].abs() > 0.01
]

print("PAYMENT RECONCILIATION RESULTS")
print("------------------------------")

print(
    "Payments checked:",
    len(payment_reconciliation)
)

print(
    "Payment amount mismatches:",
    len(payment_amount_mismatches)
)

display(
    payment_amount_mismatches[
        [
            "payment_id",
            "order_id",
            "payment_amount",
            "expected_net_sales",
            "amount_difference"
        ]
    ].head(10)
)

PAYMENT RECONCILIATION RESULTS
------------------------------
Payments checked: 119750
Payment amount mismatches: 200

,payment_id,order_id,payment_amount,expected_net_sales,amount_difference
97,PAY0000098,O0000098,2149.49,3070.70,-921.21
753,PAY0000758,O0000758,2822.32,3527.90,-705.58
1353,PAY0001358,O0001358,253.68,362.40,-108.72
2935,PAY0002944,O0002944,733.58,916.97,-183.39
4404,PAY0004417,O0004417,8837.95,8034.50,803.45
4461,PAY0004474,O0004474,2461.88,2051.57,410.31
4667,PAY0004680,O0004680,2274.42,2067.65,206.77
4678,PAY0004692,O0004692,145.97,208.53,-62.56
4715,PAY0004729,O0004729,1522.35,1383.95,138.40
4765,PAY0004779,O0004779,745.81,932.26,-186.45

In [166]:
# ---------------------------------------------------------
# Financial Reconciliation Audit 2:
# Returns -> Expected Refund Amount
# ---------------------------------------------------------

# Original transaction information
return_transaction_lookup = (
    order_items_ground_truth_df[
        [
            "order_item_id",
            "unit_price",
            "discount_pct",
            "quantity"
        ]
    ]
    .copy()
)

# Identify duplicated return IDs
duplicate_return_ids = set(
    audit_returns.loc[
        audit_returns["return_id"].duplicated(
            keep=False
        ),
        "return_id"
    ]
)

print(
    "Duplicate return IDs identified:",
    len(duplicate_return_ids)
)

Duplicate return IDs identified: 50

In [167]:
# ---------------------------------------------------------
# Prepare Returns for Refund Reconciliation
# ---------------------------------------------------------

returns_for_reconciliation = audit_returns[
    ~audit_returns["return_id"].isin(
        duplicate_return_ids
    )
].copy()

returns_for_reconciliation = (
    returns_for_reconciliation.merge(
        return_transaction_lookup,
        on="order_item_id",
        how="inner"
    )
)

# Exclude records where return quantity exceeds
# the originally purchased quantity
returns_for_reconciliation = (
    returns_for_reconciliation[
        (
            returns_for_reconciliation["return_quantity"] > 0
        )
        &
        (
            returns_for_reconciliation["return_quantity"]
            <= returns_for_reconciliation["quantity"]
        )
    ]
    .copy()
)

print(
    "Returns eligible for refund reconciliation:",
    len(returns_for_reconciliation)
)

print(
    "Duplicate return IDs excluded:",
    len(duplicate_return_ids)
)

print(
    "Orphan order-item references excluded:",
    len(returns_orphan_order_item)
)

Returns eligible for refund reconciliation: 6285
Duplicate return IDs excluded: 50
Orphan order-item references excluded: 75

In [168]:
# ---------------------------------------------------------
# Calculate Expected Refund Amount
# ---------------------------------------------------------

returns_for_reconciliation[
    "expected_refund_amount"
] = (
    returns_for_reconciliation["return_quantity"]
    * returns_for_reconciliation["unit_price"]
    * (
        1
        - returns_for_reconciliation["discount_pct"]
    )
).round(2)

returns_for_reconciliation[
    "refund_difference"
] = (
    returns_for_reconciliation["refund_amount"]
    - returns_for_reconciliation["expected_refund_amount"]
).round(2)

refund_amount_mismatches = (
    returns_for_reconciliation[
        returns_for_reconciliation[
            "refund_difference"
        ].abs() > 0.01
    ]
)

print("RETURN REFUND RECONCILIATION RESULTS")
print("------------------------------------")

print(
    "Returns checked:",
    len(returns_for_reconciliation)
)

print(
    "Refund amount mismatches:",
    len(refund_amount_mismatches)
)

display(
    refund_amount_mismatches[
        [
            "return_id",
            "order_item_id",
            "return_quantity",
            "unit_price",
            "discount_pct",
            "refund_amount",
            "expected_refund_amount",
            "refund_difference"
        ]
    ].head(10)
)

RETURN REFUND RECONCILIATION RESULTS
------------------------------------
Returns checked: 6285
Refund amount mismatches: 100

,return_id,order_item_id,return_quantity,unit_price,discount_pct,refund_amount,expected_refund_amount,refund_difference
50,R0000053,OI00002250,1,307.60,0.00,153.80,307.60,-153.80
87,R0000090,OI00003723,1,877.56,0.10,1184.70,789.80,394.90
96,R0000099,OI00003931,1,274.20,0.00,356.46,274.20,82.26
112,R0000115,OI00004881,1,840.37,0.00,1260.56,840.37,420.19
260,R0000268,OI00012307,1,593.63,0.30,207.77,415.54,-207.77
348,R0000359,OI00016348,1,811.85,0.10,876.80,730.67,146.13
377,R0000388,OI00017354,2,128.66,0.00,385.98,257.32,128.66
448,R0000460,OI00021177,1,40.32,0.05,45.96,38.30,7.66
463,R0000475,OI00021695,1,248.77,0.20,159.22,199.02,-39.80
481,R0000495,OI00023169,1,188.74,0.00,94.37,188.74,-94.37

In [169]:
# ---------------------------------------------------------
# Temporal Audit 1:
# Orders Before Customer Signup
# ---------------------------------------------------------

# Use clean customer master to obtain the expected signup date
customer_signup_lookup = (
    customers_ground_truth_df[
        [
            "customer_id",
            "signup_date"
        ]
    ]
    .copy()
)

# Start from orders with valid customer IDs
orders_for_temporal_check = audit_orders[
    audit_orders["customer_id"].isin(
        customer_signup_lookup["customer_id"]
    )
].copy()

# Remove duplicate order IDs so duplicate records
# remain a separate quality issue
orders_for_temporal_check = (
    orders_for_temporal_check
    .drop_duplicates(
        subset=["order_id"],
        keep="first"
    )
)

# Join customer signup dates
orders_for_temporal_check = (
    orders_for_temporal_check.merge(
        customer_signup_lookup,
        on="customer_id",
        how="left"
    )
)

# Convert to datetime
orders_for_temporal_check["order_date"] = pd.to_datetime(
    orders_for_temporal_check["order_date"]
)

orders_for_temporal_check["signup_date"] = pd.to_datetime(
    orders_for_temporal_check["signup_date"]
)

print(
    "Orders eligible for temporal check:",
    len(orders_for_temporal_check)
)

Orders eligible for temporal check: 119500

In [170]:
# ---------------------------------------------------------
# Detect Orders Before Customer Signup
# ---------------------------------------------------------

orders_before_signup = orders_for_temporal_check[
    orders_for_temporal_check["order_date"]
    <
    orders_for_temporal_check["signup_date"]
].copy()

orders_before_signup[
    "days_before_signup"
] = (
    orders_before_signup["signup_date"]
    - orders_before_signup["order_date"]
).dt.days

print("ORDER TEMPORAL CONSISTENCY RESULTS")
print("----------------------------------")

print(
    "Orders before customer signup:",
    len(orders_before_signup)
)

display(
    orders_before_signup[
        [
            "order_id",
            "customer_id",
            "signup_date",
            "order_date",
            "days_before_signup"
        ]
    ].head(10)
)

ORDER TEMPORAL CONSISTENCY RESULTS
----------------------------------
Orders before customer signup: 150

      order_id customer_id signup_date order_date  days_before_signup
173   O0000176     C003231  2025-01-30 2025-01-26                   4
1098  O0001108     C044064  2025-12-03 2025-10-18                  46
1220  O0001230     C011792  2023-02-14 2023-01-06                  39
1253  O0001263     C024353  2022-06-09 2022-05-28                  12
2193  O0002208     C003807  2022-02-23 2021-11-25                  90
2283  O0002298     C045219  2023-02-21 2023-02-15                   6
2824  O0002842     C037993  2024-06-05 2024-05-18                  18
3647  O0003672     C005918  2023-08-07 2023-07-19                  19
4231  O0004259     C048478  2024-08-26 2024-07-22                  35
4681  O0004709     C031575  2021-01-18 2021-01-16                   2

In [171]:
# ---------------------------------------------------------
# Temporal Audit 2:
# Payments Before Orders
# ---------------------------------------------------------

# Create clean order-date lookup
order_date_lookup_df = (
    orders_ground_truth_df[
        [
            "order_id",
            "order_date"
        ]
    ]
    .copy()
)

# Exclude payments whose order_id does not exist
payments_for_temporal_check = audit_payments[
    audit_payments["order_id"].isin(
        order_date_lookup_df["order_id"]
    )
].copy()

# Remove duplicate payment IDs so duplicates
# remain a separate quality issue
payments_for_temporal_check = (
    payments_for_temporal_check[
        ~payments_for_temporal_check[
            "payment_id"
        ].isin(duplicate_payment_ids)
    ]
    .copy()
)

# Bring in original order date
payments_for_temporal_check = (
    payments_for_temporal_check.merge(
        order_date_lookup_df,
        on="order_id",
        how="left"
    )
)

# Convert dates
payments_for_temporal_check["payment_date"] = pd.to_datetime(
    payments_for_temporal_check["payment_date"]
)

payments_for_temporal_check["order_date"] = pd.to_datetime(
    payments_for_temporal_check["order_date"]
)

print(
    "Payments eligible for temporal check:",
    len(payments_for_temporal_check)
)

Payments eligible for temporal check: 119750

In [172]:
# ---------------------------------------------------------
# Detect Payments Before Order Date
# ---------------------------------------------------------

payments_before_order = payments_for_temporal_check[
    payments_for_temporal_check["payment_date"]
    <
    payments_for_temporal_check["order_date"]
].copy()

payments_before_order[
    "days_before_order"
] = (
    payments_before_order["order_date"]
    - payments_before_order["payment_date"]
).dt.days

print("PAYMENT TEMPORAL CONSISTENCY RESULTS")
print("------------------------------------")

print(
    "Payments before order date:",
    len(payments_before_order)
)

display(
    payments_before_order[
        [
            "payment_id",
            "order_id",
            "order_date",
            "payment_date",
            "days_before_order"
        ]
    ].head(10)
)

PAYMENT TEMPORAL CONSISTENCY RESULTS
------------------------------------
Payments before order date: 100

       payment_id  order_id order_date payment_date  days_before_order
2331   PAY0002337  O0002337 2024-05-28   2024-05-26                  2
3750   PAY0003760  O0003760 2025-11-05   2025-11-02                  3
4184   PAY0004196  O0004196 2024-09-17   2024-09-16                  1
5173   PAY0005188  O0005188 2024-04-19   2024-04-17                  2
8544   PAY0008569  O0008569 2025-03-21   2025-03-16                  5
9171   PAY0009197  O0009197 2025-11-28   2025-11-21                  7
9334   PAY0009360  O0009360 2024-12-28   2024-12-27                  1
11447  PAY0011476  O0011476 2025-12-04   2025-12-02                  2
12278  PAY0012307  O0012307 2025-12-26   2025-12-19                  7
12597  PAY0012626  O0012626 2025-04-03   2025-03-30                  4

In [173]:
# ---------------------------------------------------------
# Temporal Audit 3:
# Returns Outside 30-Day Window
# ---------------------------------------------------------

# Clean order-date lookup
return_order_date_lookup = (
    orders_ground_truth_df[
        [
            "order_id",
            "order_date"
        ]
    ]
    .copy()
)

# Start with returns whose order_id exists
returns_for_temporal_check = audit_returns[
    audit_returns["order_id"].isin(
        return_order_date_lookup["order_id"]
    )
].copy()

# Remove duplicate return IDs
# Duplicate records are handled by a separate quality rule
returns_for_temporal_check = (
    returns_for_temporal_check[
        ~returns_for_temporal_check[
            "return_id"
        ].isin(duplicate_return_ids)
    ]
    .copy()
)

# Bring in the original order date
returns_for_temporal_check = (
    returns_for_temporal_check.merge(
        return_order_date_lookup,
        on="order_id",
        how="left"
    )
)

# Convert dates
returns_for_temporal_check["return_date"] = pd.to_datetime(
    returns_for_temporal_check["return_date"]
)

returns_for_temporal_check["order_date"] = pd.to_datetime(
    returns_for_temporal_check["order_date"]
)

# Calculate number of days between order and return
returns_for_temporal_check[
    "days_to_return"
] = (
    returns_for_temporal_check["return_date"]
    - returns_for_temporal_check["order_date"]
).dt.days

print(
    "Returns eligible for temporal check:",
    len(returns_for_temporal_check)
)

Returns eligible for temporal check: 6460

In [174]:
# ---------------------------------------------------------
# Detect Returns Outside Allowed Window
# ---------------------------------------------------------

returns_outside_window = returns_for_temporal_check[
    (
        returns_for_temporal_check["days_to_return"]
        < MIN_RETURN_DAYS
    )
    |
    (
        returns_for_temporal_check["days_to_return"]
        > MAX_RETURN_DAYS
    )
].copy()

print("RETURN TEMPORAL CONSISTENCY RESULTS")
print("-----------------------------------")

print(
    "Returns outside allowed window:",
    len(returns_outside_window)
)

print(
    "Minimum days among invalid returns:",
    returns_outside_window[
        "days_to_return"
    ].min()
)

print(
    "Maximum days among invalid returns:",
    returns_outside_window[
        "days_to_return"
    ].max()
)

display(
    returns_outside_window[
        [
            "return_id",
            "order_id",
            "order_date",
            "return_date",
            "days_to_return"
        ]
    ].head(10)
)

RETURN TEMPORAL CONSISTENCY RESULTS
-----------------------------------
Returns outside allowed window: 100
Minimum days among invalid returns: 31
Maximum days among invalid returns: 89

    return_id  order_id order_date return_date  days_to_return
59   R0000061  O0000940 2025-04-27  2025-07-03              67
286  R0000289  O0005075 2023-11-27  2024-02-02              67
346  R0000350  O0006212 2024-06-23  2024-09-03              72
397  R0000401  O0007068 2023-12-28  2024-03-05              68
444  R0000449  O0007987 2025-08-17  2025-10-12              56
555  R0000563  O0010279 2025-08-05  2025-09-16              42
611  R0000619  O0011636 2025-09-13  2025-10-16              33
640  R0000648  O0012439 2025-01-19  2025-04-01              72
694  R0000702  O0013279 2024-05-28  2024-07-19              52
813  R0000822  O0015151 2025-07-27  2025-10-24              89

In [175]:
# ---------------------------------------------------------
# Final Stage 2 Audit:
# Primary Identifier Uniqueness
# ---------------------------------------------------------

uniqueness_checks = {
    "customers": (
        audit_customers,
        "customer_id"
    ),
    "products": (
        audit_products,
        "product_id"
    ),
    "orders": (
        audit_orders,
        "order_id"
    ),
    "order_items": (
        audit_order_items,
        "order_item_id"
    ),
    "payments": (
        audit_payments,
        "payment_id"
    ),
    "returns": (
        audit_returns,
        "return_id"
    )
}

uniqueness_results = []

for dataset_name, (df, id_column) in uniqueness_checks.items():

    duplicate_rows = df[
        id_column
    ].duplicated().sum()

    duplicate_ids = df.loc[
        df[id_column].duplicated(
            keep=False
        ),
        id_column
    ].nunique()

    uniqueness_results.append({
        "dataset": dataset_name,
        "id_column": id_column,
        "total_rows": len(df),
        "unique_ids": df[id_column].nunique(),
        "duplicate_rows": duplicate_rows,
        "duplicate_ids": duplicate_ids
    })


uniqueness_audit_df = pd.DataFrame(
    uniqueness_results
)

display(uniqueness_audit_df)

,dataset,id_column,total_rows,unique_ids,duplicate_rows,duplicate_ids
0,customers,customer_id,50200,50000,200,200
1,products,product_id,2010,2000,10,10
2,orders,order_id,120100,120000,100,100
3,order_items,order_item_id,307309,307159,150,150
4,payments,payment_id,120100,120000,100,100
5,returns,return_id,6560,6510,50,50

In [176]:
# ---------------------------------------------------------
# Verify Expected Duplicate Counts
# ---------------------------------------------------------

expected_duplicate_ids = {
    "customers": 200,
    "products": 10,
    "orders": 100,
    "order_items": 150,
    "payments": 100,
    "returns": 50
}

print("UNIQUENESS AUDIT RESULTS")
print("------------------------")

all_passed = True

for _, row in uniqueness_audit_df.iterrows():

    dataset = row["dataset"]

    expected = expected_duplicate_ids[
        dataset
    ]

    actual = int(
        row["duplicate_ids"]
    )

    status = (
        "PASS"
        if actual == expected
        else "FAIL"
    )

    if status == "FAIL":
        all_passed = False

    print(
        f"{dataset:<12} "
        f"Expected={expected:<4} "
        f"Actual={actual:<4} "
        f"[{status}]"
    )

print()

if all_passed:
    print(
        "PASS - All duplicate counts match ground truth."
    )
else:
    print(
        "FAIL - One or more duplicate counts need investigation."
    )

UNIQUENESS AUDIT RESULTS
------------------------
customers    Expected=200  Actual=200  [PASS]
products     Expected=10   Actual=10   [PASS]
orders       Expected=100  Actual=100  [PASS]
order_items  Expected=150  Actual=150  [PASS]
payments     Expected=100  Actual=100  [PASS]
returns      Expected=50   Actual=50   [PASS]

PASS - All duplicate counts match ground truth.

In [179]:
# ---------------------------------------------------------
# Final Stage 2 Audit:
# Missing Values Across All Datasets
# ---------------------------------------------------------

datasets = {
    "customers": audit_customers,
    "products": audit_products,
    "orders": audit_orders,
    "order_items": audit_order_items,
    "payments": audit_payments,
    "returns": audit_returns
}

missing_results = []

for dataset_name, df_data in datasets.items():

    for column in df_data.columns:

        missing_count = df_data[column].isna().sum()

        if missing_count > 0:

            missing_results.append({
                "dataset": dataset_name,
                "column": column,
                "missing_count": int(missing_count),
                "missing_pct": round(
                    (missing_count / len(df_data)) * 100,
                    3
                )
            })

missing_audit_df = pd.DataFrame(
    missing_results
)

print("MISSING VALUE AUDIT")
print("-------------------")

display(missing_audit_df)

MISSING VALUE AUDIT
-------------------

     dataset         column  missing_count  missing_pct
0  customers         region            500        0.996
1   products    subcategory             20        0.995
2     orders    customer_id            300        0.250
3    returns  return_reason             17        0.259

In [180]:
# ---------------------------------------------------------
# Summarize Missing Values
# ---------------------------------------------------------

total_missing_values = (
    missing_audit_df[
        "missing_count"
    ].sum()
)

print(
    "Total missing values detected:",
    f"{total_missing_values:,}"
)

print(
    "Columns containing missing values:",
    len(missing_audit_df)
)

Total missing values detected: 837
Columns containing missing values: 4

In [181]:
# ---------------------------------------------------------
# Domain Validity Audit 1:
# Invalid Sales Channels
# ---------------------------------------------------------

VALID_SALES_CHANNELS = [
    "Website",
    "Mobile App",
    "Physical Store"
]

invalid_sales_channels = audit_orders[
    audit_orders["sales_channel"].notna()
    &
    ~audit_orders["sales_channel"].isin(
        VALID_SALES_CHANNELS
    )
]

print("SALES CHANNEL VALIDITY RESULTS")
print("------------------------------")

print(
    "Invalid sales-channel records:",
    len(invalid_sales_channels)
)

print("\nInvalid values found:")

print(
    invalid_sales_channels[
        "sales_channel"
    ].value_counts()
)

SALES CHANNEL VALIDITY RESULTS
------------------------------
Invalid sales-channel records: 100

Invalid values found:
sales_channel
Phone Order     32
Unknown         26
Social Media    26
Marketplace     16
Name: count, dtype: int64

In [182]:
# ---------------------------------------------------------
# Show Invalid Sales Channel Examples
# ---------------------------------------------------------

display(
    invalid_sales_channels[
        [
            "order_id",
            "customer_id",
            "order_date",
            "sales_channel",
            "order_status"
        ]
    ].head(10)
)

      order_id customer_id  order_date sales_channel order_status
187   O0000188     C013559  2025-06-10       Unknown    Completed
481   O0000482     C036773  2025-03-04   Phone Order    Completed
735   O0000736     C023987  2025-11-04   Marketplace    Completed
2517  O0002518     C001121  2023-01-22   Phone Order    Completed
3930  O0003931     C043578  2025-01-12   Marketplace    Completed
4721  O0004722     C020445  2023-02-17   Phone Order    Completed
5577  O0005578     C034691  2025-04-26       Unknown    Completed
5743  O0005744     C027667  2024-12-11  Social Media    Completed
8596  O0008597     C001843  2025-09-27   Marketplace    Completed
9791  O0009792     C042737  2025-12-22   Phone Order    Completed

In [183]:
# ---------------------------------------------------------
# Domain Validity Audit 2:
# Invalid Return Reasons
# ---------------------------------------------------------

invalid_return_reasons = audit_returns[
    audit_returns["return_reason"].notna()
    &
    ~audit_returns["return_reason"].isin(
        RETURN_REASONS
    )
]

print("RETURN REASON VALIDITY RESULTS")
print("------------------------------")

print(
    "Invalid return-reason records:",
    len(invalid_return_reasons)
)

print("\nInvalid values found:")

print(
    invalid_return_reasons[
        "return_reason"
    ].value_counts()
)

RETURN REASON VALIDITY RESULTS
------------------------------
Invalid return-reason records: 58

Invalid values found:
return_reason
Unknown               23
Customer Complaint    13
Other123              13
No Reason              9
Name: count, dtype: int64

In [184]:
# ---------------------------------------------------------
# Show Invalid Return Reason Examples
# ---------------------------------------------------------

display(
    invalid_return_reasons[
        [
            "return_id",
            "order_id",
            "product_id",
            "return_reason",
            "refund_amount"
        ]
    ].head(10)
)

     return_id  order_id product_id       return_reason  refund_amount
95    R0000096  O0001489     P01592  Customer Complaint         456.62
177   R0000178  O0003253     P01541           No Reason           9.59
257   R0000258  O0004647     P00089  Customer Complaint         616.59
597   R0000598  O0010991     P01119            Other123          94.34
894   R0000895  O0016475     P00446             Unknown         342.02
907   R0000908  O0016858     P01786           No Reason         362.34
911   R0000912  O0016893     P01052             Unknown         190.77
990   R0000991  O0018378     P01623           No Reason         727.29
1036  R0001037  O0019060     P00136             Unknown         487.19
1253  R0001254  O0022981     P01226  Customer Complaint         177.30

In [186]:
# ---------------------------------------------------------
# Step 104A:
# Define Valid Category-Subcategory Mapping
# ---------------------------------------------------------

CATEGORY_SUBCATEGORY_MAP = {
    "Electronics": [
        "Smartphones",
        "Laptops",
        "Tablets",
        "Headphones",
        "Accessories"
    ],

    "Home & Kitchen": [
        "Cookware",
        "Kitchen Appliances",
        "Furniture",
        "Home Decor",
        "Storage"
    ],

    "Office Supplies": [
        "Printers",
        "Paper",
        "Writing Supplies",
        "Office Furniture",
        "Organization"
    ],

    "Sports & Outdoors": [
        "Fitness Equipment",
        "Outdoor Gear",
        "Sports Equipment",
        "Camping",
        "Cycling"
    ],

    "Clothing": [
        "Men's Clothing",
        "Women's Clothing",
        "Kids' Clothing",
        "Footwear",
        "Accessories"
    ]
}

# Build valid category-subcategory pairs
valid_category_subcategory_pairs = set()

for category, subcategories in CATEGORY_SUBCATEGORY_MAP.items():

    for subcategory in subcategories:

        valid_category_subcategory_pairs.add(
            (category, subcategory)
        )

print(
    "Valid category-subcategory combinations:",
    len(valid_category_subcategory_pairs)
)

Valid category-subcategory combinations: 25

In [187]:
# ---------------------------------------------------------
# Step 104B:
# Detect Category-Subcategory Mismatches
# ---------------------------------------------------------

# Ignore rows where subcategory is missing because
# missing values are handled by a separate quality rule
products_for_category_check = audit_products[
    audit_products["category"].notna()
    &
    audit_products["subcategory"].notna()
].copy()

# Check whether each category-subcategory pair is valid
category_subcategory_mismatches = (
    products_for_category_check[
        ~products_for_category_check.apply(
            lambda row: (
                row["category"],
                row["subcategory"]
            ) in valid_category_subcategory_pairs,
            axis=1
        )
    ]
)

print("CATEGORY / SUBCATEGORY CONSISTENCY")
print("----------------------------------")

print(
    "Products checked:",
    len(products_for_category_check)
)

print(
    "Mismatched records:",
    len(category_subcategory_mismatches)
)

display(
    category_subcategory_mismatches[
        [
            "product_id",
            "product_name",
            "category",
            "subcategory",
            "brand"
        ]
    ].head(10)
)

CATEGORY / SUBCATEGORY CONSISTENCY
----------------------------------
Products checked: 1990
Mismatched records: 347

,product_id,product_name,category,subcategory,brand
2,P00003,TrailForge Sports Accessories 0003,Sports & Outdoors,Sports Accessories,TrailForge
11,P00012,Vertex Electronics Monitors 0012,Electronics,Monitors,Vertex Electronics
12,P00013,HavenHome Storage 0013,Home & Kitchen,Office Furniture,HavenHome
16,P00017,Apex Devices Monitors 0017,Electronics,Monitors,Apex Devices
19,P00020,EverWear Activewear 0020,Clothing,Activewear,EverWear
22,P00023,PrimeDesk Desk Accessories 0023,Office Supplies,Desk Accessories,PrimeDesk
26,P00027,UrbanThread Activewear 0027,Clothing,Activewear,UrbanThread
27,P00028,UrbanThread Activewear 0028,Clothing,Activewear,UrbanThread
30,P00031,Vertex Electronics Monitors 0031,Electronics,Monitors,Vertex Electronics
50,P00051,ModeCraft Activewear 0051,Clothing,Activewear,ModeCraft

In [188]:
# ---------------------------------------------------------
# Step 104C:
# Verify Expected Mismatch Count
# ---------------------------------------------------------

expected_mismatches = 15
actual_mismatches = len(
    category_subcategory_mismatches
)

if actual_mismatches == expected_mismatches:
    print(
        f"PASS - Expected {expected_mismatches} "
        f"mismatches and detected {actual_mismatches}."
    )
else:
    print(
        f"FAIL - Expected {expected_mismatches} "
        f"mismatches but detected {actual_mismatches}."
    )

FAIL - Expected 15 mismatches but detected 347.

In [189]:
# ---------------------------------------------------------
# Step 104 - Corrected
# Learn Valid Category/Subcategory Pairs
# From Clean Product Ground Truth
# ---------------------------------------------------------

valid_category_subcategory_pairs = set(
    products_ground_truth_df[
        ["category", "subcategory"]
    ]
    .dropna()
    .drop_duplicates()
    .itertuples(
        index=False,
        name=None
    )
)

print(
    "Valid category-subcategory combinations:",
    len(valid_category_subcategory_pairs)
)

print("\nValid combinations:")

for pair in sorted(valid_category_subcategory_pairs):
    print(pair)

Valid category-subcategory combinations: 25

Valid combinations:
('Clothing', 'Accessories')
('Clothing', 'Activewear')
('Clothing', 'Footwear')
('Clothing', "Men's Clothing")
('Clothing', "Women's Clothing")
('Electronics', 'Headphones')
('Electronics', 'Laptops')
('Electronics', 'Monitors')
('Electronics', 'Smartphones')
('Electronics', 'Tablets')
('Home & Kitchen', 'Cookware')
('Home & Kitchen', 'Furniture')
('Home & Kitchen', 'Home Decor')
('Home & Kitchen', 'Kitchen Appliances')
('Home & Kitchen', 'Storage')
('Office Supplies', 'Desk Accessories')
('Office Supplies', 'Office Furniture')
('Office Supplies', 'Paper')
('Office Supplies', 'Printers')
('Office Supplies', 'Writing Supplies')
('Sports & Outdoors', 'Camping')
('Sports & Outdoors', 'Cycling')
('Sports & Outdoors', 'Fitness Equipment')
('Sports & Outdoors', 'Outdoor Gear')
('Sports & Outdoors', 'Sports Accessories')

In [190]:
# ---------------------------------------------------------
# Detect Actual Category/Subcategory Mismatches
# ---------------------------------------------------------

products_for_category_check = audit_products[
    audit_products["category"].notna()
    &
    audit_products["subcategory"].notna()
].copy()

category_subcategory_mismatches = (
    products_for_category_check[
        ~products_for_category_check.apply(
            lambda row: (
                row["category"],
                row["subcategory"]
            ) in valid_category_subcategory_pairs,
            axis=1
        )
    ]
)

print(
    "Category/subcategory mismatches detected:",
    len(category_subcategory_mismatches)
)

display(
    category_subcategory_mismatches[
        [
            "product_id",
            "product_name",
            "category",
            "subcategory",
            "brand"
        ]
    ].head(10)
)

Category/subcategory mismatches detected: 15

,product_id,product_name,category,subcategory,brand
12,P00013,HavenHome Storage 0013,Home & Kitchen,Office Furniture,HavenHome
161,P00162,NorthLane Men's Clothing 0162,Clothing,Monitors,NorthLane
482,P00483,Pulse Digital Monitors 0483,Electronics,Sports Accessories,Pulse Digital
933,P00934,Apex Devices Headphones 0934,Electronics,Footwear,Apex Devices
1009,P01010,Apex Devices Tablets 1010,Electronics,Home Decor,Apex Devices
1090,P01091,EverWear Activewear 1091,Clothing,Fitness Equipment,EverWear
1314,P01315,Stride Activewear 1315,Clothing,Writing Supplies,Stride
1328,P01329,ActiveCore Cycling 1329,Sports & Outdoors,Furniture,ActiveCore
1384,P01385,ActiveCore Outdoor Gear 1385,Sports & Outdoors,Printers,ActiveCore
1411,P01412,PeakMotion Camping 1412,Sports & Outdoors,Tablets,PeakMotion

In [191]:
expected = 15
actual = len(category_subcategory_mismatches)

print(
    "PASS" if actual == expected else "FAIL",
    f"- Expected {expected}, detected {actual}"
)

PASS - Expected 15, detected 15

In [192]:
# ---------------------------------------------------------
# Step 105A:
# Detect Negative Product Costs
# ---------------------------------------------------------

negative_cost_products = audit_products[
    audit_products["unit_cost"] < 0
].copy()

print("PRODUCT COST VALIDITY")
print("---------------------")

print(
    "Products with negative unit cost:",
    len(negative_cost_products)
)

display(
    negative_cost_products[
        [
            "product_id",
            "product_name",
            "category",
            "unit_cost",
            "unit_price"
        ]
    ].head(10)
)

PRODUCT COST VALIDITY
---------------------
Products with negative unit cost: 10

,product_id,product_name,category,unit_cost,unit_price
101,P00102,Pulse Digital Smartphones 0102,Electronics,-1188.35,1468.18
390,P00391,Pulse Digital Monitors 0391,Electronics,-726.50,935.45
581,P00582,UrbanNest Cookware 0582,Home & Kitchen,-131.24,213.54
1002,P01003,Oak & Stone Storage 1003,Home & Kitchen,-185.15,305.53
1285,P01286,PrimeDesk Writing Supplies 1286,Office Supplies,-336.78,605.91
1364,P01365,Vertex Electronics Tablets 1365,Electronics,-349.26,469.75
1592,P01593,UrbanThread Accessories 1593,Clothing,-21.51,43.86
1647,P01648,HavenHome Home Decor 1648,Home & Kitchen,-213.15,326.47
1676,P01677,OfficeCore Printers 1677,Office Supplies,-53.64,93.84
1839,P01840,TrailForge Camping 1840,Sports & Outdoors,-650.26,911.97

In [193]:
# ---------------------------------------------------------
# Verify Negative Cost Count
# ---------------------------------------------------------

expected_negative_costs = 10
actual_negative_costs = len(
    negative_cost_products
)

print(
    "PASS"
    if actual_negative_costs == expected_negative_costs
    else "FAIL",
    f"- Expected {expected_negative_costs}, "
    f"detected {actual_negative_costs}"
)

PASS - Expected 10, detected 10

In [194]:
# ---------------------------------------------------------
# Step 106A:
# Detect Products Priced Below Cost
# ---------------------------------------------------------

# Only evaluate products with valid positive costs
products_for_price_check = audit_products[
    audit_products["unit_cost"] > 0
].copy()

price_below_cost_products = products_for_price_check[
    products_for_price_check["unit_price"]
    <
    products_for_price_check["unit_cost"]
].copy()

print("PRODUCT PRICE / COST VALIDITY")
print("-----------------------------")

print(
    "Products priced below cost:",
    len(price_below_cost_products)
)

display(
    price_below_cost_products[
        [
            "product_id",
            "product_name",
            "category",
            "unit_cost",
            "unit_price"
        ]
    ].head(10)
)

PRODUCT PRICE / COST VALIDITY
-----------------------------
Products priced below cost: 15

,product_id,product_name,category,unit_cost,unit_price
24,P00025,Stride Men's Clothing 0025,Clothing,7.34,6.57
164,P00165,PeakMotion Cycling 0165,Sports & Outdoors,353.62,212.51
335,P00336,Velocity Sports Cycling 0336,Sports & Outdoors,30.11,19.10
540,P00541,NorthLane Men's Clothing 0541,Clothing,12.00,7.29
571,P00572,UrbanNest Furniture 0572,Home & Kitchen,235.02,167.57
804,P00805,Apex Devices Tablets 0805,Electronics,777.38,477.69
816,P00817,Orbit Technologies Headphones 0817,Electronics,926.73,594.95
1064,P01065,HavenHome Kitchen Appliances 1065,Home & Kitchen,425.84,374.13
1162,P01163,Velocity Sports Camping 1163,Sports & Outdoors,506.94,359.74
1284,P01285,PrimeDesk Writing Supplies 1285,Office Supplies,221.99,154.76

In [195]:
# ---------------------------------------------------------
# Calculate Loss Per Unit
# ---------------------------------------------------------

price_below_cost_products[
    "loss_per_unit"
] = (
    price_below_cost_products["unit_cost"]
    - price_below_cost_products["unit_price"]
).round(2)

display(
    price_below_cost_products[
        [
            "product_id",
            "unit_cost",
            "unit_price",
            "loss_per_unit"
        ]
    ].head(10)
)

     product_id  unit_cost  unit_price  loss_per_unit
24       P00025       7.34        6.57           0.77
164      P00165     353.62      212.51         141.11
335      P00336      30.11       19.10          11.01
540      P00541      12.00        7.29           4.71
571      P00572     235.02      167.57          67.45
804      P00805     777.38      477.69         299.69
816      P00817     926.73      594.95         331.78
1064     P01065     425.84      374.13          51.71
1162     P01163     506.94      359.74         147.20
1284     P01285     221.99      154.76          67.23

In [196]:
expected_below_cost = 15
actual_below_cost = len(
    price_below_cost_products
)

print(
    "PASS"
    if actual_below_cost == expected_below_cost
    else "FAIL",
    f"- Expected {expected_below_cost}, "
    f"detected {actual_below_cost}"
)

PASS - Expected 15, detected 15

In [197]:
# ---------------------------------------------------------
# Step 107A:
# Detect Invalid Order-Item Quantities
# ---------------------------------------------------------

invalid_order_item_quantities = audit_order_items[
    audit_order_items["quantity"] <= 0
].copy()

print("ORDER-ITEM QUANTITY VALIDITY")
print("----------------------------")

print(
    "Invalid quantity records:",
    len(invalid_order_item_quantities)
)

print("\nInvalid quantity values:")

print(
    invalid_order_item_quantities[
        "quantity"
    ].value_counts().sort_index()
)

display(
    invalid_order_item_quantities[
        [
            "order_item_id",
            "order_id",
            "product_id",
            "quantity",
            "unit_price"
        ]
    ].head(10)
)

ORDER-ITEM QUANTITY VALIDITY
----------------------------
Invalid quantity records: 300

Invalid quantity values:
quantity
-2     88
-1    112
 0    100
Name: count, dtype: int64

     order_item_id  order_id product_id  quantity  unit_price
396     OI00000397  O0000159     P01194         0      624.70
776     OI00000777  O0000300     P00574        -1      183.61
1020    OI00001021  O0000396     P01633         0      730.48
2613    OI00002614  O0001024     P00655        -1      293.21
3184    OI00003185  O0001245     P00463        -2      718.52
4001    OI00004002  O0001566     P00845        -1       49.20
4015    OI00004016  O0001571     P01032        -2      608.30
4357    OI00004358  O0001703     P00824        -2       18.53
4569    OI00004570  O0001789     P00265        -1      150.72
4989    OI00004990  O0001949     P01597        -2      179.24

In [198]:
# ---------------------------------------------------------
# Step 107B:
# Verify Invalid Quantity Count
# ---------------------------------------------------------

expected_invalid_quantities = 300

actual_invalid_quantities = len(
    invalid_order_item_quantities
)

print(
    "PASS"
    if actual_invalid_quantities
    == expected_invalid_quantities
    else "FAIL",
    f"- Expected {expected_invalid_quantities}, "
    f"detected {actual_invalid_quantities}"
)

PASS - Expected 300, detected 300

In [199]:
# ---------------------------------------------------------
# Step 108A:
# Detect Invalid Order-Item Discounts
# ---------------------------------------------------------

invalid_order_item_discounts = audit_order_items[
    (audit_order_items["discount_pct"] < 0)
    |
    (audit_order_items["discount_pct"] > 0.30)
].copy()

print("ORDER-ITEM DISCOUNT VALIDITY")
print("----------------------------")

print(
    "Invalid discount records:",
    len(invalid_order_item_discounts)
)

print("\nInvalid discount values:")

print(
    invalid_order_item_discounts[
        "discount_pct"
    ].value_counts().sort_index()
)

display(
    invalid_order_item_discounts[
        [
            "order_item_id",
            "order_id",
            "product_id",
            "quantity",
            "unit_price",
            "discount_pct"
        ]
    ].head(10)
)

ORDER-ITEM DISCOUNT VALIDITY
----------------------------
Invalid discount records: 150

Invalid discount values:
discount_pct
0.50    51
0.75    49
1.10    50
Name: count, dtype: int64

      order_item_id  order_id product_id  quantity  unit_price  discount_pct
1475     OI00001476  O0000567     P00408         1       18.30          0.75
5887     OI00005888  O0002280     P01192         4      901.16          1.10
14491    OI00014492  O0005636     P01207         3      475.05          0.50
17579    OI00017580  O0006842     P00065         1      419.01          0.50
21001    OI00021002  O0008141     P00486         1      460.99          0.75
22424    OI00022425  O0008716     P01335         1      297.46          0.50
23642    OI00023643  O0009186     P00054         1      302.69          1.10
24205    OI00024206  O0009415     P01297         1      258.85          0.50
24415    OI00024416  O0009502     P01965         3      365.16          0.50
26494    OI00026495  O0010298     P00529         2      148.95          0.50

In [200]:
# ---------------------------------------------------------
# Step 108B:
# Verify Invalid Discount Count
# ---------------------------------------------------------

expected_invalid_discounts = 150

actual_invalid_discounts = len(
    invalid_order_item_discounts
)

print(
    "PASS"
    if actual_invalid_discounts
    == expected_invalid_discounts
    else "FAIL",
    f"- Expected {expected_invalid_discounts}, "
    f"detected {actual_invalid_discounts}"
)

PASS - Expected 150, detected 150

In [201]:
# ---------------------------------------------------------
# Step 109A:
# Detect Order-Item Price Inconsistencies
# ---------------------------------------------------------

# Create clean product-price lookup
product_price_lookup = (
    products_ground_truth_df[
        [
            "product_id",
            "unit_price"
        ]
    ]
    .rename(
        columns={
            "unit_price": "expected_unit_price"
        }
    )
)

# Only check order items with valid product IDs
order_items_for_price_check = (
    audit_order_items.merge(
        product_price_lookup,
        on="product_id",
        how="inner"
    )
)

# Calculate difference between transaction price
# and expected product price
order_items_for_price_check[
    "price_difference"
] = (
    order_items_for_price_check["unit_price"]
    - order_items_for_price_check["expected_unit_price"]
).round(2)

price_inconsistent_items = (
    order_items_for_price_check[
        order_items_for_price_check[
            "price_difference"
        ].abs() > 0.01
    ]
)

print("ORDER-ITEM PRICE CONSISTENCY")
print("----------------------------")

print(
    "Price-inconsistent records:",
    len(price_inconsistent_items)
)

display(
    price_inconsistent_items[
        [
            "order_item_id",
            "order_id",
            "product_id",
            "unit_price",
            "expected_unit_price",
            "price_difference"
        ]
    ].head(10)
)

ORDER-ITEM PRICE CONSISTENCY
----------------------------
Price-inconsistent records: 150

,order_item_id,order_id,product_id,unit_price,expected_unit_price,price_difference
584,OI00000585,O0000231,P00459,312.96,521.60,-208.64
2125,OI00002127,O0000819,P00518,333.95,556.59,-222.64
3304,OI00003306,O0001291,P00938,211.55,352.59,-141.04
5169,OI00005172,O0002018,P00345,391.22,260.81,130.41
5373,OI00005376,O0002092,P01034,52.85,132.12,-79.27
8261,OI00008266,O0003230,P01104,137.84,106.03,31.81
10435,OI00010441,O0004063,P01080,273.80,182.53,91.27
11416,OI00011422,O0004446,P00253,121.32,202.20,-80.88
14923,OI00014931,O0005813,P01282,173.04,108.15,64.89
16429,OI00016438,O0006424,P01405,766.29,510.86,255.43

In [202]:
# ---------------------------------------------------------
# Step 109B:
# Verify Price Inconsistency Count
# ---------------------------------------------------------

expected_price_inconsistencies = 150

actual_price_inconsistencies = len(
    price_inconsistent_items
)

print(
    "PASS"
    if actual_price_inconsistencies
    == expected_price_inconsistencies
    else "FAIL",
    f"- Expected {expected_price_inconsistencies}, "
    f"detected {actual_price_inconsistencies}"
)

PASS - Expected 150, detected 150

In [203]:
# ---------------------------------------------------------
# Step 110A:
# Detect Returns Exceeding Purchased Quantity
# ---------------------------------------------------------

# Create clean purchased-quantity lookup
purchased_quantity_lookup = (
    order_items_ground_truth_df[
        [
            "order_item_id",
            "quantity"
        ]
    ]
    .rename(
        columns={
            "quantity": "purchased_quantity"
        }
    )
)

# Only valid order_item references will match here
returns_for_quantity_check = (
    audit_returns.merge(
        purchased_quantity_lookup,
        on="order_item_id",
        how="inner"
    )
)

# Remove duplicate return IDs so duplication remains
# a separate quality problem
duplicate_return_ids_step110 = set(
    audit_returns.loc[
        audit_returns["return_id"].duplicated(
            keep=False
        ),
        "return_id"
    ]
)

returns_for_quantity_check = (
    returns_for_quantity_check[
        ~returns_for_quantity_check[
            "return_id"
        ].isin(duplicate_return_ids_step110)
    ]
    .copy()
)

invalid_return_quantities = (
    returns_for_quantity_check[
        returns_for_quantity_check["return_quantity"]
        >
        returns_for_quantity_check["purchased_quantity"]
    ]
    .copy()
)

print("RETURN QUANTITY VALIDITY")
print("------------------------")

print(
    "Returns exceeding purchased quantity:",
    len(invalid_return_quantities)
)

display(
    invalid_return_quantities[
        [
            "return_id",
            "order_item_id",
            "order_id",
            "product_id",
            "purchased_quantity",
            "return_quantity"
        ]
    ].head(10)
)

RETURN QUANTITY VALIDITY
------------------------
Returns exceeding purchased quantity: 100

,return_id,order_item_id,order_id,product_id,purchased_quantity,return_quantity
75,R0000077,OI00003117,O0001217,P00684,1,2
156,R0000160,OI00006825,O0002650,P00718,1,2
204,R0000209,OI00009608,O0003738,P01797,3,5
315,R0000322,OI00014791,O0005753,P01935,1,3
352,R0000360,OI00016347,O0006387,P00663,4,5
408,R0000416,OI00019150,O0007428,P01503,1,2
428,R0000436,OI00019823,O0007690,P00615,2,5
667,R0000679,OI00033566,O0013054,P00922,1,3
685,R0000697,OI00033928,O0013189,P01865,1,4
728,R0000740,OI00035639,O0013852,P00990,1,4

In [204]:
# ---------------------------------------------------------
# Step 110B:
# Verify Invalid Return Quantity Count
# ---------------------------------------------------------

expected_invalid_return_quantities = 100

actual_invalid_return_quantities = len(
    invalid_return_quantities
)

print(
    "PASS"
    if actual_invalid_return_quantities
    == expected_invalid_return_quantities
    else "FAIL",
    f"- Expected {expected_invalid_return_quantities}, "
    f"detected {actual_invalid_return_quantities}"
)

PASS - Expected 100, detected 100

In [205]:
# ---------------------------------------------------------
# Step 111A:
# Payment Status vs Order Status Consistency
# ---------------------------------------------------------

EXPECTED_PAYMENT_STATUS = {
    "Completed": "Successful",
    "Cancelled": "Failed",
    "Returned": "Refunded"
}

# Clean order-status lookup
order_status_lookup = (
    orders_ground_truth_df[
        [
            "order_id",
            "order_status"
        ]
    ]
    .copy()
)

# Only valid order references will match
payments_for_status_check = (
    audit_payments.merge(
        order_status_lookup,
        on="order_id",
        how="inner"
    )
)

# Remove duplicate payment IDs so duplicate records
# remain a separate quality issue
duplicate_payment_ids_step111 = set(
    audit_payments.loc[
        audit_payments["payment_id"].duplicated(
            keep=False
        ),
        "payment_id"
    ]
)

payments_for_status_check = (
    payments_for_status_check[
        ~payments_for_status_check[
            "payment_id"
        ].isin(duplicate_payment_ids_step111)
    ]
    .copy()
)

# Determine expected payment status
payments_for_status_check[
    "expected_payment_status"
] = payments_for_status_check[
    "order_status"
].map(
    EXPECTED_PAYMENT_STATUS
)

# Find mismatches
payment_status_mismatches = (
    payments_for_status_check[
        payments_for_status_check["payment_status"]
        !=
        payments_for_status_check["expected_payment_status"]
    ]
    .copy()
)

print("PAYMENT STATUS CONSISTENCY")
print("--------------------------")

print(
    "Payment-status mismatches:",
    len(payment_status_mismatches)
)

display(
    payment_status_mismatches[
        [
            "payment_id",
            "order_id",
            "order_status",
            "payment_status",
            "expected_payment_status"
        ]
    ].head(10)
)

PAYMENT STATUS CONSISTENCY
--------------------------
Payment-status mismatches: 100

      payment_id  order_id order_status payment_status expected_payment_status
417   PAY0000420  O0000420    Completed         Failed              Successful
581   PAY0000585  O0000585    Cancelled     Successful                  Failed
1103  PAY0001108  O0001108     Returned         Failed                Refunded
2057  PAY0002062  O0002062    Cancelled       Refunded                  Failed
3021  PAY0003029  O0003029    Completed       Refunded              Successful
4359  PAY0004369  O0004369    Completed       Refunded              Successful
4899  PAY0004909  O0004909    Completed         Failed              Successful
5786  PAY0005796  O0005796    Completed       Refunded              Successful
7905  PAY0007919  O0007919    Completed       Refunded              Successful
8379  PAY0008394  O0008394    Completed       Refunded              Successful

In [206]:
# ---------------------------------------------------------
# Step 111B:
# Verify Payment Status Mismatch Count
# ---------------------------------------------------------

expected_status_mismatches = 100

actual_status_mismatches = len(
    payment_status_mismatches
)

print(
    "PASS"
    if actual_status_mismatches
    == expected_status_mismatches
    else "FAIL",
    f"- Expected {expected_status_mismatches}, "
    f"detected {actual_status_mismatches}"
)

PASS - Expected 100, detected 100

In [207]:
# ---------------------------------------------------------
# Step 112A:
# Build Valid State -> Region Mapping
# ---------------------------------------------------------

state_region_lookup = (
    customers_ground_truth_df[
        ["state", "region"]
    ]
    .drop_duplicates()
)

print("Valid state-region mappings:")
print(len(state_region_lookup))

display(
    state_region_lookup
        .sort_values("state")
        .head(15)
)

Valid state-region mappings:
18

   state     region
7     AZ       West
1     CA       West
10    CO       West
0     FL      South
27    GA      South
21    IL    Midwest
65    IN    Midwest
43    MA  Northeast
13    MI    Midwest
5     MN    Midwest
2     MO    Midwest
3     NC      South
6     NJ  Northeast
4     NY  Northeast
22    OH    Midwest

In [208]:
# ---------------------------------------------------------
# Step 112B:
# Detect Customer State-Region Mismatches
# ---------------------------------------------------------

customers_for_region_check = (
    audit_customers[
        audit_customers["state"].notna()
        & audit_customers["region"].notna()
    ]
    .merge(
        state_region_lookup.rename(
            columns={
                "region": "expected_region"
            }
        ),
        on="state",
        how="left"
    )
)

customer_region_mismatches = (
    customers_for_region_check[
        customers_for_region_check["region"]
        !=
        customers_for_region_check["expected_region"]
    ]
    .copy()
)

print("CUSTOMER REGION CONSISTENCY")
print("---------------------------")

print(
    "State-region mismatches:",
    len(customer_region_mismatches)
)

display(
    customer_region_mismatches[
        [
            "customer_id",
            "city",
            "state",
            "region",
            "expected_region"
        ]
    ].head(10)
)

CUSTOMER REGION CONSISTENCY
---------------------------
State-region mismatches: 300

     customer_id     city state     region expected_region
117      C000118  Chicago    IL       West         Midwest
228      C000231  Orlando    FL    Midwest           South
250      C000253  Phoenix    AZ      South            West
262      C000266  Seattle    WA  Northeast            West
574      C000581   Austin    TX  Northeast           South
824      C000835    Miami    FL  Northeast           South
1004     C001015   Dallas    TX       West           South
1168     C001183  Seattle    WA    Midwest            West
1357     C001372   Dallas    TX  Northeast           South
1892     C001913   Dallas    TX       West           South

In [209]:
# ---------------------------------------------------------
# Step 112C:
# Verify Region Mismatch Count
# ---------------------------------------------------------

expected_region_mismatches = 300
actual_region_mismatches = len(
    customer_region_mismatches
)

print(
    "PASS"
    if actual_region_mismatches
    == expected_region_mismatches
    else "FAIL",
    f"- Expected {expected_region_mismatches}, "
    f"detected {actual_region_mismatches}"
)

PASS - Expected 300, detected 300

In [210]:
# ---------------------------------------------------------
# Step 113A:
# Detect Invalid Customer Email Addresses
# ---------------------------------------------------------

email_pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"

invalid_customer_emails = audit_customers[
    audit_customers["email"].notna()
    &
    ~audit_customers["email"].str.match(
        email_pattern,
        na=False
    )
].copy()

print("CUSTOMER EMAIL VALIDITY")
print("-----------------------")

print(
    "Invalid email addresses:",
    len(invalid_customer_emails)
)

display(
    invalid_customer_emails[
        [
            "customer_id",
            "first_name",
            "last_name",
            "email"
        ]
    ].head(10)
)

CUSTOMER EMAIL VALIDITY
-----------------------
Invalid email addresses: 400

    customer_id first_name  last_name                           email
126     C000127   Jennifer      Perez     jennifer.perez127icloud.com
160     C000161      Brian      Davis         brian.davis161yahoo.com
273     C000274      Betty      Young       betty.young274outlook.com
332     C000333    Matthew      Smith       matthew.smith333gmail.com
581     C000582       Lisa     Harris         lisa.harris582gmail.com
584     C000585   Kimberly    Sanchez  kimberly.sanchez585outlook.com
591     C000592     Donald  Hernandez    donald.hernandez592yahoo.com
697     C000698     Andrew   Mitchell   andrew.mitchell698outlook.com
776     C000777    Michael    Sanchez   michael.sanchez777outlook.com
831     C000832       John      Perez          john.perez832gmail.com

In [211]:
# ---------------------------------------------------------
# Step 113B:
# Verify Invalid Email Count
# ---------------------------------------------------------

expected_invalid_emails = 400

actual_invalid_emails = len(
    invalid_customer_emails
)

print(
    "PASS"
    if actual_invalid_emails
    == expected_invalid_emails
    else "FAIL",
    f"- Expected {expected_invalid_emails}, "
    f"detected {actual_invalid_emails}"
)

PASS - Expected 400, detected 400

In [212]:
# ---------------------------------------------------------
# Step 114A:
# Detect Order Shipping Region Mismatches
# ---------------------------------------------------------

# Build trusted state -> region reference
shipping_region_lookup = (
    customers_ground_truth_df[
        ["state", "region"]
    ]
    .drop_duplicates()
    .rename(
        columns={
            "region": "expected_shipping_region"
        }
    )
)

# Compare order shipping state with shipping region
orders_for_shipping_check = (
    audit_orders[
        audit_orders["shipping_state"].notna()
        & audit_orders["shipping_region"].notna()
    ]
    .merge(
        shipping_region_lookup,
        left_on="shipping_state",
        right_on="state",
        how="left"
    )
)

shipping_region_mismatches = (
    orders_for_shipping_check[
        orders_for_shipping_check["shipping_region"]
        !=
        orders_for_shipping_check[
            "expected_shipping_region"
        ]
    ]
    .copy()
)

print("ORDER SHIPPING REGION CONSISTENCY")
print("---------------------------------")

print(
    "Shipping-region mismatches:",
    len(shipping_region_mismatches)
)

display(
    shipping_region_mismatches[
        [
            "order_id",
            "shipping_city",
            "shipping_state",
            "shipping_region",
            "expected_shipping_region"
        ]
    ].head(10)
)

ORDER SHIPPING REGION CONSISTENCY
---------------------------------
Shipping-region mismatches: 150

,order_id,shipping_city,shipping_state,shipping_region,expected_shipping_region
648,O0000649,Columbus,OH,South,Midwest
2406,O0002407,Pittsburgh,PA,Midwest,Northeast
2969,O0002970,Miami,FL,West,South
3089,O0003090,Kansas City,MO,West,Midwest
4161,O0004162,Phoenix,AZ,South,West
4297,O0004298,Detroit,MI,South,Midwest
4856,O0004857,Kansas City,MO,West,Midwest
5373,O0005374,Kansas City,MO,South,Midwest
6211,O0006212,Minneapolis,MN,West,Midwest
9080,O0009081,Newark,NJ,South,Northeast

In [213]:
# ---------------------------------------------------------
# Step 114B:
# Verify Shipping Region Mismatch Count
# ---------------------------------------------------------

expected_shipping_mismatches = 150

actual_shipping_mismatches = len(
    shipping_region_mismatches
)

print(
    "PASS"
    if actual_shipping_mismatches
    == expected_shipping_mismatches
    else "FAIL",
    f"- Expected {expected_shipping_mismatches}, "
    f"detected {actual_shipping_mismatches}"
)

PASS - Expected 150, detected 150

In [214]:
# ---------------------------------------------------------
# Step 115A:
# Detect Invalid Return Reasons
# ---------------------------------------------------------

VALID_RETURN_REASONS = [
    "Damaged",
    "Defective",
    "Wrong Item",
    "Not as Described",
    "Changed Mind",
    "Size/Fit Issue",
    "Arrived Late"
]

invalid_return_reasons = audit_returns[
    audit_returns["return_reason"].notna()
    &
    ~audit_returns["return_reason"].isin(
        VALID_RETURN_REASONS
    )
].copy()

print("RETURN REASON VALIDITY")
print("----------------------")

print(
    "Invalid return reasons:",
    len(invalid_return_reasons)
)

print("\nInvalid values detected:")

print(
    invalid_return_reasons[
        "return_reason"
    ].value_counts()
)

display(
    invalid_return_reasons[
        [
            "return_id",
            "order_id",
            "product_id",
            "return_reason"
        ]
    ].head(10)
)

RETURN REASON VALIDITY
----------------------
Invalid return reasons: 58

Invalid values detected:
return_reason
Unknown               23
Customer Complaint    13
Other123              13
No Reason              9
Name: count, dtype: int64

     return_id  order_id product_id       return_reason
95    R0000096  O0001489     P01592  Customer Complaint
177   R0000178  O0003253     P01541           No Reason
257   R0000258  O0004647     P00089  Customer Complaint
597   R0000598  O0010991     P01119            Other123
894   R0000895  O0016475     P00446             Unknown
907   R0000908  O0016858     P01786           No Reason
911   R0000912  O0016893     P01052             Unknown
990   R0000991  O0018378     P01623           No Reason
1036  R0001037  O0019060     P00136             Unknown
1253  R0001254  O0022981     P01226  Customer Complaint

In [215]:
# ---------------------------------------------------------
# Step 115B:
# Verify Invalid Return Reason Count
# ---------------------------------------------------------

expected_invalid_return_reasons = 75

actual_invalid_return_reasons = len(
    invalid_return_reasons
)

print(
    "PASS"
    if actual_invalid_return_reasons
    == expected_invalid_return_reasons
    else "FAIL",
    f"- Expected {expected_invalid_return_reasons}, "
    f"detected {actual_invalid_return_reasons}"
)

FAIL - Expected 75, detected 58

In [216]:
# ---------------------------------------------------------
# Step 115 Fix:
# Derive Valid Return Reasons From Ground Truth
# ---------------------------------------------------------

valid_return_reasons = set(
    returns_ground_truth_df[
        "return_reason"
    ]
    .dropna()
    .unique()
)

print(
    "Number of valid return reasons:",
    len(valid_return_reasons)
)

print("\nValid return reasons:")

for reason in sorted(valid_return_reasons):
    print(reason)

Number of valid return reasons: 7

Valid return reasons:
Arrived Late
Changed Mind
Damaged
Defective
Not as Described
Size/Fit Issue
Wrong Item

In [217]:
# ---------------------------------------------------------
# Step 115C:
# Inspect Invalid Return Reason Values
# ---------------------------------------------------------

invalid_reason_rows = audit_returns[
    ~audit_returns["return_reason"].isin(
        valid_return_reasons
    )
].copy()

print("Invalid rows detected:", len(invalid_reason_rows))

print("\nInvalid return reason values:")
print(
    invalid_reason_rows[
        "return_reason"
    ].value_counts(
        dropna=False
    )
)

display(
    invalid_reason_rows[
        [
            "return_id",
            "order_id",
            "order_item_id",
            "return_reason"
        ]
    ].head(20)
)

Invalid rows detected: 75

Invalid return reason values:
return_reason
Unknown               23
NaN                   17
Customer Complaint    13
Other123              13
No Reason              9
Name: count, dtype: int64

     return_id  order_id order_item_id       return_reason
95    R0000096  O0001489    OI00003805  Customer Complaint
177   R0000178  O0003253    OI00008322           No Reason
257   R0000258  O0004647    OI00011920  Customer Complaint
470   R0000471  O0008358    OI00021541                 NaN
493   R0000494  O0008978    OI00023102                 NaN
559   R0000560  O0010233    OI00026316                 NaN
597   R0000598  O0010991    OI00028276            Other123
726   R0000727  O0013662    OI00035136                 NaN
876   R0000877  O0016036    OI00041293                 NaN
894   R0000895  O0016475    OI00042438             Unknown
907   R0000908  O0016858    OI00043442           No Reason
911   R0000912  O0016893    OI00043520             Unknown
990   R0000991  O0018378    OI00047284           No Reason
1036  R0001037  O0019060    OI00049001             Unknown
1253  R0001254  O0022981    OI00058928  Customer Complaint
1356  R0001357  O0024850    OI00063680            Other123
1413  R0001414  O0026032    OI00066727             Unknown
1441  R0001442  O0026570    OI00068045  Customer Complaint
1792  R0001793  O0031584    OI00080843            Other123
1821  R0001822  O0031945    OI00081747                 NaN

In [219]:
# ---------------------------------------------------------
# Step 115E:
# Inspect Return Issue Log Structure
# ---------------------------------------------------------

print("Return issue log columns:")
print(return_issue_log_df.columns.tolist())

print("\nFirst 10 rows:")
display(return_issue_log_df.head(10))

Return issue log columns:
['return_id', 'issue_type', 'column', 'original_value', 'injected_value']

First 10 rows:

,return_id,issue_type,column,original_value,injected_value
0,R0000933,business_rule_violation,return_quantity,1,2
1,R0006172,business_rule_violation,return_quantity,1,4
2,R0002667,business_rule_violation,return_quantity,1,3
3,R0002009,business_rule_violation,return_quantity,1,4
4,R0003290,business_rule_violation,return_quantity,3,4
5,R0003781,business_rule_violation,return_quantity,1,3
6,R0002114,business_rule_violation,return_quantity,1,4
7,R0004537,business_rule_violation,return_quantity,1,2
8,R0002852,business_rule_violation,return_quantity,1,2
9,R0005518,business_rule_violation,return_quantity,1,2

In [220]:
# ---------------------------------------------------------
# Step 115F:
# Compare Ground Truth vs Detected Return-Reason Issues
# ---------------------------------------------------------

# Return IDs that were intentionally corrupted in return_reason
expected_invalid_reason_ids = set(
    return_issue_log_df.loc[
        return_issue_log_df["column"] == "return_reason",
        "return_id"
    ]
)

# Return IDs currently detected as having an invalid reason
actual_invalid_reason_ids = set(
    invalid_reason_rows["return_id"]
)

print(
    "Ground-truth return_reason issues:",
    len(expected_invalid_reason_ids)
)

print(
    "Detected invalid return_reason rows:",
    len(actual_invalid_reason_ids)
)

# Find intentionally corrupted rows that our rule did not detect
missing_invalid_reason_ids = (
    expected_invalid_reason_ids
    - actual_invalid_reason_ids
)

print(
    "Ground-truth issues NOT detected:",
    len(missing_invalid_reason_ids)
)

print("\nUndetected return IDs:")
print(
    list(missing_invalid_reason_ids)[:20]
)

Ground-truth return_reason issues: 75
Detected invalid return_reason rows: 75
Ground-truth issues NOT detected: 0

Undetected return IDs:
[]

In [221]:
# ---------------------------------------------------------
# Step 115G:
# Inspect Undetected Ground-Truth Issues
# ---------------------------------------------------------

undetected_reason_rows = return_issue_log_df[
    return_issue_log_df["return_id"].isin(
        missing_invalid_reason_ids
    )
    &
    (
        return_issue_log_df["column"]
        == "return_reason"
    )
].copy()

display(
    undetected_reason_rows[
        [
            "return_id",
            "issue_type",
            "column",
            "original_value",
            "injected_value"
        ]
    ]
)

Empty DataFrame
Columns: [return_id, issue_type, column, original_value, injected_value]
Index: []

In [222]:
# ---------------------------------------------------------
# Step 115G:
# Diagnose Undetected Return-Reason Issues
# ---------------------------------------------------------

# Ground-truth IDs for return_reason corruption
expected_invalid_reason_ids = set(
    return_issue_log_df.loc[
        return_issue_log_df["column"] == "return_reason",
        "return_id"
    ]
)

# Actual IDs detected by our validity rule
actual_invalid_reason_ids = set(
    invalid_reason_rows["return_id"]
)

# IDs expected but not detected
missing_invalid_reason_ids = (
    expected_invalid_reason_ids
    - actual_invalid_reason_ids
)

print(
    "Expected return_reason issues:",
    len(expected_invalid_reason_ids)
)

print(
    "Detected return_reason issues:",
    len(actual_invalid_reason_ids)
)

print(
    "Undetected issues:",
    len(missing_invalid_reason_ids)
)

# Compare ground truth with current returns data
diagnostic = (
    return_issue_log_df[
        return_issue_log_df["return_id"].isin(
            missing_invalid_reason_ids
        )
        &
        (
            return_issue_log_df["column"]
            == "return_reason"
        )
    ]
    .merge(
        audit_returns[
            [
                "return_id",
                "return_reason"
            ]
        ],
        on="return_id",
        how="left"
    )
)

print("\nUndetected records:")
display(diagnostic)

Expected return_reason issues: 75
Detected return_reason issues: 75
Undetected issues: 0

Undetected records:

Empty DataFrame
Columns: [return_id, issue_type, column, original_value, injected_value, return_reason]
Index: []

In [223]:
# ---------------------------------------------------------
# Step 116A:
# Payment Method Domain Validity
# ---------------------------------------------------------

VALID_PAYMENT_METHODS = {
    "Credit Card",
    "Debit Card",
    "PayPal",
    "Apple Pay",
    "Google Pay",
    "Bank Transfer"
}

invalid_payment_methods = audit_payments[
    audit_payments["payment_method"].notna()
    &
    ~audit_payments["payment_method"].isin(
        VALID_PAYMENT_METHODS
    )
].copy()

print("PAYMENT METHOD VALIDITY")
print("-----------------------")

print(
    "Invalid payment-method records:",
    len(invalid_payment_methods)
)

print("\nInvalid payment methods found:")

print(
    invalid_payment_methods[
        "payment_method"
    ].value_counts()
)

display(
    invalid_payment_methods[
        [
            "payment_id",
            "order_id",
            "payment_method",
            "payment_status",
            "payment_amount"
        ]
    ].head(10)
)

PAYMENT METHOD VALIDITY
-----------------------
Invalid payment-method records: 18011

Invalid payment methods found:
payment_method
Digital Wallet    18011
Name: count, dtype: int64

    payment_id  order_id  payment_method payment_status  payment_amount
16  PAY0000017  O0000017  Digital Wallet     Successful         2382.44
27  PAY0000028  O0000028  Digital Wallet     Successful         1241.03
30  PAY0000031  O0000031  Digital Wallet     Successful          954.45
31  PAY0000032  O0000032  Digital Wallet     Successful         1583.42
32  PAY0000033  O0000033  Digital Wallet     Successful          716.25
36  PAY0000037  O0000037  Digital Wallet     Successful         1294.48
37  PAY0000038  O0000038  Digital Wallet     Successful          913.79
46  PAY0000047  O0000047  Digital Wallet     Successful          326.74
47  PAY0000048  O0000048  Digital Wallet     Successful          679.39
52  PAY0000053  O0000053  Digital Wallet     Successful         1457.28

In [224]:
# ---------------------------------------------------------
# Step 116B:
# Verify Invalid Payment Method Count
# ---------------------------------------------------------

expected_invalid_payment_methods = 100

actual_invalid_payment_methods = len(
    invalid_payment_methods
)

print(
    "PASS"
    if actual_invalid_payment_methods
    == expected_invalid_payment_methods
    else "FAIL",
    f"- Expected {expected_invalid_payment_methods}, "
    f"detected {actual_invalid_payment_methods}"
)

FAIL - Expected 100, detected 18011

In [225]:
# ---------------------------------------------------------
# Step 116 Fix:
# Derive Valid Payment Methods From Ground Truth
# ---------------------------------------------------------

valid_payment_methods = set(
    payments_ground_truth_df[
        "payment_method"
    ]
    .dropna()
    .unique()
)

print(
    "Number of valid payment methods:",
    len(valid_payment_methods)
)

print("\nValid payment methods:")

for method in sorted(valid_payment_methods):
    print(method)

Number of valid payment methods: 4

Valid payment methods:
Credit Card
Debit Card
Digital Wallet
PayPal

In [226]:
# ---------------------------------------------------------
# Detect Invalid Payment Methods Using Ground Truth Domain
# ---------------------------------------------------------

invalid_payment_methods = audit_payments[
    audit_payments["payment_method"].notna()
    &
    ~audit_payments["payment_method"].isin(
        valid_payment_methods
    )
].copy()

print(
    "Invalid payment-method records:",
    len(invalid_payment_methods)
)

print("\nInvalid payment methods found:")

print(
    invalid_payment_methods[
        "payment_method"
    ].value_counts()
)

display(
    invalid_payment_methods[
        [
            "payment_id",
            "order_id",
            "payment_method",
            "payment_status",
            "payment_amount"
        ]
    ].head(10)
)

Invalid payment-method records: 0

Invalid payment methods found:
Series([], Name: count, dtype: int64)

Empty DataFrame
Columns: [payment_id, order_id, payment_method, payment_status, payment_amount]
Index: []

In [227]:
# ---------------------------------------------------------
# Step 116C:
# Check Payment Method Ground Truth
# ---------------------------------------------------------

payment_method_issues = payment_issue_log_df[
    payment_issue_log_df["column"] == "payment_method"
].copy()

print(
    "Ground-truth payment_method issues:",
    len(payment_method_issues)
)

display(
    payment_method_issues.head(20)
)

Ground-truth payment_method issues: 0

Empty DataFrame
Columns: [payment_id, issue_type, column, original_value, injected_value]
Index: []

In [228]:
# ---------------------------------------------------------
# Step 116D:
# Final Payment Method Validation
# ---------------------------------------------------------

actual_invalid_payment_methods = len(
    invalid_payment_methods
)

expected_invalid_payment_methods = len(
    payment_method_issues
)

print(
    "PASS"
    if actual_invalid_payment_methods
    == expected_invalid_payment_methods
    else "FAIL",
    f"- Expected {expected_invalid_payment_methods}, "
    f"detected {actual_invalid_payment_methods}"
)

PASS - Expected 0, detected 0

In [229]:
# ---------------------------------------------------------
# Step 117A:
# Payment Amount vs Order Total Consistency
# ---------------------------------------------------------

# Build clean order-total reference
order_total_lookup = (
    orders_ground_truth_df[
        [
            "order_id",
            "order_total"
        ]
    ]
    .drop_duplicates(
        subset=["order_id"]
    )
)

# Join payments to their corresponding orders
payments_for_amount_check = (
    audit_payments.merge(
        order_total_lookup,
        on="order_id",
        how="inner"
    )
    .copy()
)

# Calculate the difference
payments_for_amount_check[
    "amount_difference"
] = (
    payments_for_amount_check["payment_amount"]
    -
    payments_for_amount_check["order_total"]
).round(2)

# Identify inconsistencies
payment_amount_mismatches = (
    payments_for_amount_check[
        payments_for_amount_check[
            "amount_difference"
        ].abs() > 0.01
    ]
    .copy()
)

print("PAYMENT AMOUNT CONSISTENCY")
print("--------------------------")

print(
    "Payments checked:",
    len(payments_for_amount_check)
)

print(
    "Payment amount mismatches:",
    len(payment_amount_mismatches)
)

display(
    payment_amount_mismatches[
        [
            "payment_id",
            "order_id",
            "payment_amount",
            "order_total",
            "amount_difference"
        ]
    ].head(10)
)

KeyError: "['order_total'] not in index"

In [230]:
# ---------------------------------------------------------
# Step 117 Fix:
# Inspect Orders Ground-Truth Columns
# ---------------------------------------------------------

print("Orders ground-truth columns:")
print(orders_ground_truth_df.columns.tolist())

print("\nFirst 5 rows:")
display(orders_ground_truth_df.head())

Orders ground-truth columns:
['order_id', 'customer_id', 'order_date', 'sales_channel', 'order_status', 'payment_method', 'shipping_city', 'shipping_state', 'shipping_region']

First 5 rows:

,order_id,customer_id,order_date,sales_channel,order_status,payment_method,shipping_city,shipping_state,shipping_region
0,O0000001,C024260,2025-12-06,Mobile App,Completed,Credit Card,Austin,TX,South
1,O0000002,C016387,2024-06-16,Mobile App,Returned,PayPal,Detroit,MI,Midwest
2,O0000003,C034376,2025-08-20,Website,Completed,Credit Card,Newark,NJ,Northeast
3,O0000004,C035249,2025-03-10,Website,Completed,Credit Card,Los Angeles,CA,West
4,O0000005,C034541,2025-09-23,Website,Completed,Credit Card,New York,NY,Northeast

In [231]:
# ---------------------------------------------------------
# Step 117A:
# Identify Order Amount / Total Columns
# ---------------------------------------------------------

print("Orders columns:")
print(audit_orders.columns.tolist())

print("\nPotential amount/total columns:")

amount_candidates = [
    col for col in audit_orders.columns
    if any(
        keyword in col.lower()
        for keyword in [
            "total",
            "amount",
            "revenue",
            "subtotal",
            "price"
        ]
    )
]

print(amount_candidates)

print("\nSample data:")
display(
    audit_orders[
        amount_candidates
    ].head()
)

Orders columns:
['order_id', 'customer_id', 'order_date', 'sales_channel', 'order_status', 'payment_method', 'shipping_city', 'shipping_state', 'shipping_region']

Potential amount/total columns:
[]

Sample data:

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [232]:
# ---------------------------------------------------------
# Step 117B:
# Payment Amount vs Order Amount Consistency
# ---------------------------------------------------------

# Find likely order-total column automatically
preferred_names = [
    "order_total",
    "total_amount",
    "order_amount",
    "grand_total",
    "total"
]

order_amount_column = None

for col in preferred_names:
    if col in audit_orders.columns:
        order_amount_column = col
        break

# If none of the preferred names exist, show candidates
if order_amount_column is None:

    candidates = [
        col for col in audit_orders.columns
        if any(
            keyword in col.lower()
            for keyword in [
                "total",
                "amount",
                "revenue"
            ]
        )
    ]

    print("Could not automatically identify the order-total column.")
    print("Possible columns:", candidates)

else:

    print(
        "Using order amount column:",
        order_amount_column
    )

    # Build order amount lookup
    order_amount_lookup = (
        audit_orders[
            [
                "order_id",
                order_amount_column
            ]
        ]
        .drop_duplicates(
            subset=["order_id"]
        )
        .rename(
            columns={
                order_amount_column:
                "expected_order_amount"
            }
        )
    )

    # Match payments to orders
    payments_for_amount_check = (
        audit_payments.merge(
            order_amount_lookup,
            on="order_id",
            how="inner"
        )
        .copy()
    )

    # Calculate difference
    payments_for_amount_check[
        "amount_difference"
    ] = (
        payments_for_amount_check["payment_amount"]
        -
        payments_for_amount_check[
            "expected_order_amount"
        ]
    ).round(2)

    # Find mismatches
    payment_amount_mismatches = (
        payments_for_amount_check[
            payments_for_amount_check[
                "amount_difference"
            ].abs() > 0.01
        ]
        .copy()
    )

    print(
        "Payments checked:",
        len(payments_for_amount_check)
    )

    print(
        "Payment amount mismatches:",
        len(payment_amount_mismatches)
    )

    display(
        payment_amount_mismatches[
            [
                "payment_id",
                "order_id",
                "payment_amount",
                "expected_order_amount",
                "amount_difference"
            ]
        ].head(10)
    )

Could not automatically identify the order-total column.
Possible columns: []

In [233]:
# ---------------------------------------------------------
# Step 117C:
# Calculate Expected Order Amount From Order Items
# ---------------------------------------------------------

# Use the clean order-item data as the source of truth
clean_items = order_items_ground_truth_df.copy()

# Calculate each line's expected amount
clean_items["expected_line_total"] = (
    clean_items["quantity"]
    * clean_items["unit_price"]
    * (1 - clean_items["discount_pct"])
).round(2)

# Aggregate line totals by order
expected_order_amounts = (
    clean_items
    .groupby("order_id", as_index=False)[
        "expected_line_total"
    ]
    .sum()
    .rename(
        columns={
            "expected_line_total":
            "expected_order_amount"
        }
    )
)

print("Orders with calculated expected amounts:")
print(len(expected_order_amounts))

display(
    expected_order_amounts.head(10)
)

Orders with calculated expected amounts:
120000

   order_id  expected_order_amount
0  O0000001                1231.55
1  O0000002                1981.16
2  O0000003                1193.27
3  O0000004                1882.46
4  O0000005                3099.90
5  O0000006                 175.33
6  O0000007                3525.93
7  O0000008                3402.70
8  O0000009                2106.09
9  O0000010                 811.81

In [234]:
# ---------------------------------------------------------
# Step 117D:
# Compare Payment Amount to Expected Order Amount
# ---------------------------------------------------------

payments_for_amount_check = (
    audit_payments.merge(
        expected_order_amounts,
        on="order_id",
        how="inner"
    )
    .copy()
)

payments_for_amount_check["amount_difference"] = (
    payments_for_amount_check["payment_amount"]
    -
    payments_for_amount_check["expected_order_amount"]
).round(2)

payment_amount_mismatches = (
    payments_for_amount_check[
        payments_for_amount_check[
            "amount_difference"
        ].abs() > 0.01
    ]
    .copy()
)

print("PAYMENT AMOUNT CONSISTENCY")
print("--------------------------")

print(
    "Payments checked:",
    len(payments_for_amount_check)
)

print(
    "Payment amount mismatches:",
    len(payment_amount_mismatches)
)

display(
    payment_amount_mismatches[
        [
            "payment_id",
            "order_id",
            "payment_amount",
            "expected_order_amount",
            "amount_difference"
        ]
    ].head(10)
)

PAYMENT AMOUNT CONSISTENCY
--------------------------
Payments checked: 119950
Payment amount mismatches: 260

,payment_id,order_id,payment_amount,expected_order_amount,amount_difference
97,PAY0000098,O0000098,2149.49,3070.70,-921.21
217,PAY0000219,O0000219,4839.20,4839.22,-0.02
522,PAY0000525,O0000525,6150.56,6150.58,-0.02
753,PAY0000758,O0000758,2822.32,3527.90,-705.58
1353,PAY0001358,O0001358,253.68,362.40,-108.72
2886,PAY0002894,O0002894,1404.70,1404.72,-0.02
2936,PAY0002944,O0002944,733.58,916.97,-183.39
4407,PAY0004417,O0004417,8837.95,8034.50,803.45
4464,PAY0004474,O0004474,2461.88,2051.57,410.31
4670,PAY0004680,O0004680,2274.42,2067.65,206.77

In [235]:
# ---------------------------------------------------------
# Step 117E:
# Check Ground-Truth Payment Amount Issues
# ---------------------------------------------------------

payment_amount_issues = payment_issue_log_df[
    payment_issue_log_df["column"] == "payment_amount"
].copy()

print(
    "Ground-truth payment_amount issues:",
    len(payment_amount_issues)
)

print("\nIssue types:")
print(
    payment_amount_issues[
        "issue_type"
    ].value_counts()
)

display(
    payment_amount_issues.head(10)
)

Ground-truth payment_amount issues: 200

Issue types:
issue_type
reconciliation_error    200
Name: count, dtype: int64

,payment_id,issue_type,column,original_value,injected_value
0,PAY0020520,reconciliation_error,payment_amount,3233.53,2263.47
1,PAY0071732,reconciliation_error,payment_amount,2706.08,2976.69
2,PAY0063657,reconciliation_error,payment_amount,519.4,363.58
3,PAY0030722,reconciliation_error,payment_amount,1940.09,2134.1
4,PAY0027089,reconciliation_error,payment_amount,1582.8,1107.96
5,PAY0011913,reconciliation_error,payment_amount,2873.82,3735.97
6,PAY0047462,reconciliation_error,payment_amount,2909.46,3200.41
7,PAY0118536,reconciliation_error,payment_amount,1157.96,926.37
8,PAY0115314,reconciliation_error,payment_amount,986.71,690.7
9,PAY0062202,reconciliation_error,payment_amount,1032.51,1239.01

In [236]:
# ---------------------------------------------------------
# Step 117F:
# Final Payment Amount Verification
# ---------------------------------------------------------

detected_payment_amount_issues = len(
    payment_amount_mismatches
)

ground_truth_payment_amount_issues = len(
    payment_amount_issues
)

print(
    "Detected payment amount issues:",
    detected_payment_amount_issues
)

print(
    "Ground-truth payment amount issues:",
    ground_truth_payment_amount_issues
)

if (
    detected_payment_amount_issues
    == ground_truth_payment_amount_issues
):
    print(
        f"\nPASS - Expected "
        f"{ground_truth_payment_amount_issues}, "
        f"detected "
        f"{detected_payment_amount_issues}."
    )
else:
    print(
        f"\nREVIEW - Expected "
        f"{ground_truth_payment_amount_issues}, "
        f"detected "
        f"{detected_payment_amount_issues}."
    )

Detected payment amount issues: 260
Ground-truth payment amount issues: 200

REVIEW - Expected 200, detected 260.

In [237]:
# ---------------------------------------------------------
# Step 118:
# Reconstruct Order Totals From Order Items
# ---------------------------------------------------------

clean_items = order_items_ground_truth_df.copy()

# Calculate expected line-level revenue
clean_items["expected_line_total"] = (
    clean_items["quantity"]
    * clean_items["unit_price"]
    * (1 - clean_items["discount_pct"])
).round(2)

# Aggregate to order level
reconstructed_order_totals = (
    clean_items
    .groupby("order_id", as_index=False)
    ["expected_line_total"]
    .sum()
    .rename(
        columns={
            "expected_line_total":
            "reconstructed_order_total"
        }
    )
)

print("ORDER TOTAL RECONSTRUCTION")
print("--------------------------")

print(
    "Orders reconstructed:",
    len(reconstructed_order_totals)
)

display(
    reconstructed_order_totals.head(10)
)

ORDER TOTAL RECONSTRUCTION
--------------------------
Orders reconstructed: 120000

   order_id  reconstructed_order_total
0  O0000001                    1231.55
1  O0000002                    1981.16
2  O0000003                    1193.27
3  O0000004                    1882.46
4  O0000005                    3099.90
5  O0000006                     175.33
6  O0000007                    3525.93
7  O0000008                    3402.70
8  O0000009                    2106.09
9  O0000010                     811.81

In [238]:
# ---------------------------------------------------------
# Step 119A:
# Detect Orphan Order Items
# ---------------------------------------------------------

valid_order_ids = set(
    audit_orders["order_id"]
    .dropna()
    .unique()
)

orphan_order_items = audit_order_items[
    ~audit_order_items["order_id"].isin(
        valid_order_ids
    )
].copy()

print("ORDER ITEM REFERENTIAL INTEGRITY")
print("--------------------------------")

print(
    "Order items checked:",
    len(audit_order_items)
)

print(
    "Orphan order items:",
    len(orphan_order_items)
)

display(
    orphan_order_items[
        [
            "order_item_id",
            "order_id",
            "product_id",
            "quantity",
            "unit_price"
        ]
    ].head(10)
)

ORDER ITEM REFERENTIAL INTEGRITY
--------------------------------
Order items checked: 307309
Orphan order items: 0

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price]
Index: []

In [239]:
# ---------------------------------------------------------
# Step 119B:
# Check Ground-Truth Orphan Order-Item Issues
# ---------------------------------------------------------

order_item_orphan_issues = (
    order_item_issue_log_df[
        order_item_issue_log_df["issue_type"]
        .astype(str)
        .str.contains(
            "referential|orphan",
            case=False,
            na=False
        )
    ]
    .copy()
)

print(
    "Ground-truth orphan/reference issues:",
    len(order_item_orphan_issues)
)

display(
    order_item_orphan_issues.head(10)
)

Ground-truth orphan/reference issues: 200

,order_item_id,issue_type,column,original_value,injected_value
300,OI00059792,referential_integrity_error,product_id,P00939,P90001
301,OI00062935,referential_integrity_error,product_id,P01675,P90002
302,OI00151401,referential_integrity_error,product_id,P01905,P90003
303,OI00298678,referential_integrity_error,product_id,P01414,P90004
304,OI00260785,referential_integrity_error,product_id,P01988,P90005
305,OI00197633,referential_integrity_error,product_id,P00297,P90006
306,OI00282150,referential_integrity_error,product_id,P00727,P90007
307,OI00306039,referential_integrity_error,product_id,P01185,P90008
308,OI00179096,referential_integrity_error,product_id,P01334,P90009
309,OI00050623,referential_integrity_error,product_id,P01190,P90010

In [240]:
# ---------------------------------------------------------
# Step 120A:
# Detect Order Items With Invalid Product References
# ---------------------------------------------------------

valid_product_ids = set(
    audit_products["product_id"]
    .dropna()
    .unique()
)

orphan_product_items = audit_order_items[
    ~audit_order_items["product_id"].isin(
        valid_product_ids
    )
].copy()

print("PRODUCT REFERENTIAL INTEGRITY")
print("-----------------------------")

print(
    "Order items checked:",
    len(audit_order_items)
)

print(
    "Invalid product references:",
    len(orphan_product_items)
)

display(
    orphan_product_items[
        [
            "order_item_id",
            "order_id",
            "product_id",
            "quantity",
            "unit_price"
        ]
    ].head(10)
)

PRODUCT REFERENTIAL INTEGRITY
-----------------------------
Order items checked: 307309
Invalid product references: 200

      order_item_id  order_id product_id  quantity  unit_price
1555     OI00001556  O0000597     P90074         4      213.54
3925     OI00003926  O0001538     P90036         2      163.69
6274     OI00006275  O0002429     P90115         1      789.71
8139     OI00008140  O0003178     P90192         1      230.23
9260     OI00009261  O0003615     P90130         1      289.69
12686    OI00012687  O0004935     P90145         1      866.31
14277    OI00014278  O0005546     P90165         1      847.07
15537    OI00015538  O0006066     P90179         1      290.73
24833    OI00024834  O0009661     P90100         1      254.92
29464    OI00029465  O0011459     P90032         1       90.96

In [241]:
# ---------------------------------------------------------
# Step 120B:
# Inspect Product Reference Issues
# ---------------------------------------------------------

print("Available order-item issue-log columns:")
print(order_item_issue_log_df.columns.tolist())

product_reference_issues = (
    order_item_issue_log_df[
        order_item_issue_log_df["column"]
        .astype(str)
        .str.contains(
            "product",
            case=False,
            na=False
        )
    ]
    .copy()
)

print(
    "\nGround-truth product-reference issues:",
    len(product_reference_issues)
)

display(
    product_reference_issues.head(10)
)

Available order-item issue-log columns:
['order_item_id', 'issue_type', 'column', 'original_value', 'injected_value']

Ground-truth product-reference issues: 200

,order_item_id,issue_type,column,original_value,injected_value
300,OI00059792,referential_integrity_error,product_id,P00939,P90001
301,OI00062935,referential_integrity_error,product_id,P01675,P90002
302,OI00151401,referential_integrity_error,product_id,P01905,P90003
303,OI00298678,referential_integrity_error,product_id,P01414,P90004
304,OI00260785,referential_integrity_error,product_id,P01988,P90005
305,OI00197633,referential_integrity_error,product_id,P00297,P90006
306,OI00282150,referential_integrity_error,product_id,P00727,P90007
307,OI00306039,referential_integrity_error,product_id,P01185,P90008
308,OI00179096,referential_integrity_error,product_id,P01334,P90009
309,OI00050623,referential_integrity_error,product_id,P01190,P90010

In [242]:
# ---------------------------------------------------------
# Step 121A:
# Detect Payments With Invalid Order References
# ---------------------------------------------------------

valid_order_ids = set(
    audit_orders["order_id"]
    .dropna()
    .unique()
)

orphan_payments = audit_payments[
    ~audit_payments["order_id"].isin(
        valid_order_ids
    )
].copy()

print("PAYMENT REFERENTIAL INTEGRITY")
print("-----------------------------")

print(
    "Payments checked:",
    len(audit_payments)
)

print(
    "Payments with invalid order references:",
    len(orphan_payments)
)

display(
    orphan_payments[
        [
            "payment_id",
            "order_id",
            "payment_date",
            "payment_method",
            "payment_status",
            "payment_amount"
        ]
    ].head(10)
)

PAYMENT REFERENTIAL INTEGRITY
-----------------------------
Payments checked: 120100
Payments with invalid order references: 150

,payment_id,order_id,payment_date,payment_method,payment_status,payment_amount
214,PAY0000215,O9000056,2025-12-20,Digital Wallet,Successful,2066.69
410,PAY0000411,O9000073,2025-05-21,Credit Card,Successful,572.57
537,PAY0000538,O9000053,2025-11-23,Debit Card,Successful,1204.44
662,PAY0000663,O9000013,2024-10-21,Credit Card,Successful,2915.00
2088,PAY0002089,O9000054,2025-12-15,Credit Card,Successful,678.00
2422,PAY0002423,O9000029,2024-11-12,Credit Card,Successful,302.32
2614,PAY0002615,O9000085,2025-10-18,Debit Card,Failed,931.66
3885,PAY0003886,O9000039,2025-06-16,Credit Card,Successful,87.92
4262,PAY0004263,O9000090,2023-04-13,Digital Wallet,Successful,4033.94
6025,PAY0006026,O9000078,2024-06-01,Debit Card,Failed,433.07

In [243]:
# ---------------------------------------------------------
# Step 121B:
# Check Ground-Truth Payment Reference Issues
# ---------------------------------------------------------

payment_reference_issues = (
    payment_issue_log_df[
        payment_issue_log_df["column"]
        .astype(str)
        .str.contains(
            "order_id",
            case=False,
            na=False
        )
    ]
    .copy()
)

print(
    "Ground-truth payment order-reference issues:",
    len(payment_reference_issues)
)

display(
    payment_reference_issues.head(10)
)

Ground-truth payment order-reference issues: 150

,payment_id,issue_type,column,original_value,injected_value
200,PAY0087296,referential_integrity_error,order_id,O0087296,O9000001
201,PAY0107789,referential_integrity_error,order_id,O0107789,O9000002
202,PAY0097250,referential_integrity_error,order_id,O0097250,O9000003
203,PAY0107895,referential_integrity_error,order_id,O0107895,O9000004
204,PAY0092333,referential_integrity_error,order_id,O0092333,O9000005
205,PAY0062660,referential_integrity_error,order_id,O0062660,O9000006
206,PAY0114297,referential_integrity_error,order_id,O0114297,O9000007
207,PAY0052429,referential_integrity_error,order_id,O0052429,O9000008
208,PAY0035551,referential_integrity_error,order_id,O0035551,O9000009
209,PAY0017601,referential_integrity_error,order_id,O0017601,O9000010

In [244]:
# ---------------------------------------------------------
# Step 122A:
# Detect Returns With Invalid Order-Item References
# ---------------------------------------------------------

valid_order_item_ids = set(
    audit_order_items["order_item_id"]
    .dropna()
    .unique()
)

orphan_returns = audit_returns[
    ~audit_returns["order_item_id"].isin(
        valid_order_item_ids
    )
].copy()

print("RETURN REFERENTIAL INTEGRITY")
print("----------------------------")

print(
    "Returns checked:",
    len(audit_returns)
)

print(
    "Returns with invalid order-item references:",
    len(orphan_returns)
)

display(
    orphan_returns[
        [
            "return_id",
            "order_item_id",
            "order_id",
            "product_id",
            "return_quantity",
            "refund_amount"
        ]
    ].head(10)
)

RETURN REFERENTIAL INTEGRITY
----------------------------
Returns checked: 6560
Returns with invalid order-item references: 75

,return_id,order_item_id,order_id,product_id,return_quantity,refund_amount
8,R0000009,OI90000040,O0000106,P01085,4,261.75
123,R0000124,OI90000023,O0001982,P01230,2,822.66
144,R0000145,OI90000008,O0002405,P01119,1,99.58
180,R0000181,OI90000046,O0003253,P01399,1,800.51
211,R0000212,OI90000016,O0003738,P00744,1,87.65
279,R0000280,OI90000048,O0005012,P01625,1,224.04
343,R0000344,OI90000013,O0006041,P01172,1,233.81
482,R0000483,OI90000021,O0008657,P00594,1,584.34
548,R0000549,OI90000059,O0009973,P00946,2,663.82
549,R0000550,OI90000066,O0009974,P01528,3,198.03

In [245]:
# ---------------------------------------------------------
# Step 122B:
# Check Ground-Truth Return Reference Issues
# ---------------------------------------------------------

return_reference_issues = (
    return_issue_log_df[
        return_issue_log_df["column"]
        .astype(str)
        .str.contains(
            "order_item_id",
            case=False,
            na=False
        )
    ]
    .copy()
)

print(
    "Ground-truth return reference issues:",
    len(return_reference_issues)
)

display(
    return_reference_issues.head(10)
)

Ground-truth return reference issues: 75

,return_id,issue_type,column,original_value,injected_value
375,R0006040,referential_integrity_error,order_item_id,OI00282233,OI90000001
376,R0005256,referential_integrity_error,order_item_id,OI00241402,OI90000002
377,R0006364,referential_integrity_error,order_item_id,OI00299063,OI90000003
378,R0001727,referential_integrity_error,order_item_id,OI00078309,OI90000004
379,R0003560,referential_integrity_error,order_item_id,OI00161882,OI90000005
380,R0004791,referential_integrity_error,order_item_id,OI00222002,OI90000006
381,R0002410,referential_integrity_error,order_item_id,OI00108947,OI90000007
382,R0000145,referential_integrity_error,order_item_id,OI00006215,OI90000008
383,R0004638,referential_integrity_error,order_item_id,OI00214390,OI90000009
384,R0001629,referential_integrity_error,order_item_id,OI00074863,OI90000010

In [246]:
# ---------------------------------------------------------
# Step 123A:
# Detect Returns With Invalid Order References
# ---------------------------------------------------------

valid_order_ids = set(
    audit_orders["order_id"]
    .dropna()
    .unique()
)

returns_with_invalid_order = audit_returns[
    ~audit_returns["order_id"].isin(
        valid_order_ids
    )
].copy()

print("RETURN -> ORDER REFERENTIAL INTEGRITY")
print("-------------------------------------")

print(
    "Returns checked:",
    len(audit_returns)
)

print(
    "Returns with invalid order references:",
    len(returns_with_invalid_order)
)

display(
    returns_with_invalid_order[
        [
            "return_id",
            "order_id",
            "order_item_id",
            "product_id",
            "return_quantity",
            "refund_amount"
        ]
    ].head(10)
)

RETURN -> ORDER REFERENTIAL INTEGRITY
-------------------------------------
Returns checked: 6560
Returns with invalid order references: 0

Empty DataFrame
Columns: [return_id, order_id, order_item_id, product_id, return_quantity, refund_amount]
Index: []

In [247]:
# ---------------------------------------------------------
# Step 123B:
# Check Ground-Truth Return Order Reference Issues
# ---------------------------------------------------------

return_order_reference_issues = (
    return_issue_log_df[
        return_issue_log_df["column"]
        .astype(str)
        .str.lower()
        .eq("order_id")
    ]
    .copy()
)

print(
    "Ground-truth return order-reference issues:",
    len(return_order_reference_issues)
)

display(
    return_order_reference_issues.head(10)
)

Ground-truth return order-reference issues: 0

Empty DataFrame
Columns: [return_id, issue_type, column, original_value, injected_value]
Index: []

In [248]:
# ---------------------------------------------------------
# Step 123C:
# Compare Detection With Ground Truth
# ---------------------------------------------------------

detected = len(
    returns_with_invalid_order
)

expected = len(
    return_order_reference_issues
)

print(
    "Detected:",
    detected
)

print(
    "Ground truth:",
    expected
)

if detected == expected:
    print(
        f"PASS - Expected {expected}, detected {detected}."
    )
else:
    print(
        f"REVIEW - Expected {expected}, detected {detected}."
    )

Detected: 0
Ground truth: 0
PASS - Expected 0, detected 0.

In [249]:
# ---------------------------------------------------------
# Step 124A:
# Customer Required-Field Completeness
# ---------------------------------------------------------

required_customer_columns = [
    "first_name",
    "last_name",
    "email",
    "state",
    "region"
]

customer_completeness = []

for column in required_customer_columns:

    missing_count = audit_customers[
        column
    ].isna().sum()

    customer_completeness.append({
        "column": column,
        "missing_count": int(missing_count),
        "missing_percentage": round(
            (missing_count / len(audit_customers)) * 100,
            3
        )
    })

customer_completeness_df = pd.DataFrame(
    customer_completeness
)

print("CUSTOMER DATA COMPLETENESS")
print("--------------------------")

display(
    customer_completeness_df
)

CUSTOMER DATA COMPLETENESS
--------------------------

       column  missing_count  missing_percentage
0  first_name              0               0.000
1   last_name              0               0.000
2       email              0               0.000
3       state              0               0.000
4      region            500               0.996

In [250]:
# ---------------------------------------------------------
# Step 124B:
# Customers With Multiple Missing Required Fields
# ---------------------------------------------------------

customer_missing_mask = (
    audit_customers[
        required_customer_columns
    ]
    .isna()
)

audit_customers_with_missing = audit_customers[
    customer_missing_mask.any(axis=1)
].copy()

audit_customers_with_missing[
    "missing_field_count"
] = (
    customer_missing_mask
    .sum(axis=1)
)

print(
    "Customers with at least one missing required field:",
    len(audit_customers_with_missing)
)

print(
    "Customers missing 2+ required fields:",
    (
        audit_customers_with_missing[
            "missing_field_count"
        ] >= 2
    ).sum()
)

display(
    audit_customers_with_missing[
        [
            "customer_id",
            "first_name",
            "last_name",
            "email",
            "state",
            "region",
            "missing_field_count"
        ]
    ].head(10)
)

Customers with at least one missing required field: 500
Customers missing 2+ required fields: 0

,customer_id,first_name,last_name,email,state,region,missing_field_count
147,C000148,Anthony,Adams,anthony.adams148@icloud.com,GA,NaN,1
199,C000200,Lisa,Baker,lisa.baker200@icloud.com,NY,NaN,1
262,C000263,William,King,william.king263@icloud.com,NC,NaN,1
292,C000293,Sandra,Baker,sandra.baker293@icloud.com,NY,NaN,1
314,C000315,Susan,Allen,susan.allen315@icloud.com,OH,NaN,1
508,C000509,George,Campbell,george.campbell509@yahoo.com,GA,NaN,1
659,C000660,Richard,Taylor,richard.taylor660@gmail.com,CO,NaN,1
708,C000709,Matthew,Nelson,matthew.nelson709@outlook.com,CA,NaN,1
725,C000726,Michelle,Young,michelle.young726@icloud.com,PA,NaN,1
821,C000822,Paul,Roberts,paul.roberts822@gmail.com,IL,NaN,1

In [251]:
# ---------------------------------------------------------
# Step 124C:
# Customer Missing-Value Ground Truth
# ---------------------------------------------------------

customer_missing_issues = (
    customer_issue_log_df[
        customer_issue_log_df["issue_type"]
        .astype(str)
        .str.contains(
            "missing|null|completeness",
            case=False,
            na=False
        )
    ]
    .copy()
)

print(
    "Ground-truth customer completeness issues:",
    len(customer_missing_issues)
)

display(
    customer_missing_issues.head(10)
)

Ground-truth customer completeness issues: 500

  customer_id     issue_type  column original_value injected_value
0     C033554  missing_value  region        Midwest            NaN
1     C009428  missing_value  region        Midwest            NaN
2     C000200  missing_value  region      Northeast            NaN
3     C012448  missing_value  region          South            NaN
4     C039490  missing_value  region           West            NaN
5     C042725  missing_value  region           West            NaN
6     C010823  missing_value  region           West            NaN
7     C049499  missing_value  region      Northeast            NaN
8     C004145  missing_value  region          South            NaN
9     C036959  missing_value  region      Northeast            NaN

In [252]:
# ---------------------------------------------------------
# Step 125A:
# Product Required-Field Completeness
# ---------------------------------------------------------

required_product_columns = [
    "product_name",
    "category",
    "subcategory",
    "brand",
    "unit_cost",
    "unit_price"
]

product_completeness = []

for column in required_product_columns:

    missing_count = audit_products[
        column
    ].isna().sum()

    product_completeness.append({
        "column": column,
        "missing_count": int(missing_count),
        "missing_percentage": round(
            (missing_count / len(audit_products)) * 100,
            3
        )
    })

product_completeness_df = pd.DataFrame(
    product_completeness
)

print("PRODUCT DATA COMPLETENESS")
print("-------------------------")

display(
    product_completeness_df
)

PRODUCT DATA COMPLETENESS
-------------------------

         column  missing_count  missing_percentage
0  product_name              0               0.000
1      category              0               0.000
2   subcategory             20               0.995
3         brand              0               0.000
4     unit_cost              0               0.000
5    unit_price              0               0.000

In [253]:
# ---------------------------------------------------------
# Step 125B:
# Products With Missing Required Fields
# ---------------------------------------------------------

product_missing_mask = (
    audit_products[
        required_product_columns
    ]
    .isna()
)

products_with_missing = audit_products[
    product_missing_mask.any(axis=1)
].copy()

products_with_missing[
    "missing_field_count"
] = (
    product_missing_mask
    .sum(axis=1)
)

print(
    "Products with at least one missing required field:",
    len(products_with_missing)
)

print(
    "Products missing 2+ required fields:",
    (
        products_with_missing[
            "missing_field_count"
        ] >= 2
    ).sum()
)

display(
    products_with_missing[
        [
            "product_id",
            "product_name",
            "category",
            "subcategory",
            "brand",
            "unit_cost",
            "unit_price",
            "missing_field_count"
        ]
    ].head(10)
)

Products with at least one missing required field: 20
Products missing 2+ required fields: 0

,product_id,product_name,category,subcategory,brand,unit_cost,unit_price,missing_field_count
29,P00030,NorthLane Men's Clothing 0030,Clothing,NaN,NorthLane,10.09,14.51,1
144,P00145,Velocity Sports Fitness Equipment 0145,Sports & Outdoors,NaN,Velocity Sports,468.79,629.09,1
173,P00174,PrimeDesk Printers 0174,Office Supplies,NaN,PrimeDesk,182.07,314.84,1
366,P00367,DeskPro Paper 0367,Office Supplies,NaN,DeskPro,347.23,624.46,1
461,P00462,Pulse Digital Smartphones 0462,Electronics,NaN,Pulse Digital,923.03,1134.82,1
702,P00703,DeskPro Writing Supplies 0703,Office Supplies,NaN,DeskPro,17.95,25.61,1
720,P00721,Oak & Stone Cookware 0721,Home & Kitchen,NaN,Oak & Stone,112.96,176.98,1
779,P00780,PaperPoint Desk Accessories 0780,Office Supplies,NaN,PaperPoint,303.13,510.30,1
805,P00806,Apex Devices Smartphones 0806,Electronics,NaN,Apex Devices,468.26,652.08,1
817,P00818,Stride Men's Clothing 0818,Clothing,NaN,Stride,128.23,244.13,1

In [254]:
# ---------------------------------------------------------
# Step 125C:
# Product Missing-Value Ground Truth
# ---------------------------------------------------------

product_missing_issues = (
    product_issue_log_df[
        product_issue_log_df["issue_type"]
        .astype(str)
        .str.contains(
            "missing|null|completeness",
            case=False,
            na=False
        )
    ]
    .copy()
)

print(
    "Ground-truth product completeness issues:",
    len(product_missing_issues)
)

display(
    product_missing_issues.head(10)
)

Ground-truth product completeness issues: 20

  product_id     issue_type       column    original_value injected_value
0     P01952  missing_value  subcategory       Smartphones           None
1     P01029  missing_value  subcategory       Smartphones           None
2     P00174  missing_value  subcategory          Printers           None
3     P00462  missing_value  subcategory       Smartphones           None
4     P01772  missing_value  subcategory           Camping           None
5     P01109  missing_value  subcategory  Writing Supplies           None
6     P00780  missing_value  subcategory  Desk Accessories           None
7     P00367  missing_value  subcategory             Paper           None
8     P00818  missing_value  subcategory    Men's Clothing           None
9     P01080  missing_value  subcategory          Cookware           None

In [255]:
# ---------------------------------------------------------
# Step 126A:
# Order Required-Field Completeness
# ---------------------------------------------------------

required_order_columns = [
    "order_id",
    "customer_id",
    "order_date",
    "sales_channel",
    "order_status",
    "shipping_city",
    "shipping_state",
    "shipping_region"
]

order_completeness = []

for column in required_order_columns:

    missing_count = audit_orders[column].isna().sum()

    order_completeness.append({
        "column": column,
        "missing_count": int(missing_count),
        "missing_percentage": round(
            (missing_count / len(audit_orders)) * 100,
            3
        )
    })

order_completeness_df = pd.DataFrame(
    order_completeness
)

print("ORDER DATA COMPLETENESS")
print("-----------------------")

display(order_completeness_df)

ORDER DATA COMPLETENESS
-----------------------

            column  missing_count  missing_percentage
0         order_id              0                0.00
1      customer_id            300                0.25
2       order_date              0                0.00
3    sales_channel              0                0.00
4     order_status              0                0.00
5    shipping_city              0                0.00
6   shipping_state              0                0.00
7  shipping_region              0                0.00

In [256]:
# ---------------------------------------------------------
# Step 126B:
# Orders With Missing Required Fields
# ---------------------------------------------------------

order_missing_mask = (
    audit_orders[
        required_order_columns
    ]
    .isna()
)

orders_with_missing = audit_orders[
    order_missing_mask.any(axis=1)
].copy()

orders_with_missing[
    "missing_field_count"
] = (
    order_missing_mask
    .sum(axis=1)
)

print(
    "Orders with at least one missing required field:",
    len(orders_with_missing)
)

print(
    "Orders missing 2+ required fields:",
    (
        orders_with_missing[
            "missing_field_count"
        ] >= 2
    ).sum()
)

display(
    orders_with_missing[
        [
            "order_id",
            "customer_id",
            "order_date",
            "sales_channel",
            "order_status",
            "shipping_city",
            "shipping_state",
            "shipping_region",
            "missing_field_count"
        ]
    ].head(10)
)

Orders with at least one missing required field: 300
Orders missing 2+ required fields: 0

,order_id,customer_id,order_date,sales_channel,order_status,shipping_city,shipping_state,shipping_region,missing_field_count
404,O0000405,NaN,2025-03-10,Website,Completed,Austin,TX,South,1
419,O0000420,NaN,2023-02-15,Physical Store,Completed,Seattle,WA,West,1
847,O0000848,NaN,2024-11-20,Website,Completed,Minneapolis,MN,Midwest,1
1084,O0001085,NaN,2024-04-11,Website,Completed,Detroit,MI,Midwest,1
1350,O0001351,NaN,2024-01-30,Website,Completed,San Francisco,CA,West,1
1504,O0001505,NaN,2024-08-26,Physical Store,Completed,Miami,FL,South,1
2091,O0002092,NaN,2025-10-06,Physical Store,Completed,Los Angeles,CA,West,1
2093,O0002094,NaN,2025-06-29,Website,Completed,Pittsburgh,PA,Northeast,1
2578,O0002579,NaN,2025-08-02,Physical Store,Completed,Denver,CO,West,1
2902,O0002903,NaN,2024-08-29,Mobile App,Completed,Orlando,FL,South,1

In [257]:
# ---------------------------------------------------------
# Step 126C:
# Order Missing-Value Ground Truth
# ---------------------------------------------------------

order_missing_issues = (
    order_issue_log_df[
        order_issue_log_df["issue_type"]
        .astype(str)
        .str.contains(
            "missing|null|completeness",
            case=False,
            na=False
        )
    ]
    .copy()
)

print(
    "Ground-truth order completeness issues:",
    len(order_missing_issues)
)

display(
    order_missing_issues.head(10)
)

Ground-truth order completeness issues: 300

   order_id     issue_type       column original_value injected_value
0  O0114037  missing_value  customer_id        C003950           None
1  O0073152  missing_value  customer_id        C027854           None
2  O0017918  missing_value  customer_id        C033244           None
3  O0096625  missing_value  customer_id        C008145           None
4  O0003479  missing_value  customer_id        C048721           None
5  O0094634  missing_value  customer_id        C016917           None
6  O0004081  missing_value  customer_id        C027827           None
7  O0007386  missing_value  customer_id        C028866           None
8  O0061852  missing_value  customer_id        C029069           None
9  O0001351  missing_value  customer_id        C015438           None

In [258]:
# ---------------------------------------------------------
# Step 127A:
# Order-Item Required-Field Completeness
# ---------------------------------------------------------

required_order_item_columns = [
    "order_item_id",
    "order_id",
    "product_id",
    "quantity",
    "unit_price",
    "discount_pct"
]

order_item_completeness = []

for column in required_order_item_columns:

    missing_count = audit_order_items[column].isna().sum()

    order_item_completeness.append({
        "column": column,
        "missing_count": int(missing_count),
        "missing_percentage": round(
            (missing_count / len(audit_order_items)) * 100,
            3
        )
    })

order_item_completeness_df = pd.DataFrame(
    order_item_completeness
)

print("ORDER-ITEM DATA COMPLETENESS")
print("----------------------------")

display(order_item_completeness_df)

ORDER-ITEM DATA COMPLETENESS
----------------------------

          column  missing_count  missing_percentage
0  order_item_id              0                 0.0
1       order_id              0                 0.0
2     product_id              0                 0.0
3       quantity              0                 0.0
4     unit_price              0                 0.0
5   discount_pct              0                 0.0

In [259]:
# ---------------------------------------------------------
# Step 127B:
# Order Items With Missing Required Fields
# ---------------------------------------------------------

order_item_missing_mask = (
    audit_order_items[
        required_order_item_columns
    ]
    .isna()
)

order_items_with_missing = audit_order_items[
    order_item_missing_mask.any(axis=1)
].copy()

order_items_with_missing[
    "missing_field_count"
] = (
    order_item_missing_mask
    .sum(axis=1)
)

print(
    "Order items with at least one missing required field:",
    len(order_items_with_missing)
)

print(
    "Order items missing 2+ required fields:",
    (
        order_items_with_missing[
            "missing_field_count"
        ] >= 2
    ).sum()
)

display(
    order_items_with_missing[
        [
            "order_item_id",
            "order_id",
            "product_id",
            "quantity",
            "unit_price",
            "discount_pct",
            "missing_field_count"
        ]
    ].head(10)
)

Order items with at least one missing required field: 307309
Order items missing 2+ required fields: 0

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,missing_field_count
0,NaN,NaN,NaN,NaN,NaN,NaN,0
1,NaN,NaN,NaN,NaN,NaN,NaN,0
2,NaN,NaN,NaN,NaN,NaN,NaN,0
3,NaN,NaN,NaN,NaN,NaN,NaN,0
4,NaN,NaN,NaN,NaN,NaN,NaN,0
5,NaN,NaN,NaN,NaN,NaN,NaN,0
6,NaN,NaN,NaN,NaN,NaN,NaN,0
7,NaN,NaN,NaN,NaN,NaN,NaN,0
8,NaN,NaN,NaN,NaN,NaN,NaN,0
9,NaN,NaN,NaN,NaN,NaN,NaN,0

In [260]:
# ---------------------------------------------------------
# Step 127C:
# Order-Item Missing-Value Ground Truth
# ---------------------------------------------------------

order_item_missing_issues = (
    order_item_issue_log_df[
        order_item_issue_log_df["issue_type"]
        .astype(str)
        .str.contains(
            "missing|null|completeness",
            case=False,
            na=False
        )
    ]
    .copy()
)

print(
    "Ground-truth order-item completeness issues:",
    len(order_item_missing_issues)
)

display(
    order_item_missing_issues.head(10)
)

Ground-truth order-item completeness issues: 0

Empty DataFrame
Columns: [order_item_id, issue_type, column, original_value, injected_value]
Index: []

In [261]:
# ---------------------------------------------------------
# Step 128A:
# Payment Required-Field Completeness
# ---------------------------------------------------------

required_payment_columns = [
    "payment_id",
    "order_id",
    "payment_date",
    "payment_method",
    "payment_status",
    "payment_amount"
]

payment_completeness = []

for column in required_payment_columns:

    missing_count = audit_payments[column].isna().sum()

    payment_completeness.append({
        "column": column,
        "missing_count": int(missing_count),
        "missing_percentage": round(
            (missing_count / len(audit_payments)) * 100,
            3
        )
    })

payment_completeness_df = pd.DataFrame(
    payment_completeness
)

print("PAYMENT DATA COMPLETENESS")
print("-------------------------")

display(payment_completeness_df)

PAYMENT DATA COMPLETENESS
-------------------------

           column  missing_count  missing_percentage
0      payment_id              0                 0.0
1        order_id              0                 0.0
2    payment_date              0                 0.0
3  payment_method              0                 0.0
4  payment_status              0                 0.0
5  payment_amount              0                 0.0

In [262]:
# ---------------------------------------------------------
# Step 128B:
# Payments With Missing Required Fields
# ---------------------------------------------------------

payment_missing_mask = (
    audit_payments[
        required_payment_columns
    ]
    .isna()
)

payments_with_missing = audit_payments[
    payment_missing_mask.any(axis=1)
].copy()

payments_with_missing[
    "missing_field_count"
] = (
    payment_missing_mask
    .sum(axis=1)
)

print(
    "Payments with at least one missing required field:",
    len(payments_with_missing)
)

print(
    "Payments missing 2+ required fields:",
    (
        payments_with_missing[
            "missing_field_count"
        ] >= 2
    ).sum()
)

display(
    payments_with_missing[
        [
            "payment_id",
            "order_id",
            "payment_date",
            "payment_method",
            "payment_status",
            "payment_amount",
            "missing_field_count"
        ]
    ].head(10)
)

Payments with at least one missing required field: 120100
Payments missing 2+ required fields: 0

,payment_id,order_id,payment_date,payment_method,payment_status,payment_amount,missing_field_count
0,NaN,NaN,NaN,NaN,NaN,NaN,0
1,NaN,NaN,NaN,NaN,NaN,NaN,0
2,NaN,NaN,NaN,NaN,NaN,NaN,0
3,NaN,NaN,NaN,NaN,NaN,NaN,0
4,NaN,NaN,NaN,NaN,NaN,NaN,0
5,NaN,NaN,NaN,NaN,NaN,NaN,0
6,NaN,NaN,NaN,NaN,NaN,NaN,0
7,NaN,NaN,NaN,NaN,NaN,NaN,0
8,NaN,NaN,NaN,NaN,NaN,NaN,0
9,NaN,NaN,NaN,NaN,NaN,NaN,0

In [263]:
# ---------------------------------------------------------
# Step 128C:
# Payment Missing-Value Ground Truth
# ---------------------------------------------------------

payment_missing_issues = (
    payment_issue_log_df[
        payment_issue_log_df["issue_type"]
        .astype(str)
        .str.contains(
            "missing|null|completeness",
            case=False,
            na=False
        )
    ]
    .copy()
)

print(
    "Ground-truth payment completeness issues:",
    len(payment_missing_issues)
)

display(
    payment_missing_issues.head(10)
)

Ground-truth payment completeness issues: 0

Empty DataFrame
Columns: [payment_id, issue_type, column, original_value, injected_value]
Index: []

In [264]:
# ---------------------------------------------------------
# Step 129A:
# Return Required-Field Completeness
# ---------------------------------------------------------

required_return_columns = [
    "return_id",
    "order_id",
    "order_item_id",
    "product_id",
    "return_date",
    "return_quantity",
    "return_reason",
    "refund_amount"
]

return_completeness = []

for column in required_return_columns:

    missing_count = audit_returns[column].isna().sum()

    return_completeness.append({
        "column": column,
        "missing_count": int(missing_count),
        "missing_percentage": round(
            (missing_count / len(audit_returns)) * 100,
            3
        )
    })

return_completeness_df = pd.DataFrame(
    return_completeness
)

print("RETURN DATA COMPLETENESS")
print("------------------------")

display(return_completeness_df)

RETURN DATA COMPLETENESS
------------------------

            column  missing_count  missing_percentage
0        return_id              0               0.000
1         order_id              0               0.000
2    order_item_id              0               0.000
3       product_id              0               0.000
4      return_date              0               0.000
5  return_quantity              0               0.000
6    return_reason             17               0.259
7    refund_amount              0               0.000

In [265]:
# ---------------------------------------------------------
# Step 129B:
# Returns With Missing Required Fields
# ---------------------------------------------------------

return_missing_mask = (
    audit_returns[
        required_return_columns
    ]
    .isna()
)

returns_with_missing = audit_returns[
    return_missing_mask.any(axis=1)
].copy()

returns_with_missing[
    "missing_field_count"
] = (
    return_missing_mask
    .sum(axis=1)
)

print(
    "Returns with at least one missing required field:",
    len(returns_with_missing)
)

print(
    "Returns missing 2+ required fields:",
    (
        returns_with_missing[
            "missing_field_count"
        ] >= 2
    ).sum()
)

display(
    returns_with_missing[
        [
            "return_id",
            "order_id",
            "order_item_id",
            "product_id",
            "return_date",
            "return_quantity",
            "return_reason",
            "refund_amount",
            "missing_field_count"
        ]
    ].head(10)
)

Returns with at least one missing required field: 17
Returns missing 2+ required fields: 0

,return_id,order_id,order_item_id,product_id,return_date,return_quantity,return_reason,refund_amount,missing_field_count
470,R0000471,O0008358,OI00021541,P00562,2023-07-17,1,NaN,194.44,1
493,R0000494,O0008978,OI00023102,P00663,2024-01-18,1,NaN,172.01,1
559,R0000560,O0010233,OI00026316,P00455,2024-04-13,1,NaN,211.19,1
726,R0000727,O0013662,OI00035136,P00642,2024-07-24,4,NaN,2728.88,1
876,R0000877,O0016036,OI00041293,P01177,2024-09-11,1,NaN,474.20,1
1821,R0001822,O0031945,OI00081747,P00164,2023-10-24,1,NaN,180.58,1
1865,R0001866,O0032616,OI00083471,P01256,2025-09-27,1,NaN,236.78,1
2105,R0002106,O0037171,OI00095112,P01819,2023-11-21,1,NaN,625.63,1
2428,R0002429,O0042851,OI00109642,P00816,2025-10-20,1,NaN,216.82,1
3699,R0003700,O0066244,OI00169623,P01859,2025-02-10,1,NaN,624.94,1

In [266]:
# ---------------------------------------------------------
# Step 129C:
# Return Missing-Value Ground Truth
# ---------------------------------------------------------

return_missing_issues = (
    return_issue_log_df[
        return_issue_log_df["issue_type"]
        .astype(str)
        .str.contains(
            "missing|null|completeness",
            case=False,
            na=False
        )
    ]
    .copy()
)

print(
    "Ground-truth return completeness issues:",
    len(return_missing_issues)
)

display(
    return_missing_issues.head(10)
)

Ground-truth return completeness issues: 0

Empty DataFrame
Columns: [return_id, issue_type, column, original_value, injected_value]
Index: []

In [267]:
# ---------------------------------------------------------
# Step 130A:
# Primary-Key Completeness Audit
# ---------------------------------------------------------

primary_keys = {
    "customers": (audit_customers, "customer_id"),
    "products": (audit_products, "product_id"),
    "orders": (audit_orders, "order_id"),
    "order_items": (audit_order_items, "order_item_id"),
    "payments": (audit_payments, "payment_id"),
    "returns": (audit_returns, "return_id")
}

primary_key_results = []

for dataset_name, (df_data, key_column) in primary_keys.items():

    null_count = df_data[key_column].isna().sum()

    unique_count = df_data[key_column].nunique(
        dropna=True
    )

    duplicate_rows = df_data[
        key_column
    ].duplicated().sum()

    primary_key_results.append({
        "dataset": dataset_name,
        "primary_key": key_column,
        "total_rows": len(df_data),
        "null_keys": int(null_count),
        "unique_keys": int(unique_count),
        "duplicate_rows": int(duplicate_rows)
    })

primary_key_audit_df = pd.DataFrame(
    primary_key_results
)

print("PRIMARY-KEY INTEGRITY AUDIT")
print("---------------------------")

display(primary_key_audit_df)

PRIMARY-KEY INTEGRITY AUDIT
---------------------------

,dataset,primary_key,total_rows,null_keys,unique_keys,duplicate_rows
0,customers,customer_id,50200,0,50000,200
1,products,product_id,2010,0,2000,10
2,orders,order_id,120100,0,120000,100
3,order_items,order_item_id,307309,0,307159,150
4,payments,payment_id,120100,0,120000,100
5,returns,return_id,6560,0,6510,50

In [268]:
# ---------------------------------------------------------
# Step 130B:
# Summarize Primary-Key Failures
# ---------------------------------------------------------

primary_key_audit_df[
    "status"
] = primary_key_audit_df.apply(
    lambda row:
        "PASS"
        if (
            row["null_keys"] == 0
            and row["duplicate_rows"] == 0
        )
        else "REVIEW",
    axis=1
)

print("PRIMARY-KEY STATUS")
print("------------------")

display(
    primary_key_audit_df[
        [
            "dataset",
            "primary_key",
            "null_keys",
            "duplicate_rows",
            "status"
        ]
    ]
)

PRIMARY-KEY STATUS
------------------

       dataset    primary_key  null_keys  duplicate_rows  status
0    customers    customer_id          0             200  REVIEW
1     products     product_id          0              10  REVIEW
2       orders       order_id          0             100  REVIEW
3  order_items  order_item_id          0             150  REVIEW
4     payments     payment_id          0             100  REVIEW
5      returns      return_id          0              50  REVIEW

In [269]:
# ---------------------------------------------------------
# Step 131A:
# Physical Rows Affected by Duplicate Primary Keys
# ---------------------------------------------------------

duplicate_impact_results = []

for dataset_name, (df_data, key_column) in primary_keys.items():

    duplicated_mask = df_data[key_column].duplicated(
        keep=False
    )

    duplicate_rows_affected = duplicated_mask.sum()

    duplicate_id_count = df_data.loc[
        duplicated_mask,
        key_column
    ].nunique()

    duplicate_impact_results.append({
        "dataset": dataset_name,
        "primary_key": key_column,
        "rows_affected_by_duplicates": int(
            duplicate_rows_affected
        ),
        "duplicate_ids": int(
            duplicate_id_count
        )
    })

duplicate_impact_df = pd.DataFrame(
    duplicate_impact_results
)

print("DUPLICATE RECORD IMPACT")
print("-----------------------")

display(duplicate_impact_df)

DUPLICATE RECORD IMPACT
-----------------------

       dataset    primary_key  rows_affected_by_duplicates  duplicate_ids
0    customers    customer_id                          400            200
1     products     product_id                           20             10
2       orders       order_id                          200            100
3  order_items  order_item_id                          300            150
4     payments     payment_id                          200            100
5      returns      return_id                          100             50

In [270]:
# ---------------------------------------------------------
# Step 131B:
# Overall Duplicate Impact
# ---------------------------------------------------------

total_duplicate_rows_affected = (
    duplicate_impact_df[
        "rows_affected_by_duplicates"
    ].sum()
)

total_duplicate_ids = (
    duplicate_impact_df[
        "duplicate_ids"
    ].sum()
)

print(
    "Total physical rows involved in duplicates:",
    int(total_duplicate_rows_affected)
)

print(
    "Total duplicate identifiers:",
    int(total_duplicate_ids)
)

Total physical rows involved in duplicates: 1220
Total duplicate identifiers: 610

In [271]:
# ---------------------------------------------------------
# Step 131C:
# Classify Duplicate Impact
# ---------------------------------------------------------

duplicate_impact_df["severity"] = (
    duplicate_impact_df[
        "rows_affected_by_duplicates"
    ]
    .apply(
        lambda x:
            "High" if x >= 100
            else "Medium" if x > 0
            else "None"
    )
)

display(
    duplicate_impact_df
)

,dataset,primary_key,rows_affected_by_duplicates,duplicate_ids,severity
0,customers,customer_id,400,200,High
1,products,product_id,20,10,Medium
2,orders,order_id,200,100,High
3,order_items,order_item_id,300,150,High
4,payments,payment_id,200,100,High
5,returns,return_id,100,50,High

In [272]:
# ---------------------------------------------------------
# Step 132A:
# Data-Type Consistency Profile
# ---------------------------------------------------------

dtype_results = []

for dataset_name, df_data in datasets.items():

    for column in df_data.columns:

        dtype_results.append({
            "dataset": dataset_name,
            "column": column,
            "dtype": str(
                df_data[column].dtype
            )
        })

dtype_audit_df = pd.DataFrame(
    dtype_results
)

print("DATA-TYPE PROFILE")
print("-----------------")

display(dtype_audit_df)

DATA-TYPE PROFILE
-----------------

        dataset            column           dtype
0     customers       customer_id             str
1     customers        first_name             str
2     customers         last_name             str
3     customers             email             str
4     customers             phone             str
5     customers              city             str
6     customers             state             str
7     customers            region             str
8     customers  customer_segment             str
9     customers       signup_date             str
10     products        product_id             str
11     products      product_name             str
12     products          category             str
13     products       subcategory             str
14     products             brand             str
15     products         unit_cost         float64
16     products        unit_price         float64
17     products       supplier_id             str
18     products       launch_date  datetime64[us]
19     products    product_status             str
20       orders          order_id             str
21       orders       customer_id             str
22       orders        order_date             str
23       orders     sales_channel             str
24       orders      order_status             str
25       orders    payment_method             str
26       orders     shipping_city             str
27       orders    shipping_state             str
28       orders   shipping_region             str
29  order_items     order_item_id             str
30  order_items          order_id             str
31  order_items        product_id             str
32  order_items          quantity           int64
33  order_items        unit_price         float64
34  order_items      discount_pct         float64
35  order_items         unit_cost         float64
36     payments        payment_id             str
37     payments          order_id             str
38     payments      payment_date             str
39     payments    payment_method             str
40     payments    payment_status             str
41     payments    payment_amount         float64
42      returns         return_id             str
43      returns     order_item_id             str
44      returns          order_id             str
45      returns        product_id             str
46      returns       return_date             str
47      returns   return_quantity           int64
48      returns     return_reason             str
49      returns     refund_amount         float64

In [273]:
# ---------------------------------------------------------
# Step 132B:
# Date Column Data-Type Check
# ---------------------------------------------------------

date_keywords = [
    "date",
    "datetime",
    "timestamp"
]

date_columns = dtype_audit_df[
    dtype_audit_df["column"].str.lower().apply(
        lambda column_name:
            any(
                keyword in column_name
                for keyword in date_keywords
            )
    )
].copy()

print("DATE/TIME COLUMN TYPES")
print("----------------------")

display(date_columns)

DATE/TIME COLUMN TYPES
----------------------

      dataset        column           dtype
9   customers   signup_date             str
18   products   launch_date  datetime64[us]
22     orders    order_date             str
38   payments  payment_date             str
46    returns   return_date             str

In [274]:
# ---------------------------------------------------------
# Step 132C:
# Identify Date Columns Stored as Object/String
# ---------------------------------------------------------

object_date_columns = date_columns[
    date_columns["dtype"].isin(
        ["object", "string"]
    )
].copy()

print(
    "Date columns stored as object/string:",
    len(object_date_columns)
)

display(
    object_date_columns
)

Date columns stored as object/string: 0

Empty DataFrame
Columns: [dataset, column, dtype]
Index: []

In [275]:
# ---------------------------------------------------------
# Step 133A:
# Consolidated Numeric Range Audit
# ---------------------------------------------------------

numeric_rules = {
    "products": {
        "unit_cost": {"min": 0},
        "unit_price": {"min": 0}
    },

    "order_items": {
        "quantity": {"min": 1},
        "unit_price": {"min": 0},
        "discount_pct": {"min": 0, "max": 0.30}
    },

    "payments": {
        "payment_amount": {"min": 0}
    },

    "returns": {
        "return_quantity": {"min": 1},
        "refund_amount": {"min": 0}
    }
}

numeric_range_results = []

for dataset_name, column_rules in numeric_rules.items():

    df_data = datasets[dataset_name]

    for column, rules in column_rules.items():

        invalid_mask = pd.Series(
            False,
            index=df_data.index
        )

        if "min" in rules:
            invalid_mask |= (
                df_data[column] < rules["min"]
            )

        if "max" in rules:
            invalid_mask |= (
                df_data[column] > rules["max"]
            )

        invalid_count = invalid_mask.sum()

        numeric_range_results.append({
            "dataset": dataset_name,
            "column": column,
            "invalid_count": int(invalid_count),
            "minimum_observed": df_data[column].min(),
            "maximum_observed": df_data[column].max(),
            "allowed_min": rules.get("min"),
            "allowed_max": rules.get("max")
        })

numeric_range_audit_df = pd.DataFrame(
    numeric_range_results
)

print("NUMERIC RANGE AUDIT")
print("-------------------")

display(numeric_range_audit_df)

NUMERIC RANGE AUDIT
-------------------

,dataset,column,invalid_count,minimum_observed,maximum_observed,allowed_min,allowed_max
0,products,unit_cost,10,-1188.35,1195.79,0,NaN
1,products,unit_price,0,2.59,1911.25,0,NaN
2,order_items,quantity,300,-2.00,5.00,1,NaN
3,order_items,unit_price,0,2.59,2808.83,0,NaN
4,order_items,discount_pct,150,0.00,1.10,0,0.3
5,payments,payment_amount,0,1.81,13739.75,0,NaN
6,returns,return_quantity,0,1.00,7.00,1,NaN
7,returns,refund_amount,0,2.20,6652.52,0,NaN

In [276]:
# ---------------------------------------------------------
# Step 133B:
# Numeric Rules With Violations
# ---------------------------------------------------------

numeric_violations = (
    numeric_range_audit_df[
        numeric_range_audit_df["invalid_count"] > 0
    ]
    .copy()
)

print(
    "Numeric rules with violations:",
    len(numeric_violations)
)

display(
    numeric_violations
)

Numeric rules with violations: 3

,dataset,column,invalid_count,minimum_observed,maximum_observed,allowed_min,allowed_max
0,products,unit_cost,10,-1188.35,1195.79,0,NaN
2,order_items,quantity,300,-2.00,5.00,1,NaN
4,order_items,discount_pct,150,0.00,1.10,0,0.3

In [277]:
# ---------------------------------------------------------
# Step 133C:
# Total Numeric Violations
# ---------------------------------------------------------

total_numeric_violations = (
    numeric_range_audit_df[
        "invalid_count"
    ].sum()
)

print(
    "Total numeric rule violations:",
    int(total_numeric_violations)
)

Total numeric rule violations: 460

In [278]:
# ---------------------------------------------------------
# Step 134A:
# Derive Valid Status Domains From Ground Truth
# ---------------------------------------------------------

valid_order_statuses = set(
    orders_ground_truth_df[
        "order_status"
    ]
    .dropna()
    .unique()
)

valid_payment_statuses = set(
    payments_ground_truth_df[
        "payment_status"
    ]
    .dropna()
    .unique()
)

print("Valid order statuses:")
for status in sorted(valid_order_statuses):
    print("-", status)

print("\nValid payment statuses:")
for status in sorted(valid_payment_statuses):
    print("-", status)

Valid order statuses:
- Cancelled
- Completed
- Returned

Valid payment statuses:
- Failed
- Refunded
- Successful

In [279]:
# ---------------------------------------------------------
# Step 134B:
# Detect Invalid Order Statuses
# ---------------------------------------------------------

invalid_order_statuses = audit_orders[
    audit_orders["order_status"].notna()
    &
    ~audit_orders["order_status"].isin(
        valid_order_statuses
    )
].copy()

print("ORDER STATUS VALIDITY")
print("---------------------")

print(
    "Invalid order-status records:",
    len(invalid_order_statuses)
)

display(
    invalid_order_statuses[
        [
            "order_id",
            "customer_id",
            "order_date",
            "order_status"
        ]
    ].head(10)
)

ORDER STATUS VALIDITY
---------------------
Invalid order-status records: 0

Empty DataFrame
Columns: [order_id, customer_id, order_date, order_status]
Index: []

In [280]:
# ---------------------------------------------------------
# Step 134C:
# Detect Invalid Payment Statuses
# ---------------------------------------------------------

invalid_payment_statuses = audit_payments[
    audit_payments["payment_status"].notna()
    &
    ~audit_payments["payment_status"].isin(
        valid_payment_statuses
    )
].copy()

print("PAYMENT STATUS VALIDITY")
print("-----------------------")

print(
    "Invalid payment-status records:",
    len(invalid_payment_statuses)
)

display(
    invalid_payment_statuses[
        [
            "payment_id",
            "order_id",
            "payment_status",
            "payment_amount"
        ]
    ].head(10)
)

PAYMENT STATUS VALIDITY
-----------------------
Invalid payment-status records: 0

Empty DataFrame
Columns: [payment_id, order_id, payment_status, payment_amount]
Index: []

In [281]:
# ---------------------------------------------------------
# Step 134D:
# Consolidated Status Validity Results
# ---------------------------------------------------------

status_validity_summary = pd.DataFrame([
    {
        "dataset": "orders",
        "column": "order_status",
        "invalid_records": len(
            invalid_order_statuses
        )
    },
    {
        "dataset": "payments",
        "column": "payment_status",
        "invalid_records": len(
            invalid_payment_statuses
        )
    }
])

print("STATUS VALIDITY SUMMARY")
print("-----------------------")

display(
    status_validity_summary
)

STATUS VALIDITY SUMMARY
-----------------------

    dataset          column  invalid_records
0    orders    order_status                0
1  payments  payment_status                0

In [282]:
# ---------------------------------------------------------
# Step 135A:
# Derive Valid Sales Channels From Ground Truth
# ---------------------------------------------------------

valid_sales_channels = set(
    orders_ground_truth_df[
        "sales_channel"
    ]
    .dropna()
    .unique()
)

print("Valid sales channels:")

for channel in sorted(valid_sales_channels):
    print("-", channel)

Valid sales channels:
- Mobile App
- Physical Store
- Website

In [283]:
# ---------------------------------------------------------
# Step 135B:
# Detect Invalid Sales Channels
# ---------------------------------------------------------

invalid_sales_channels = audit_orders[
    audit_orders["sales_channel"].notna()
    &
    ~audit_orders["sales_channel"].isin(
        valid_sales_channels
    )
].copy()

print("SALES CHANNEL VALIDITY")
print("----------------------")

print(
    "Invalid sales-channel records:",
    len(invalid_sales_channels)
)

print("\nInvalid values detected:")

print(
    invalid_sales_channels[
        "sales_channel"
    ].value_counts()
)

display(
    invalid_sales_channels[
        [
            "order_id",
            "customer_id",
            "order_date",
            "sales_channel",
            "order_status"
        ]
    ].head(10)
)

SALES CHANNEL VALIDITY
----------------------
Invalid sales-channel records: 100

Invalid values detected:
sales_channel
Phone Order     32
Unknown         26
Social Media    26
Marketplace     16
Name: count, dtype: int64

      order_id customer_id  order_date sales_channel order_status
187   O0000188     C013559  2025-06-10       Unknown    Completed
481   O0000482     C036773  2025-03-04   Phone Order    Completed
735   O0000736     C023987  2025-11-04   Marketplace    Completed
2517  O0002518     C001121  2023-01-22   Phone Order    Completed
3930  O0003931     C043578  2025-01-12   Marketplace    Completed
4721  O0004722     C020445  2023-02-17   Phone Order    Completed
5577  O0005578     C034691  2025-04-26       Unknown    Completed
5743  O0005744     C027667  2024-12-11  Social Media    Completed
8596  O0008597     C001843  2025-09-27   Marketplace    Completed
9791  O0009792     C042737  2025-12-22   Phone Order    Completed

In [284]:
# ---------------------------------------------------------
# Step 135C:
# Sales-Channel Ground-Truth Issues
# ---------------------------------------------------------

sales_channel_issues = (
    order_issue_log_df[
        order_issue_log_df["column"]
        .astype(str)
        .str.lower()
        .eq("sales_channel")
    ]
    .copy()
)

detected_sales_channel_issues = len(
    invalid_sales_channels
)

expected_sales_channel_issues = len(
    sales_channel_issues
)

print(
    "Detected invalid sales channels:",
    detected_sales_channel_issues
)

print(
    "Ground-truth sales-channel issues:",
    expected_sales_channel_issues
)

if (
    detected_sales_channel_issues
    == expected_sales_channel_issues
):
    print(
        f"\nPASS - Expected "
        f"{expected_sales_channel_issues}, "
        f"detected "
        f"{detected_sales_channel_issues}."
    )
else:
    print(
        f"\nREVIEW - Expected "
        f"{expected_sales_channel_issues}, "
        f"detected "
        f"{detected_sales_channel_issues}."
    )

Detected invalid sales channels: 100
Ground-truth sales-channel issues: 100

PASS - Expected 100, detected 100.

In [285]:
# ---------------------------------------------------------
# Step 136A:
# Prepare Order vs Customer Signup Temporal Check
# ---------------------------------------------------------

orders_temporal = audit_orders.copy()
customers_temporal = audit_customers.copy()

# Convert dates safely
orders_temporal["order_date"] = pd.to_datetime(
    orders_temporal["order_date"],
    errors="coerce"
)

customers_temporal["signup_date"] = pd.to_datetime(
    customers_temporal["signup_date"],
    errors="coerce"
)

# Use one customer record per ID so intentional
# customer duplicates do not multiply order rows
customer_signup_lookup = (
    customers_temporal[
        ["customer_id", "signup_date"]
    ]
    .dropna(subset=["customer_id"])
    .drop_duplicates(
        subset=["customer_id"],
        keep="first"
    )
)

orders_signup_check = (
    orders_temporal.merge(
        customer_signup_lookup,
        on="customer_id",
        how="inner"
    )
)

print(
    "Orders available for temporal check:",
    len(orders_signup_check)
)

Orders available for temporal check: 119600

In [286]:
# ---------------------------------------------------------
# Step 136B:
# Detect Orders Before Customer Signup
# ---------------------------------------------------------

orders_before_signup = (
    orders_signup_check[
        orders_signup_check["order_date"]
        <
        orders_signup_check["signup_date"]
    ]
    .copy()
)

orders_before_signup["days_before_signup"] = (
    orders_before_signup["signup_date"]
    -
    orders_before_signup["order_date"]
).dt.days

print("ORDER / CUSTOMER TEMPORAL CONSISTENCY")
print("-------------------------------------")

print(
    "Orders before customer signup:",
    len(orders_before_signup)
)

display(
    orders_before_signup[
        [
            "order_id",
            "customer_id",
            "signup_date",
            "order_date",
            "days_before_signup"
        ]
    ].head(10)
)

ORDER / CUSTOMER TEMPORAL CONSISTENCY
-------------------------------------
Orders before customer signup: 150

      order_id customer_id signup_date order_date  days_before_signup
173   O0000176     C003231  2025-01-30 2025-01-26                   4
1098  O0001108     C044064  2025-12-03 2025-10-18                  46
1220  O0001230     C011792  2023-02-14 2023-01-06                  39
1253  O0001263     C024353  2022-06-09 2022-05-28                  12
2193  O0002208     C003807  2022-02-23 2021-11-25                  90
2283  O0002298     C045219  2023-02-21 2023-02-15                   6
2824  O0002842     C037993  2024-06-05 2024-05-18                  18
3647  O0003672     C005918  2023-08-07 2023-07-19                  19
4231  O0004259     C048478  2024-08-26 2024-07-22                  35
4681  O0004709     C031575  2021-01-18 2021-01-16                   2

In [287]:
# ---------------------------------------------------------
# Step 136C:
# Verify Against Ground Truth
# ---------------------------------------------------------

order_temporal_issues = (
    order_issue_log_df[
        (
            order_issue_log_df["column"]
            .astype(str)
            .str.lower()
            == "order_date"
        )
        &
        (
            order_issue_log_df["issue_type"]
            .astype(str)
            .str.contains(
                "temporal",
                case=False,
                na=False
            )
        )
    ]
    .copy()
)

detected = len(orders_before_signup)
expected = len(order_temporal_issues)

print(
    "Detected orders before signup:",
    detected
)

print(
    "Ground-truth temporal issues:",
    expected
)

print(
    "\nPASS" if detected == expected else "\nREVIEW",
    f"- Expected {expected}, detected {detected}"
)

Detected orders before signup: 150
Ground-truth temporal issues: 150

PASS - Expected 150, detected 150

In [288]:
# ---------------------------------------------------------
# Step 137A:
# Prepare Payment vs Order Temporal Check
# ---------------------------------------------------------

payments_temporal = audit_payments.copy()
orders_payment_temporal = audit_orders.copy()

payments_temporal["payment_date"] = pd.to_datetime(
    payments_temporal["payment_date"],
    errors="coerce"
)

orders_payment_temporal["order_date"] = pd.to_datetime(
    orders_payment_temporal["order_date"],
    errors="coerce"
)

# Use one order record per order_id so intentional
# duplicate orders do not multiply payment records
order_date_lookup = (
    orders_payment_temporal[
        ["order_id", "order_date"]
    ]
    .dropna(subset=["order_id"])
    .drop_duplicates(
        subset=["order_id"],
        keep="first"
    )
)

payments_date_check = (
    payments_temporal.merge(
        order_date_lookup,
        on="order_id",
        how="inner"
    )
)

print(
    "Payments available for temporal check:",
    len(payments_date_check)
)

Payments available for temporal check: 119950

In [289]:
# ---------------------------------------------------------
# Step 137B:
# Detect Payments Before Order Date
# ---------------------------------------------------------

payments_before_order = (
    payments_date_check[
        payments_date_check["payment_date"]
        <
        payments_date_check["order_date"]
    ]
    .copy()
)

payments_before_order["days_before_order"] = (
    payments_before_order["order_date"]
    -
    payments_before_order["payment_date"]
).dt.days

print("PAYMENT / ORDER TEMPORAL CONSISTENCY")
print("------------------------------------")

print(
    "Payments before order date:",
    len(payments_before_order)
)

display(
    payments_before_order[
        [
            "payment_id",
            "order_id",
            "order_date",
            "payment_date",
            "days_before_order"
        ]
    ].head(10)
)

PAYMENT / ORDER TEMPORAL CONSISTENCY
------------------------------------
Payments before order date: 100

       payment_id  order_id order_date payment_date  days_before_order
2331   PAY0002337  O0002337 2024-05-28   2024-05-26                  2
3752   PAY0003760  O0003760 2025-11-05   2025-11-02                  3
4187   PAY0004196  O0004196 2024-09-17   2024-09-16                  1
5178   PAY0005188  O0005188 2024-04-19   2024-04-17                  2
8554   PAY0008569  O0008569 2025-03-21   2025-03-16                  5
9181   PAY0009197  O0009197 2025-11-28   2025-11-21                  7
9344   PAY0009360  O0009360 2024-12-28   2024-12-27                  1
11459  PAY0011476  O0011476 2025-12-04   2025-12-02                  2
12290  PAY0012307  O0012307 2025-12-26   2025-12-19                  7
12609  PAY0012626  O0012626 2025-04-03   2025-03-30                  4

In [290]:
# ---------------------------------------------------------
# Step 137C:
# Verify Payment Temporal Issues
# ---------------------------------------------------------

payment_temporal_issues = (
    payment_issue_log_df[
        (
            payment_issue_log_df["column"]
            .astype(str)
            .str.lower()
            == "payment_date"
        )
        &
        (
            payment_issue_log_df["issue_type"]
            .astype(str)
            .str.contains(
                "temporal",
                case=False,
                na=False
            )
        )
    ]
    .copy()
)

detected = len(payments_before_order)
expected = len(payment_temporal_issues)

print(
    "Detected payments before order:",
    detected
)

print(
    "Ground-truth temporal issues:",
    expected
)

print(
    "\nPASS" if detected == expected else "\nREVIEW",
    f"- Expected {expected}, detected {detected}"
)

Detected payments before order: 100
Ground-truth temporal issues: 100

PASS - Expected 100, detected 100

In [291]:
# ---------------------------------------------------------
# Step 138A:
# Prepare Return vs Order Temporal Check
# ---------------------------------------------------------

returns_temporal = audit_returns.copy()
orders_return_temporal = audit_orders.copy()

returns_temporal["return_date"] = pd.to_datetime(
    returns_temporal["return_date"],
    errors="coerce"
)

orders_return_temporal["order_date"] = pd.to_datetime(
    orders_return_temporal["order_date"],
    errors="coerce"
)

# One order per order_id
order_date_lookup_returns = (
    orders_return_temporal[
        ["order_id", "order_date"]
    ]
    .dropna(subset=["order_id"])
    .drop_duplicates(
        subset=["order_id"],
        keep="first"
    )
)

returns_date_check = (
    returns_temporal.merge(
        order_date_lookup_returns,
        on="order_id",
        how="inner"
    )
)

print(
    "Returns available for temporal check:",
    len(returns_date_check)
)

Returns available for temporal check: 6560

In [292]:
# ---------------------------------------------------------
# Step 138B:
# Calculate Return Window
# ---------------------------------------------------------

returns_date_check[
    "days_after_order"
] = (
    returns_date_check["return_date"]
    -
    returns_date_check["order_date"]
).dt.days

invalid_return_windows = (
    returns_date_check[
        (returns_date_check["days_after_order"] < 1)
        |
        (returns_date_check["days_after_order"] > 30)
    ]
    .copy()
)

print("RETURN WINDOW VALIDITY")
print("----------------------")

print(
    "Returns outside 1-30 day window:",
    len(invalid_return_windows)
)

display(
    invalid_return_windows[
        [
            "return_id",
            "order_id",
            "order_date",
            "return_date",
            "days_after_order"
        ]
    ].head(10)
)

RETURN WINDOW VALIDITY
----------------------
Returns outside 1-30 day window: 111

    return_id  order_id order_date return_date  days_after_order
60   R0000061  O0000940 2025-04-27  2025-07-03                67
71   R0000072  O0001108 2025-10-18  2025-12-26                69
72   R0000073  O0001108 2025-10-18  2025-12-28                71
288  R0000289  O0005075 2023-11-27  2024-02-02                67
349  R0000350  O0006212 2024-06-23  2024-09-03                72
400  R0000401  O0007068 2023-12-28  2024-03-05                68
448  R0000449  O0007987 2025-08-17  2025-10-12                56
562  R0000563  O0010279 2025-08-05  2025-09-16                42
618  R0000619  O0011636 2025-09-13  2025-10-16                33
647  R0000648  O0012439 2025-01-19  2025-04-01                72

In [293]:
# ---------------------------------------------------------
# Step 138C:
# Verify Return Temporal Issues
# ---------------------------------------------------------

return_temporal_issues = (
    return_issue_log_df[
        (
            return_issue_log_df["column"]
            .astype(str)
            .str.lower()
            == "return_date"
        )
        &
        (
            return_issue_log_df["issue_type"]
            .astype(str)
            .str.contains(
                "temporal",
                case=False,
                na=False
            )
        )
    ]
    .copy()
)

detected = len(invalid_return_windows)
expected = len(return_temporal_issues)

print(
    "Detected invalid return windows:",
    detected
)

print(
    "Ground-truth temporal issues:",
    expected
)

print(
    "\nPASS" if detected == expected else "\nREVIEW",
    f"- Expected {expected}, detected {detected}"
)

Detected invalid return windows: 111
Ground-truth temporal issues: 100

REVIEW - Expected 100, detected 111

In [294]:
# ---------------------------------------------------------
# Step 139A:
# Build Expected Refund Reference
# ---------------------------------------------------------

refund_reference = (
    order_items_ground_truth_df[
        [
            "order_item_id",
            "unit_price",
            "discount_pct"
        ]
    ]
    .drop_duplicates(
        subset=["order_item_id"]
    )
)

returns_refund_check = (
    audit_returns.merge(
        refund_reference,
        on="order_item_id",
        how="inner"
    )
    .copy()
)

print(
    "Returns available for refund reconciliation:",
    len(returns_refund_check)
)

Returns available for refund reconciliation: 6485

In [295]:
# ---------------------------------------------------------
# Step 139B:
# Calculate Expected Refund Amount
# ---------------------------------------------------------

returns_refund_check[
    "expected_refund_amount"
] = (
    returns_refund_check["return_quantity"]
    *
    returns_refund_check["unit_price"]
    *
    (
        1 -
        returns_refund_check["discount_pct"]
    )
).round(2)

returns_refund_check[
    "refund_difference"
] = (
    returns_refund_check["refund_amount"]
    -
    returns_refund_check["expected_refund_amount"]
).round(2)

display(
    returns_refund_check[
        [
            "return_id",
            "order_item_id",
            "return_quantity",
            "refund_amount",
            "expected_refund_amount",
            "refund_difference"
        ]
    ].head(10)
)

,return_id,order_item_id,return_quantity,refund_amount,expected_refund_amount,refund_difference
0,R0000001,OI00000008,2,70.16,70.16,0.00
1,R0000002,OI00000007,1,1094.89,1094.89,0.00
2,R0000003,OI00000006,1,816.11,816.11,0.00
3,R0000004,OI00000112,2,93.80,93.80,0.00
4,R0000005,OI00000113,1,282.36,282.36,0.00
5,R0000006,OI00000242,1,136.82,136.82,0.00
6,R0000007,OI00000243,1,145.60,145.60,0.00
7,R0000008,OI00000264,1,452.77,452.77,0.00
8,R0000010,OI00000462,2,638.91,638.91,0.00
9,R0000011,OI00000463,1,393.07,393.08,-0.01

In [296]:
# ---------------------------------------------------------
# Step 139C:
# Isolate Refund-Amount Reconciliation
# ---------------------------------------------------------

# Remove duplicate return IDs
duplicate_return_ids_139 = set(
    audit_returns.loc[
        audit_returns["return_id"].duplicated(
            keep=False
        ),
        "return_id"
    ]
)

valid_refund_checks = (
    returns_refund_check[
        ~returns_refund_check["return_id"].isin(
            duplicate_return_ids_139
        )
        &
        (
            returns_refund_check["return_quantity"] > 0
        )
    ]
    .copy()
)

# Ensure returned quantity does not exceed purchased quantity
quantity_reference_139 = (
    order_items_ground_truth_df[
        ["order_item_id", "quantity"]
    ]
    .rename(
        columns={
            "quantity": "purchased_quantity"
        }
    )
)

valid_refund_checks = (
    valid_refund_checks.merge(
        quantity_reference_139,
        on="order_item_id",
        how="left"
    )
)

valid_refund_checks = (
    valid_refund_checks[
        valid_refund_checks["return_quantity"]
        <=
        valid_refund_checks["purchased_quantity"]
    ]
    .copy()
)

refund_amount_mismatches = (
    valid_refund_checks[
        valid_refund_checks[
            "refund_difference"
        ].abs() > 0.01
    ]
    .copy()
)

print(
    "Refund amount mismatches:",
    len(refund_amount_mismatches)
)

display(
    refund_amount_mismatches[
        [
            "return_id",
            "order_item_id",
            "return_quantity",
            "refund_amount",
            "expected_refund_amount",
            "refund_difference"
        ]
    ].head(10)
)

Refund amount mismatches: 100

,return_id,order_item_id,return_quantity,refund_amount,expected_refund_amount,refund_difference
50,R0000053,OI00002250,1,153.80,307.60,-153.80
87,R0000090,OI00003723,1,1184.70,789.80,394.90
96,R0000099,OI00003931,1,356.46,274.20,82.26
112,R0000115,OI00004881,1,1260.56,840.37,420.19
260,R0000268,OI00012307,1,207.77,415.54,-207.77
348,R0000359,OI00016348,1,876.80,730.67,146.13
377,R0000388,OI00017354,2,385.98,257.32,128.66
448,R0000460,OI00021177,1,45.96,38.30,7.66
463,R0000475,OI00021695,1,159.22,199.02,-39.80
481,R0000495,OI00023169,1,94.37,188.74,-94.37

In [297]:
# ---------------------------------------------------------
# Step 139D:
# Verify Refund Reconciliation Against Ground Truth
# ---------------------------------------------------------

refund_ground_truth = (
    return_issue_log_df[
        (
            return_issue_log_df["column"]
            .astype(str)
            .str.lower()
            == "refund_amount"
        )
    ]
    .copy()
)

detected = len(
    refund_amount_mismatches
)

expected = len(
    refund_ground_truth
)

print(
    "Detected refund mismatches:",
    detected
)

print(
    "Ground-truth refund issues:",
    expected
)

print(
    "\nPASS" if detected == expected else "\nREVIEW",
    f"- Expected {expected}, detected {detected}"
)

Detected refund mismatches: 100
Ground-truth refund issues: 100

PASS - Expected 100, detected 100

In [298]:
# ---------------------------------------------------------
# Step 140A:
# Build Master Data-Quality Audit Summary
# ---------------------------------------------------------

quality_audit_summary = [
    # -------------------------
    # COMPLETENESS
    # -------------------------
    {
        "dataset": "customers",
        "quality_dimension": "Completeness",
        "rule": "Required customer fields must not be null",
        "violations": int(
            customer_completeness_df["missing_count"].sum()
        )
    },

    {
        "dataset": "products",
        "quality_dimension": "Completeness",
        "rule": "Required product fields must not be null",
        "violations": int(
            product_completeness_df["missing_count"].sum()
        )
    },

    {
        "dataset": "orders",
        "quality_dimension": "Completeness",
        "rule": "Required order fields must not be null",
        "violations": int(
            order_completeness_df["missing_count"].sum()
        )
    },

    {
        "dataset": "order_items",
        "quality_dimension": "Completeness",
        "rule": "Required order-item fields must not be null",
        "violations": int(
            order_item_completeness_df["missing_count"].sum()
        )
    },

    {
        "dataset": "payments",
        "quality_dimension": "Completeness",
        "rule": "Required payment fields must not be null",
        "violations": int(
            payment_completeness_df["missing_count"].sum()
        )
    },

    {
        "dataset": "returns",
        "quality_dimension": "Completeness",
        "rule": "Required return fields must not be null",
        "violations": int(
            return_completeness_df["missing_count"].sum()
        )
    },

    # -------------------------
    # UNIQUENESS
    # -------------------------
    {
        "dataset": "customers",
        "quality_dimension": "Uniqueness",
        "rule": "customer_id must be unique",
        "violations": int(
            audit_customers["customer_id"]
            .duplicated()
            .sum()
        )
    },

    {
        "dataset": "products",
        "quality_dimension": "Uniqueness",
        "rule": "product_id must be unique",
        "violations": int(
            audit_products["product_id"]
            .duplicated()
            .sum()
        )
    },

    {
        "dataset": "orders",
        "quality_dimension": "Uniqueness",
        "rule": "order_id must be unique",
        "violations": int(
            audit_orders["order_id"]
            .duplicated()
            .sum()
        )
    },

    {
        "dataset": "order_items",
        "quality_dimension": "Uniqueness",
        "rule": "order_item_id must be unique",
        "violations": int(
            audit_order_items["order_item_id"]
            .duplicated()
            .sum()
        )
    },

    {
        "dataset": "payments",
        "quality_dimension": "Uniqueness",
        "rule": "payment_id must be unique",
        "violations": int(
            audit_payments["payment_id"]
            .duplicated()
            .sum()
        )
    },

    {
        "dataset": "returns",
        "quality_dimension": "Uniqueness",
        "rule": "return_id must be unique",
        "violations": int(
            audit_returns["return_id"]
            .duplicated()
            .sum()
        )
    },

    # -------------------------
    # VALIDITY
    # -------------------------
    {
        "dataset": "customers",
        "quality_dimension": "Validity",
        "rule": "Email must follow valid format",
        "violations": len(
            invalid_customer_emails
        )
    },

    {
        "dataset": "products",
        "quality_dimension": "Validity",
        "rule": "Unit cost must not be negative",
        "violations": len(
            negative_cost_products
        )
    },

    {
        "dataset": "order_items",
        "quality_dimension": "Validity",
        "rule": "Quantity must be greater than zero",
        "violations": len(
            invalid_order_item_quantities
        )
    },

    {
        "dataset": "order_items",
        "quality_dimension": "Validity",
        "rule": "Discount must be between 0 and 30%",
        "violations": len(
            invalid_order_item_discounts
        )
    },

    {
        "dataset": "orders",
        "quality_dimension": "Validity",
        "rule": "Sales channel must belong to approved domain",
        "violations": len(
            invalid_sales_channels
        )
    },

    # -------------------------
    # CONSISTENCY
    # -------------------------
    {
        "dataset": "customers",
        "quality_dimension": "Consistency",
        "rule": "State must map to correct region",
        "violations": len(
            customer_region_mismatches
        )
    },

    {
        "dataset": "products",
        "quality_dimension": "Consistency",
        "rule": "Category must match subcategory",
        "violations": len(
            category_subcategory_mismatches
        )
    },

    {
        "dataset": "orders",
        "quality_dimension": "Consistency",
        "rule": "Shipping state must match shipping region",
        "violations": len(
            shipping_region_mismatches
        )
    },

    {
        "dataset": "payments",
        "quality_dimension": "Consistency",
        "rule": "Payment status must agree with order status",
        "violations": len(
            payment_status_mismatches
        )
    },

    # -------------------------
    # TEMPORAL CONSISTENCY
    # -------------------------
    {
        "dataset": "orders",
        "quality_dimension": "Consistency",
        "rule": "Order date cannot precede customer signup",
        "violations": len(
            orders_before_signup
        )
    },

    {
        "dataset": "payments",
        "quality_dimension": "Consistency",
        "rule": "Payment date cannot precede order date",
        "violations": len(
            payments_before_order
        )
    },

    {
        "dataset": "returns",
        "quality_dimension": "Consistency",
        "rule": "Return must occur within 1-30 days",
        "violations": len(
            invalid_return_windows
        )
    },

    # -------------------------
    # RECONCILIATION
    # -------------------------
    {
        "dataset": "payments",
        "quality_dimension": "Reconciliation",
        "rule": "Payment amount must match calculated order amount",
        "violations": len(
            payment_amount_mismatches
        )
    },

    {
        "dataset": "returns",
        "quality_dimension": "Reconciliation",
        "rule": "Refund must match calculated refund amount",
        "violations": len(
            refund_amount_mismatches
        )
    }
]

quality_audit_summary_df = pd.DataFrame(
    quality_audit_summary
)

print("MASTER DATA-QUALITY AUDIT")
print("-------------------------")

display(
    quality_audit_summary_df
)

MASTER DATA-QUALITY AUDIT
-------------------------

,dataset,quality_dimension,rule,violations
0,customers,Completeness,Required customer fields must not be null,500
1,products,Completeness,Required product fields must not be null,20
2,orders,Completeness,Required order fields must not be null,300
3,order_items,Completeness,Required order-item fields must not be null,0
4,payments,Completeness,Required payment fields must not be null,0
5,returns,Completeness,Required return fields must not be null,17
6,customers,Uniqueness,customer_id must be unique,200
7,products,Uniqueness,product_id must be unique,10
8,orders,Uniqueness,order_id must be unique,100
9,order_items,Uniqueness,order_item_id must be unique,150
10,payments,Uniqueness,payment_id must be unique,100
11,returns,Uniqueness,return_id must be unique,50
12,customers,Validity,Email must follow valid format,400
13,products,Validity,Unit cost must not be negative,10
14,order_items,Validity,Quantity must be greater than zero,300
15,order_items,Validity,Discount must be between 0 and 30%,150
16,orders,Validity,Sales channel must belong to approved domain,100
17,customers,Consistency,State must map to correct region,300
18,products,Consistency,Category must match subcategory,15
19,orders,Consistency,Shipping state must match shipping region,150
20,payments,Consistency,Payment status must agree with order status,100
21,orders,Consistency,Order date cannot precede customer signup,150
22,payments,Consistency,Payment date cannot precede order date,100
23,returns,Consistency,Return must occur within 1-30 days,111
24,payments,Reconciliation,Payment amount must match calculated order amount,260
25,returns,Reconciliation,Refund must match calculated refund amount,100

In [299]:
# ---------------------------------------------------------
# Step 141A:
# Add Dataset Row Counts and Violation Rates
# ---------------------------------------------------------

dataset_row_counts = {
    "customers": len(audit_customers),
    "products": len(audit_products),
    "orders": len(audit_orders),
    "order_items": len(audit_order_items),
    "payments": len(audit_payments),
    "returns": len(audit_returns)
}

quality_audit_summary_df["total_records"] = (
    quality_audit_summary_df["dataset"]
    .map(dataset_row_counts)
)

quality_audit_summary_df["violation_rate_pct"] = (
    quality_audit_summary_df["violations"]
    /
    quality_audit_summary_df["total_records"]
    * 100
).round(4)

display(
    quality_audit_summary_df[
        [
            "dataset",
            "quality_dimension",
            "rule",
            "violations",
            "total_records",
            "violation_rate_pct"
        ]
    ]
)

,dataset,quality_dimension,rule,violations,total_records,violation_rate_pct
0,customers,Completeness,Required customer fields must not be null,500,50200,0.9960
1,products,Completeness,Required product fields must not be null,20,2010,0.9950
2,orders,Completeness,Required order fields must not be null,300,120100,0.2498
3,order_items,Completeness,Required order-item fields must not be null,0,307309,0.0000
4,payments,Completeness,Required payment fields must not be null,0,120100,0.0000
5,returns,Completeness,Required return fields must not be null,17,6560,0.2591
6,customers,Uniqueness,customer_id must be unique,200,50200,0.3984
7,products,Uniqueness,product_id must be unique,10,2010,0.4975
8,orders,Uniqueness,order_id must be unique,100,120100,0.0833
9,order_items,Uniqueness,order_item_id must be unique,150,307309,0.0488
10,payments,Uniqueness,payment_id must be unique,100,120100,0.0833
11,returns,Uniqueness,return_id must be unique,50,6560,0.7622
12,customers,Validity,Email must follow valid format,400,50200,0.7968
13,products,Validity,Unit cost must not be negative,10,2010,0.4975
14,order_items,Validity,Quantity must be greater than zero,300,307309,0.0976
15,order_items,Validity,Discount must be between 0 and 30%,150,307309,0.0488
16,orders,Validity,Sales channel must belong to approved domain,100,120100,0.0833
17,customers,Consistency,State must map to correct region,300,50200,0.5976
18,products,Consistency,Category must match subcategory,15,2010,0.7463
19,orders,Consistency,Shipping state must match shipping region,150,120100,0.1249
20,payments,Consistency,Payment status must agree with order status,100,120100,0.0833
21,orders,Consistency,Order date cannot precede customer signup,150,120100,0.1249
22,payments,Consistency,Payment date cannot precede order date,100,120100,0.0833
23,returns,Consistency,Return must occur within 1-30 days,111,6560,1.6921
24,payments,Reconciliation,Payment amount must match calculated order amount,260,120100,0.2165
25,returns,Reconciliation,Refund must match calculated refund amount,100,6560,1.5244

In [300]:
# ---------------------------------------------------------
# Step 141B:
# Rank Rules by Violation Rate
# ---------------------------------------------------------

quality_audit_ranked_df = (
    quality_audit_summary_df
    .sort_values(
        by="violation_rate_pct",
        ascending=False
    )
    .reset_index(drop=True)
)

display(
    quality_audit_ranked_df[
        [
            "dataset",
            "quality_dimension",
            "rule",
            "violations",
            "total_records",
            "violation_rate_pct"
        ]
    ].head(15)
)

,dataset,quality_dimension,rule,violations,total_records,violation_rate_pct
0,returns,Consistency,Return must occur within 1-30 days,111,6560,1.6921
1,returns,Reconciliation,Refund must match calculated refund amount,100,6560,1.5244
2,customers,Completeness,Required customer fields must not be null,500,50200,0.9960
3,products,Completeness,Required product fields must not be null,20,2010,0.9950
4,customers,Validity,Email must follow valid format,400,50200,0.7968
5,returns,Uniqueness,return_id must be unique,50,6560,0.7622
6,products,Consistency,Category must match subcategory,15,2010,0.7463
7,customers,Consistency,State must map to correct region,300,50200,0.5976
8,products,Validity,Unit cost must not be negative,10,2010,0.4975
9,products,Uniqueness,product_id must be unique,10,2010,0.4975
10,customers,Uniqueness,customer_id must be unique,200,50200,0.3984
11,returns,Completeness,Required return fields must not be null,17,6560,0.2591
12,orders,Completeness,Required order fields must not be null,300,120100,0.2498
13,payments,Reconciliation,Payment amount must match calculated order amount,260,120100,0.2165
14,orders,Consistency,Order date cannot precede customer signup,150,120100,0.1249

In [301]:
# ---------------------------------------------------------
# Step 142A:
# Summarize Violations by Quality Dimension
# ---------------------------------------------------------

quality_dimension_summary_df = (
    quality_audit_summary_df
    .groupby(
        "quality_dimension",
        as_index=False
    )
    .agg(
        rules_checked=("rule", "count"),
        total_violations=("violations", "sum")
    )
    .sort_values(
        "total_violations",
        ascending=False
    )
    .reset_index(drop=True)
)

display(quality_dimension_summary_df)

  quality_dimension  rules_checked  total_violations
0          Validity              5               960
1       Consistency              7               926
2      Completeness              6               837
3        Uniqueness              6               610
4    Reconciliation              2               360

In [302]:
# ---------------------------------------------------------
# Step 142B:
# Calculate Violation Distribution
# ---------------------------------------------------------

total_detected_violations = (
    quality_dimension_summary_df[
        "total_violations"
    ].sum()
)

quality_dimension_summary_df[
    "violation_share_pct"
] = (
    quality_dimension_summary_df[
        "total_violations"
    ]
    /
    total_detected_violations
    * 100
).round(2)

print(
    "Total violations captured by current audit rules:",
    total_detected_violations
)

display(quality_dimension_summary_df)

Total violations captured by current audit rules: 3693

  quality_dimension  rules_checked  total_violations  violation_share_pct
0          Validity              5               960                26.00
1       Consistency              7               926                25.07
2      Completeness              6               837                22.66
3        Uniqueness              6               610                16.52
4    Reconciliation              2               360                 9.75

In [303]:
# ---------------------------------------------------------
# Step 143:
# Add Referential Integrity Rules to Master Audit
# ---------------------------------------------------------

# Valid primary-key sets
valid_customer_ids = set(
    audit_customers["customer_id"].dropna()
)

valid_order_ids = set(
    audit_orders["order_id"].dropna()
)

valid_product_ids = set(
    audit_products["product_id"].dropna()
)

valid_order_item_ids = set(
    audit_order_items["order_item_id"].dropna()
)


# 1. Orders -> Customers
# Missing customer_id is handled by Completeness,
# so only count NON-NULL nonexistent IDs here.
orders_invalid_customer_ref = (
    audit_orders["customer_id"].notna()
    &
    ~audit_orders["customer_id"].isin(valid_customer_ids)
).sum()


# 2. Order Items -> Orders
order_items_invalid_order_ref = (
    audit_order_items["order_id"].notna()
    &
    ~audit_order_items["order_id"].isin(valid_order_ids)
).sum()


# 3. Order Items -> Products
order_items_invalid_product_ref = (
    audit_order_items["product_id"].notna()
    &
    ~audit_order_items["product_id"].isin(valid_product_ids)
).sum()


# 4. Payments -> Orders
payments_invalid_order_ref = (
    audit_payments["order_id"].notna()
    &
    ~audit_payments["order_id"].isin(valid_order_ids)
).sum()


# 5. Returns -> Order Items
returns_invalid_item_ref = (
    audit_returns["order_item_id"].notna()
    &
    ~audit_returns["order_item_id"].isin(valid_order_item_ids)
).sum()


# 6. Returns -> Orders
returns_invalid_order_ref = (
    audit_returns["order_id"].notna()
    &
    ~audit_returns["order_id"].isin(valid_order_ids)
).sum()


referential_summary_df = pd.DataFrame([
    {
        "dataset": "orders",
        "quality_dimension": "Referential Integrity",
        "rule": "customer_id must reference an existing customer",
        "violations": int(orders_invalid_customer_ref)
    },
    {
        "dataset": "order_items",
        "quality_dimension": "Referential Integrity",
        "rule": "order_id must reference an existing order",
        "violations": int(order_items_invalid_order_ref)
    },
    {
        "dataset": "order_items",
        "quality_dimension": "Referential Integrity",
        "rule": "product_id must reference an existing product",
        "violations": int(order_items_invalid_product_ref)
    },
    {
        "dataset": "payments",
        "quality_dimension": "Referential Integrity",
        "rule": "order_id must reference an existing order",
        "violations": int(payments_invalid_order_ref)
    },
    {
        "dataset": "returns",
        "quality_dimension": "Referential Integrity",
        "rule": "order_item_id must reference an existing order item",
        "violations": int(returns_invalid_item_ref)
    },
    {
        "dataset": "returns",
        "quality_dimension": "Referential Integrity",
        "rule": "order_id must reference an existing order",
        "violations": int(returns_invalid_order_ref)
    }
])

display(referential_summary_df)

,dataset,quality_dimension,rule,violations
0,orders,Referential Integrity,customer_id must reference an existing customer,200
1,order_items,Referential Integrity,order_id must reference an existing order,0
2,order_items,Referential Integrity,product_id must reference an existing product,200
3,payments,Referential Integrity,order_id must reference an existing order,150
4,returns,Referential Integrity,order_item_id must reference an existing order...,75
5,returns,Referential Integrity,order_id must reference an existing order,0

In [304]:
# ---------------------------------------------------------
# Step 144:
# Add Referential Integrity Results to Master Audit
# ---------------------------------------------------------

# Add total record counts
referential_summary_df["total_records"] = (
    referential_summary_df["dataset"]
    .map(dataset_row_counts)
)

# Calculate violation rate
referential_summary_df["violation_rate_pct"] = (
    referential_summary_df["violations"]
    /
    referential_summary_df["total_records"]
    * 100
).round(4)


# Prevent accidental duplication if this cell is rerun
quality_audit_summary_df = (
    quality_audit_summary_df[
        quality_audit_summary_df["quality_dimension"]
        != "Referential Integrity"
    ]
    .copy()
)


# Append referential-integrity rules
quality_audit_summary_df = pd.concat(
    [
        quality_audit_summary_df,
        referential_summary_df
    ],
    ignore_index=True
)


print("Updated Master Data-Quality Audit")
print("---------------------------------")
print(
    "Total rules:",
    len(quality_audit_summary_df)
)

display(
    quality_audit_summary_df[
        [
            "dataset",
            "quality_dimension",
            "rule",
            "violations",
            "total_records",
            "violation_rate_pct"
        ]
    ]
)

Updated Master Data-Quality Audit
---------------------------------
Total rules: 32

,dataset,quality_dimension,rule,violations,total_records,violation_rate_pct
0,customers,Completeness,Required customer fields must not be null,500,50200,0.9960
1,products,Completeness,Required product fields must not be null,20,2010,0.9950
2,orders,Completeness,Required order fields must not be null,300,120100,0.2498
3,order_items,Completeness,Required order-item fields must not be null,0,307309,0.0000
4,payments,Completeness,Required payment fields must not be null,0,120100,0.0000
5,returns,Completeness,Required return fields must not be null,17,6560,0.2591
6,customers,Uniqueness,customer_id must be unique,200,50200,0.3984
7,products,Uniqueness,product_id must be unique,10,2010,0.4975
8,orders,Uniqueness,order_id must be unique,100,120100,0.0833
9,order_items,Uniqueness,order_item_id must be unique,150,307309,0.0488
10,payments,Uniqueness,payment_id must be unique,100,120100,0.0833
11,returns,Uniqueness,return_id must be unique,50,6560,0.7622
12,customers,Validity,Email must follow valid format,400,50200,0.7968
13,products,Validity,Unit cost must not be negative,10,2010,0.4975
14,order_items,Validity,Quantity must be greater than zero,300,307309,0.0976
15,order_items,Validity,Discount must be between 0 and 30%,150,307309,0.0488
16,orders,Validity,Sales channel must belong to approved domain,100,120100,0.0833
17,customers,Consistency,State must map to correct region,300,50200,0.5976
18,products,Consistency,Category must match subcategory,15,2010,0.7463
19,orders,Consistency,Shipping state must match shipping region,150,120100,0.1249
20,payments,Consistency,Payment status must agree with order status,100,120100,0.0833
21,orders,Consistency,Order date cannot precede customer signup,150,120100,0.1249
22,payments,Consistency,Payment date cannot precede order date,100,120100,0.0833
23,returns,Consistency,Return must occur within 1-30 days,111,6560,1.6921
24,payments,Reconciliation,Payment amount must match calculated order amount,260,120100,0.2165
25,returns,Reconciliation,Refund must match calculated refund amount,100,6560,1.5244
26,orders,Referential Integrity,customer_id must reference an existing customer,200,120100,0.1665
27,order_items,Referential Integrity,order_id must reference an existing order,0,307309,0.0000
28,order_items,Referential Integrity,product_id must reference an existing product,200,307309,0.0651
29,payments,Referential Integrity,order_id must reference an existing order,150,120100,0.1249
30,returns,Referential Integrity,order_item_id must reference an existing order...,75,6560,1.1433
31,returns,Referential Integrity,order_id must reference an existing order,0,6560,0.0000

In [305]:
# ---------------------------------------------------------
# Step 145:
# Diagnose Return-Reason Detection Discrepancy
# ---------------------------------------------------------

# Derive the valid return reasons directly from clean data
valid_return_reasons = set(
    returns_ground_truth_df[
        "return_reason"
    ].dropna().unique()
)

# Get all return_reason issues recorded in the issue log
return_reason_ground_truth = (
    return_issue_log_df[
        return_issue_log_df["column"]
        .astype(str)
        .str.lower()
        .eq("return_reason")
    ]
    .copy()
)

# Compare those exact return IDs with the current dirty dataset
return_reason_diagnostic = (
    return_reason_ground_truth.merge(
        audit_returns[
            ["return_id", "return_reason"]
        ],
        on="return_id",
        how="left"
    )
)

# Determine whether each injected issue is currently detectable
return_reason_diagnostic["currently_invalid"] = (
    return_reason_diagnostic["return_reason"].notna()
    &
    ~return_reason_diagnostic[
        "return_reason"
    ].isin(valid_return_reasons)
)

print("RETURN REASON DIAGNOSTIC")
print("------------------------")

print(
    "Ground-truth injected issues:",
    len(return_reason_ground_truth)
)

print(
    "Currently detected as invalid:",
    int(
        return_reason_diagnostic[
            "currently_invalid"
        ].sum()
    )
)

print(
    "Injected issues NOT currently detected:",
    int(
        (~return_reason_diagnostic[
            "currently_invalid"
        ]).sum()
    )
)

print("\nValid return reasons:")
print(sorted(valid_return_reasons))

print(
    "\nRows recorded as corrupted but currently appearing valid:"
)

display(
    return_reason_diagnostic.loc[
        ~return_reason_diagnostic[
            "currently_invalid"
        ]
    ].head(25)
)

RETURN REASON DIAGNOSTIC
------------------------
Ground-truth injected issues: 75
Currently detected as invalid: 58
Injected issues NOT currently detected: 17

Valid return reasons:
[np.str_('Arrived Late'), np.str_('Changed Mind'), np.str_('Damaged'), np.str_('Defective'), np.str_('Not as Described'), np.str_('Size/Fit Issue'), np.str_('Wrong Item')]

Rows recorded as corrupted but currently appearing valid:

,return_id,issue_type,column,original_value,injected_value,return_reason,currently_invalid
1,R0002106,invalid_category,return_reason,Arrived Late,N/A,NaN,False
6,R0005789,invalid_category,return_reason,Changed Mind,N/A,NaN,False
9,R0000471,invalid_category,return_reason,Damaged,N/A,NaN,False
11,R0006476,invalid_category,return_reason,Changed Mind,N/A,NaN,False
12,R0000494,invalid_category,return_reason,Defective,N/A,NaN,False
14,R0004480,invalid_category,return_reason,Damaged,N/A,NaN,False
18,R0006012,invalid_category,return_reason,Defective,N/A,NaN,False
19,R0002429,invalid_category,return_reason,Size/Fit Issue,N/A,NaN,False
21,R0001822,invalid_category,return_reason,Wrong Item,N/A,NaN,False
24,R0000727,invalid_category,return_reason,Not as Described,N/A,NaN,False
26,R0000560,invalid_category,return_reason,Not as Described,N/A,NaN,False
30,R0005923,invalid_category,return_reason,Size/Fit Issue,N/A,NaN,False
32,R0004328,invalid_category,return_reason,Wrong Item,N/A,NaN,False
35,R0006340,invalid_category,return_reason,Not as Described,N/A,NaN,False
63,R0001866,invalid_category,return_reason,Changed Mind,N/A,NaN,False
68,R0000877,invalid_category,return_reason,Arrived Late,N/A,NaN,False
71,R0003700,invalid_category,return_reason,Not as Described,N/A,NaN,False

In [306]:
# ---------------------------------------------------------
# Step 146:
# Inspect Return-Reason Values for Undetected Issues
# ---------------------------------------------------------

undetected_return_reason_issues = (
    return_reason_diagnostic[
        ~return_reason_diagnostic["currently_invalid"]
    ]
    .copy()
)

print("Undetected injected return-reason issues:")
print(len(undetected_return_reason_issues))

print("\nColumns available in diagnostic table:")
print(undetected_return_reason_issues.columns.tolist())

display(
    undetected_return_reason_issues
)

Undetected injected return-reason issues:
17

Columns available in diagnostic table:
['return_id', 'issue_type', 'column', 'original_value', 'injected_value', 'return_reason', 'currently_invalid']

,return_id,issue_type,column,original_value,injected_value,return_reason,currently_invalid
1,R0002106,invalid_category,return_reason,Arrived Late,N/A,NaN,False
6,R0005789,invalid_category,return_reason,Changed Mind,N/A,NaN,False
9,R0000471,invalid_category,return_reason,Damaged,N/A,NaN,False
11,R0006476,invalid_category,return_reason,Changed Mind,N/A,NaN,False
12,R0000494,invalid_category,return_reason,Defective,N/A,NaN,False
14,R0004480,invalid_category,return_reason,Damaged,N/A,NaN,False
18,R0006012,invalid_category,return_reason,Defective,N/A,NaN,False
19,R0002429,invalid_category,return_reason,Size/Fit Issue,N/A,NaN,False
21,R0001822,invalid_category,return_reason,Wrong Item,N/A,NaN,False
24,R0000727,invalid_category,return_reason,Not as Described,N/A,NaN,False
26,R0000560,invalid_category,return_reason,Not as Described,N/A,NaN,False
30,R0005923,invalid_category,return_reason,Size/Fit Issue,N/A,NaN,False
32,R0004328,invalid_category,return_reason,Wrong Item,N/A,NaN,False
35,R0006340,invalid_category,return_reason,Not as Described,N/A,NaN,False
63,R0001866,invalid_category,return_reason,Changed Mind,N/A,NaN,False
68,R0000877,invalid_category,return_reason,Arrived Late,N/A,NaN,False
71,R0003700,invalid_category,return_reason,Not as Described,N/A,NaN,False

In [307]:
# ---------------------------------------------------------
# Step 147:
# Check Duplicate Return IDs in Undetected Reason Issues
# ---------------------------------------------------------

duplicate_return_ids = set(
    audit_returns.loc[
        audit_returns["return_id"].duplicated(keep=False),
        "return_id"
    ]
)

undetected_return_reason_issues[
    "is_duplicate_return_id"
] = (
    undetected_return_reason_issues[
        "return_id"
    ].isin(duplicate_return_ids)
)

print("RETURN-REASON DUPLICATE DIAGNOSTIC")
print("----------------------------------")

print(
    "Undetected return-reason issues:",
    len(undetected_return_reason_issues)
)

print(
    "Associated with duplicate return IDs:",
    int(
        undetected_return_reason_issues[
            "is_duplicate_return_id"
        ].sum()
    )
)

print(
    "Not associated with duplicate return IDs:",
    int(
        (~undetected_return_reason_issues[
            "is_duplicate_return_id"
        ]).sum()
    )
)

display(
    undetected_return_reason_issues[
        [
            "return_id",
            "return_reason",
            "is_duplicate_return_id"
        ]
    ].head(25)
)

RETURN-REASON DUPLICATE DIAGNOSTIC
----------------------------------
Undetected return-reason issues: 17
Associated with duplicate return IDs: 0
Not associated with duplicate return IDs: 17

   return_id return_reason  is_duplicate_return_id
1   R0002106           NaN                   False
6   R0005789           NaN                   False
9   R0000471           NaN                   False
11  R0006476           NaN                   False
12  R0000494           NaN                   False
14  R0004480           NaN                   False
18  R0006012           NaN                   False
19  R0002429           NaN                   False
21  R0001822           NaN                   False
24  R0000727           NaN                   False
26  R0000560           NaN                   False
30  R0005923           NaN                   False
32  R0004328           NaN                   False
35  R0006340           NaN                   False
63  R0001866           NaN                   False
68  R0000877           NaN                   False
71  R0003700           NaN                   False

In [308]:
# ---------------------------------------------------------
# Step 148:
# Inspect Actual Return-Reason Injection Records
# ---------------------------------------------------------

print("Columns in return issue log:")
print(return_issue_log_df.columns.tolist())

print("\nReturn-reason issue records:")
display(
    return_reason_ground_truth.head(20)
)

print("\nUnique values in each useful issue-log column:")

for col in return_reason_ground_truth.columns:
    if col not in ["return_id"]:
        print(f"\n--- {col} ---")
        print(
            return_reason_ground_truth[col]
            .value_counts(dropna=False)
            .head(20)
        )

Columns in return issue log:
['return_id', 'issue_type', 'column', 'original_value', 'injected_value']

Return-reason issue records:

,return_id,issue_type,column,original_value,injected_value
300,R0003559,invalid_category,return_reason,Not as Described,Unknown
301,R0002106,invalid_category,return_reason,Arrived Late,N/A
302,R0000598,invalid_category,return_reason,Size/Fit Issue,Other123
303,R0006420,invalid_category,return_reason,Arrived Late,Unknown
304,R0002968,invalid_category,return_reason,Size/Fit Issue,Other123
305,R0006169,invalid_category,return_reason,Changed Mind,Other123
306,R0005789,invalid_category,return_reason,Changed Mind,N/A
307,R0005282,invalid_category,return_reason,Defective,Unknown
308,R0001037,invalid_category,return_reason,Changed Mind,Unknown
309,R0000471,invalid_category,return_reason,Damaged,N/A
310,R0005519,invalid_category,return_reason,Damaged,Unknown
311,R0006476,invalid_category,return_reason,Changed Mind,N/A
312,R0000494,invalid_category,return_reason,Defective,N/A
313,R0005113,invalid_category,return_reason,Size/Fit Issue,No Reason
314,R0004480,invalid_category,return_reason,Damaged,N/A
315,R0003550,invalid_category,return_reason,Arrived Late,Customer Complaint
316,R0001414,invalid_category,return_reason,Size/Fit Issue,Unknown
317,R0004023,invalid_category,return_reason,Changed Mind,Unknown
318,R0006012,invalid_category,return_reason,Defective,N/A
319,R0002429,invalid_category,return_reason,Size/Fit Issue,N/A

Unique values in each useful issue-log column:

--- issue_type ---
issue_type
invalid_category    75
Name: count, dtype: int64

--- column ---
column
return_reason    75
Name: count, dtype: int64

--- original_value ---
original_value
Changed Mind        16
Size/Fit Issue      14
Not as Described    12
Arrived Late        12
Damaged              8
Wrong Item           7
Defective            6
Name: count, dtype: int64

--- injected_value ---
injected_value
Unknown               23
N/A                   17
Other123              13
Customer Complaint    13
No Reason              9
Name: count, dtype: int64

In [309]:
# ---------------------------------------------------------
# Step 149:
# Compare Logged Return-Reason Value vs Final CSV Value
# ---------------------------------------------------------

possible_value_columns = [
    "injected_value",
    "new_value",
    "corrupted_value",
    "invalid_value"
]

injected_col = next(
    (
        col for col in possible_value_columns
        if col in return_reason_ground_truth.columns
    ),
    None
)

if injected_col is None:
    print("No injected-value column found automatically.")
    print(
        "Available columns:",
        return_reason_ground_truth.columns.tolist()
    )

else:
    comparison_df = (
        return_reason_ground_truth[
            ["return_id", injected_col]
        ]
        .merge(
            audit_returns[
                ["return_id", "return_reason"]
            ],
            on="return_id",
            how="left"
        )
    )

    comparison_df["logged_matches_final"] = (
        comparison_df[injected_col].astype(str)
        ==
        comparison_df["return_reason"].astype(str)
    )

    comparison_df["final_value_is_valid"] = (
        comparison_df["return_reason"]
        .isin(valid_return_reasons)
    )

    print("RETURN REASON VALUE COMPARISON")
    print("------------------------------")

    print(
        "Ground-truth issues:",
        len(comparison_df)
    )

    print(
        "Logged value matches final CSV:",
        int(
            comparison_df[
                "logged_matches_final"
            ].sum()
        )
    )

    print(
        "Logged value DOES NOT match final CSV:",
        int(
            (~comparison_df[
                "logged_matches_final"
            ]).sum()
        )
    )

    print(
        "Final values that appear valid:",
        int(
            comparison_df[
                "final_value_is_valid"
            ].sum()
        )
    )

    display(
        comparison_df[
            ~comparison_df["logged_matches_final"]
            |
            comparison_df["final_value_is_valid"]
        ].head(30)
    )

RETURN REASON VALUE COMPARISON
------------------------------
Ground-truth issues: 75
Logged value matches final CSV: 58
Logged value DOES NOT match final CSV: 17
Final values that appear valid: 0

,return_id,injected_value,return_reason,logged_matches_final,final_value_is_valid
1,R0002106,N/A,NaN,False,False
6,R0005789,N/A,NaN,False,False
9,R0000471,N/A,NaN,False,False
11,R0006476,N/A,NaN,False,False
12,R0000494,N/A,NaN,False,False
14,R0004480,N/A,NaN,False,False
18,R0006012,N/A,NaN,False,False
19,R0002429,N/A,NaN,False,False
21,R0001822,N/A,NaN,False,False
24,R0000727,N/A,NaN,False,False
26,R0000560,N/A,NaN,False,False
30,R0005923,N/A,NaN,False,False
32,R0004328,N/A,NaN,False,False
35,R0006340,N/A,NaN,False,False
63,R0001866,N/A,NaN,False,False
68,R0000877,N/A,NaN,False,False
71,R0003700,N/A,NaN,False,False

In [310]:
# ---------------------------------------------------------
# Step 150:
# Validate Injected Return-Reason Values
# ---------------------------------------------------------

# Find the column that stores the injected/corrupted value
possible_value_columns = [
    "injected_value",
    "new_value",
    "corrupted_value",
    "invalid_value"
]

injected_col = next(
    (
        col for col in possible_value_columns
        if col in return_reason_ground_truth.columns
    ),
    None
)

if injected_col is None:

    print("Could not identify the injected-value column.")
    print("Available columns:")
    print(return_reason_ground_truth.columns.tolist())

else:

    reason_injection_check = (
        return_reason_ground_truth[
            ["return_id", injected_col]
        ]
        .copy()
    )

    reason_injection_check["injected_value_is_valid"] = (
        reason_injection_check[injected_col]
        .isin(valid_return_reasons)
    )

    print("RETURN-REASON INJECTION VALIDITY")
    print("--------------------------------")

    print(
        "Total logged return-reason issues:",
        len(reason_injection_check)
    )

    print(
        "Actually invalid injected values:",
        int(
            (~reason_injection_check[
                "injected_value_is_valid"
            ]).sum()
        )
    )

    print(
        "Injected values that are actually VALID:",
        int(
            reason_injection_check[
                "injected_value_is_valid"
            ].sum()
        )
    )

    print("\nInjected value distribution:")

    display(
        reason_injection_check[
            injected_col
        ]
        .value_counts(dropna=False)
        .rename_axis("injected_value")
        .reset_index(name="count")
    )

    print("\nLogged issues whose injected value is valid:")

    display(
        reason_injection_check[
            reason_injection_check[
                "injected_value_is_valid"
            ]
        ]
    )

RETURN-REASON INJECTION VALIDITY
--------------------------------
Total logged return-reason issues: 75
Actually invalid injected values: 75
Injected values that are actually VALID: 0

Injected value distribution:

       injected_value  count
0             Unknown     23
1                 N/A     17
2            Other123     13
3  Customer Complaint     13
4           No Reason      9

Logged issues whose injected value is valid:

Empty DataFrame
Columns: [return_id, injected_value, injected_value_is_valid]
Index: []

In [311]:
# ---------------------------------------------------------
# Step 151:
# Identify Root Cause of Return-Reason Discrepancy
# ---------------------------------------------------------

if injected_col is None:

    print("ROOT CAUSE CANNOT YET BE DETERMINED")
    print("No injected-value column was identified in the issue log.")

else:

    logged_valid_count = int(
        return_reason_ground_truth[injected_col]
        .isin(valid_return_reasons)
        .sum()
    )

    comparison = (
        return_reason_ground_truth[
            ["return_id", injected_col]
        ]
        .merge(
            audit_returns[
                ["return_id", "return_reason"]
            ],
            on="return_id",
            how="left"
        )
    )

    comparison["logged_matches_final"] = (
        comparison[injected_col].astype(str)
        ==
        comparison["return_reason"].astype(str)
    )

    changed_after_logging = int(
        (~comparison["logged_matches_final"]).sum()
    )

    detected_invalid = int(
        (~comparison["return_reason"].isin(
            valid_return_reasons
        )).sum()
    )

    print("RETURN-REASON ROOT-CAUSE SUMMARY")
    print("--------------------------------")

    print("Logged issues:", len(comparison))
    print("Detected invalid in final CSV:", detected_invalid)
    print("Logged injected values that were actually valid:", logged_valid_count)
    print("Values changed after issue logging:", changed_after_logging)

    print("\nDIAGNOSIS:")

    if logged_valid_count > 0:
        print(
            "The injection logic generated some values "
            "that belong to the valid return-reason domain."
        )

    elif changed_after_logging > 0:
        print(
            "The issue log recorded invalid values correctly, "
            "but some values changed before the final CSV was saved."
        )

    elif detected_invalid == len(comparison):
        print(
            "All logged return-reason issues are correctly "
            "present and detectable in the final dataset."
        )

    else:
        print(
            "The discrepancy requires additional investigation."
        )

RETURN-REASON ROOT-CAUSE SUMMARY
--------------------------------
Logged issues: 75
Detected invalid in final CSV: 75
Logged injected values that were actually valid: 0
Values changed after issue logging: 17

DIAGNOSIS:
The issue log recorded invalid values correctly, but some values changed before the final CSV was saved.

In [312]:
# ---------------------------------------------------------
# Step 152:
# Repair Return-Reason Corruption Injection
# ---------------------------------------------------------

# IDs that were intentionally selected for return_reason corruption
reason_issue_ids = (
    return_issue_log_df.loc[
        return_issue_log_df["column"]
        .astype(str)
        .str.lower()
        .eq("return_reason"),
        "return_id"
    ]
    .dropna()
    .unique()
)

# Values deliberately outside the valid business domain
invalid_reason_values = [
    "Unknown Reason",
    "Other Invalid",
    "System Error",
    "Invalid Code"
]

# Work from current dirty returns dataset
returns_repaired_df = audit_returns.copy()

# Do not modify duplicate copies separately
reason_mask = (
    returns_repaired_df["return_id"]
    .isin(reason_issue_ids)
)

# Deterministic replacement
rng = np.random.default_rng(RANDOM_SEED)

returns_repaired_df.loc[
    reason_mask,
    "return_reason"
] = rng.choice(
    invalid_reason_values,
    size=reason_mask.sum()
)

print("Intended return_reason issue IDs:", len(reason_issue_ids))
print("Rows updated:", int(reason_mask.sum()))

Intended return_reason issue IDs: 75
Rows updated: 75

In [313]:
# ---------------------------------------------------------
# Step 153:
# Verify Repaired Return-Reason Issues
# ---------------------------------------------------------

# Derive valid reasons from the clean ground-truth dataset
valid_return_reasons = set(
    returns_ground_truth_df[
        "return_reason"
    ].dropna().unique()
)

# Detect invalid reasons in repaired dataset
invalid_reasons_after_repair = (
    returns_repaired_df[
        returns_repaired_df["return_reason"].notna()
        &
        ~returns_repaired_df[
            "return_reason"
        ].isin(valid_return_reasons)
    ]
    .copy()
)

expected_reason_issues = len(reason_issue_ids)
detected_reason_issues = len(invalid_reasons_after_repair)

print("RETURN-REASON REPAIR VERIFICATION")
print("---------------------------------")

print(
    "Expected invalid return reasons:",
    expected_reason_issues
)

print(
    "Detected invalid return reasons:",
    detected_reason_issues
)

print(
    "\nPASS"
    if detected_reason_issues == expected_reason_issues
    else "\nREVIEW"
)

print("\nInvalid reason distribution:")

display(
    invalid_reasons_after_repair[
        "return_reason"
    ]
    .value_counts()
    .rename_axis("invalid_reason")
    .reset_index(name="count")
)

RETURN-REASON REPAIR VERIFICATION
---------------------------------
Expected invalid return reasons: 75
Detected invalid return reasons: 75

PASS

Invalid reason distribution:

   invalid_reason  count
0    Invalid Code     21
1   Other Invalid     19
2    System Error     18
3  Unknown Reason     17

In [314]:
# ---------------------------------------------------------
# Step 154:
# Save Corrected Returns Dataset
# ---------------------------------------------------------

returns_repaired_df.to_csv(
    INCOMING_DIR / "returns.csv",
    index=False
)

print("Corrected returns.csv saved successfully.")
print("Rows saved:", len(returns_repaired_df))

Corrected returns.csv saved successfully.
Rows saved: 6560

In [315]:
# Reload saved file
audit_returns = pd.read_csv(
    INCOMING_DIR / "returns.csv"
)

invalid_reasons_saved = audit_returns[
    audit_returns["return_reason"].notna()
    &
    ~audit_returns["return_reason"].isin(
        valid_return_reasons
    )
]

print("Invalid return reasons after reload:",
      len(invalid_reasons_saved))

print(
    "PASS"
    if len(invalid_reasons_saved) == 75
    else "REVIEW"
)

Invalid return reasons after reload: 75
PASS

In [316]:
# ---------------------------------------------------------
# Step 155:
# Add Return-Reason Validity Rule to Master Audit
# ---------------------------------------------------------

invalid_return_reasons = (
    audit_returns[
        audit_returns["return_reason"].notna()
        &
        ~audit_returns["return_reason"].isin(
            valid_return_reasons
        )
    ]
    .copy()
)

return_reason_rule = pd.DataFrame([
    {
        "dataset": "returns",
        "quality_dimension": "Validity",
        "rule": "Return reason must belong to approved domain",
        "violations": len(invalid_return_reasons),
        "total_records": len(audit_returns),
        "violation_rate_pct": round(
            len(invalid_return_reasons)
            / len(audit_returns)
            * 100,
            4
        )
    }
])

# Prevent duplication if this cell is rerun
quality_audit_summary_df = (
    quality_audit_summary_df[
        quality_audit_summary_df["rule"]
        != "Return reason must belong to approved domain"
    ]
    .copy()
)

quality_audit_summary_df = pd.concat(
    [
        quality_audit_summary_df,
        return_reason_rule
    ],
    ignore_index=True
)

print("RETURN REASON RULE")
print("------------------")
print(
    "Invalid return reasons detected:",
    len(invalid_return_reasons)
)

display(return_reason_rule)

RETURN REASON RULE
------------------
Invalid return reasons detected: 75

,dataset,quality_dimension,rule,violations,total_records,violation_rate_pct
0,returns,Validity,Return reason must belong to approved domain,75,6560,1.1433

In [317]:
# ---------------------------------------------------------
# Step 156:
# Verify Total Injected Issues Across All Datasets
# ---------------------------------------------------------

issue_log_summary = pd.DataFrame([
    {
        "dataset": "customers",
        "injected_issues": len(customer_issue_log_df)
    },
    {
        "dataset": "products",
        "injected_issues": len(product_issue_log_df)
    },
    {
        "dataset": "orders",
        "injected_issues": len(order_issue_log_df)
    },
    {
        "dataset": "order_items",
        "injected_issues": len(order_item_issue_log_df)
    },
    {
        "dataset": "payments",
        "injected_issues": len(payment_issue_log_df)
    },
    {
        "dataset": "returns",
        "injected_issues": len(return_issue_log_df)
    }
])

total_injected_issues = int(
    issue_log_summary["injected_issues"].sum()
)

display(issue_log_summary)

print("--------------------------------")
print("Total intentionally injected issues:",
      total_injected_issues)

       dataset  injected_issues
0    customers             1400
1     products               70
2       orders             1000
3  order_items              950
4     payments              650
5      returns              500

--------------------------------
Total intentionally injected issues: 4570

In [318]:
# ---------------------------------------------------------
# Step 157:
# Calculate Dataset Size and Overall Injection Rate
# ---------------------------------------------------------

source_volume_summary = pd.DataFrame([
    {
        "dataset": "customers",
        "rows": len(audit_customers)
    },
    {
        "dataset": "products",
        "rows": len(audit_products)
    },
    {
        "dataset": "orders",
        "rows": len(audit_orders)
    },
    {
        "dataset": "order_items",
        "rows": len(audit_order_items)
    },
    {
        "dataset": "payments",
        "rows": len(audit_payments)
    },
    {
        "dataset": "returns",
        "rows": len(audit_returns)
    }
])

total_source_records = int(
    source_volume_summary["rows"].sum()
)

overall_injection_rate = (
    total_injected_issues
    / total_source_records
    * 100
)

display(source_volume_summary)

print("--------------------------------")
print(
    "Total source records:",
    f"{total_source_records:,}"
)

print(
    "Total intentionally injected issues:",
    f"{total_injected_issues:,}"
)

print(
    "Overall injected issue rate:",
    f"{overall_injection_rate:.4f}%"
)

       dataset    rows
0    customers   50200
1     products    2010
2       orders  120100
3  order_items  307309
4     payments  120100
5      returns    6560

--------------------------------
Total source records: 606,279
Total intentionally injected issues: 4,570
Overall injected issue rate: 0.7538%

In [319]:
# ---------------------------------------------------------
# Step 158:
# Save Stage 2 Generation Audit Summary
# ---------------------------------------------------------

stage2_summary = pd.DataFrame([
    {
        "metric": "Total Source Records",
        "value": total_source_records
    },
    {
        "metric": "Operational Datasets",
        "value": len(source_volume_summary)
    },
    {
        "metric": "Intentionally Injected Issues",
        "value": total_injected_issues
    },
    {
        "metric": "Injected Issue Rate (%)",
        "value": round(overall_injection_rate, 4)
    }
])

display(stage2_summary)

print("\nDataset Volume:")
display(source_volume_summary)

print("\nInjected Issues:")
display(issue_log_summary)

                          metric        value
0           Total Source Records  606279.0000
1           Operational Datasets       6.0000
2  Intentionally Injected Issues    4570.0000
3        Injected Issue Rate (%)       0.7538

Dataset Volume:

       dataset    rows
0    customers   50200
1     products    2010
2       orders  120100
3  order_items  307309
4     payments  120100
5      returns    6560

Injected Issues:

       dataset  injected_issues
0    customers             1400
1     products               70
2       orders             1000
3  order_items              950
4     payments              650
5      returns              500

In [320]:
# ---------------------------------------------------------
# Step 159:
# Export Stage 2 Audit Results
# ---------------------------------------------------------

REPORTS_DIR = PROJECT_ROOT / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

# Save overall project summary
stage2_summary.to_csv(
    REPORTS_DIR / "stage2_generation_summary.csv",
    index=False
)

# Save dataset volumes
source_volume_summary.to_csv(
    REPORTS_DIR / "stage2_dataset_volume.csv",
    index=False
)

# Save injected issue counts
issue_log_summary.to_csv(
    REPORTS_DIR / "stage2_injected_issues.csv",
    index=False
)

# Save detailed quality audit
quality_audit_summary_df.to_csv(
    REPORTS_DIR / "stage2_quality_audit.csv",
    index=False
)

print("STAGE 2 AUDIT FILES EXPORTED")
print("----------------------------")

for filename in [
    "stage2_generation_summary.csv",
    "stage2_dataset_volume.csv",
    "stage2_injected_issues.csv",
    "stage2_quality_audit.csv"
]:
    path = REPORTS_DIR / filename
    print(
        f"{filename}:",
        "SAVED" if path.exists() else "MISSING"
    )

STAGE 2 AUDIT FILES EXPORTED
----------------------------
stage2_generation_summary.csv: SAVED
stage2_dataset_volume.csv: SAVED
stage2_injected_issues.csv: SAVED
stage2_quality_audit.csv: SAVED